### ISSUE TITLE
Sort photos in chronological order

### ISSUE THREAD

**Issue by heikobornholdt** [electerious/Lychee#10]
Hi,

your software looks nice, but I missed a function to sort all photos in chronological order.

Thank you

**Comment by mnemonicflow** [comment]
If it is planned why is the issue closed? The issue should remain opened until such feature is implemented!

**Comment by heikobornholdt** [comment]
You're right

**Comment by mnemonicflow** [comment]
@heikobornholdt Does Lychee have such a feature yet? I can't find anything in the UI to change the sorting.

**Comment by mnemonicflow** [comment]
@heikobornholdt You can close this issue again :-)

**Comment by electerious** [comment]
Yes, it's implemented ;)

**Comment by heikobornholdt** [comment]
:smile:
