### ISSUE TITLE
Add feature "merge with album"

### ISSUE THREAD

**Issue by auzias** [electerious/Lychee#166]
When we right click on an album it would be great if we could choose "merge album with..." and then choose the album within which we want to merge.

Once again, great work ! Go on :)

**Comment by rhurling** [comment]
I'm going to try to make a PR for the v3 Branch for this since I really need this feature

**Comment by auzias** [comment]
:+1:
Keep us updated

**Comment by rhurling** [comment]
I think I have [something that should work](/rhurling/Lychee/tree/release/v3.0.0) (using the Multiselection, not yet for single Albums and then selecting another one).

I'll just have to test it to see if it works.

**Comment by electerious** [comment]
I don't think it should show up for single albums, using multi-select for this is a great idea. Looking forward!

**Comment by rhurling** [comment]
Problem with that is if you want to merge multiple albums which are not next to each other.
Something like a Shift-Select would be needed for that.

**Comment by electerious** [comment]
You're right. I would suggest something like the "Move"-photo-entry. You click on "Merge" and it shows a list of all albums, expect the one you clicked. Using multi-select would be even faster, because there's no need to show a list in this case. An additional confirm dialog should be added before merging the albums.

**Comment by rhurling** [comment]
Okay.
I'll see if I can implement the Shift/Comand-Selection from [this fiddle](http://jsfiddle.net/bMgpc/170/) into multi-select and If not go with the "Move"-photo-entry (or I'll just go with both).
And I'll have to figure out how to add the confirm dialog.

**Comment by electerious** [comment]
Skip the shift/comand-Selection for now. I already thought about an improved way to select albums, including keyboard navigation and shift/comand-Selection. Will open a separated issue for this feature as it's complex and affects more parts of Lychee.

**Comment by rhurling** [comment]
Okay, will do

**Comment by electerious** [comment]
#339
