### ISSUE TITLE
L2.5 - Title cut after ÄÖÜ in Filename

### ISSUE THREAD

**Issue by PatrickSp** [electerious/Lychee#176]
I have filenames with Ä,Ö,Ü like
"2014.06.26_171615_Tarox_Hübi.jpg"

Lychee cut the Title after Ä,Ö,Ü 
![zwischenablage](https://cloud.githubusercontent.com/assets/7984404/3417079/3922a212-fe34-11e3-80c1-40a58549c062.jpg)

**Comment by electerious** [comment]
I'm not able to reproduce this issue. Could be already fixed in a newer version.
