### ISSUE TITLE
[Feature] Manual sort order

### ISSUE THREAD

**Issue by chrismarquardt** [electerious/Lychee#192]
When I present pictures, I usually want to tell a story or at least present the pictures with some sort of arch. Currently everything is sorted automatically and sort order can only be configured within limits. I would love to be able to sort pictures and/or albums manually.

**Comment by bravobih** [comment]
I'm also very interested in such option.  I tried to change the order by creating a new album and moving the photos in the order that I want to get.  But after this operation all photos in the new album were in the order as in the source album.  Isn't still any option to  change the order?

**Comment by electerious** [comment]
You can change the order in the settings, but there's no way to sort them manually.

<img width="536" alt="sorting" src="https://cloud.githubusercontent.com/assets/499088/9393225/256f1ca4-4781-11e5-8a19-a2721c1f7045.png">

**Comment by mck182** [comment]
> Catching "edge cases" like: Fixing position when the user moves one or more photos to another album; Fixing position when the user deletes photos…

I actually don't think you'd need to fix the "position" in those cases as long as you use it only for sort-ordering (eg. ORDER BY position ASC). It would still work. Then when there are manual moves within the same album, you would just update the range from the moved photo to the end.

So eg. you've deleted one photo and you have this sequence:
1 2 3 5 6

The order is still correct. Now you move 6 to be after 2:
1 2 6 3 5

Next you just take the position before 6, which is 2, and correct all the positions afterwards with simple increment, so you'd end up with:
1 2 3 4 5

...and at this point the edge case fixed itself :)

Similarily,
1 2 3 5 6 -> move 1 after 3 -> 2 3 1 5 6 -> start from 3 and increment till the end -> 2 3 4 5 6.

I don't think it must start from 1 and end with "album.size()", it's just a sorting attribute after all :)

This could also make it quite easy to implement - you just need some id of the image being moved and some info where it was dropped, for example which image is before. Then in the backend you get the index of the before image, put the moved image after it in the array and then iterate from the before-index to the end, changing the sort attributes and running an UPDATE query.

Well, uhh..just throwing some random ideas around...that said, I too would welcome this feature :)

**Comment by electerious** [comment]
@mck182 Thanks for the idea. That should work fine! I guess the back-end implementation shouldn't make any trouble. Adding a good drag and drop sorting to the front-end is way harder.

**Comment by omichalek** [comment]
Wouldn't it be better to store the position not within the photo, but somewhere inside the album?

The main reason I think of is when one reaches the photo from a different context (for example a tag in the future), the position suddenly becomes irrelevant

I don't have the insider knowledge, but reading about collections here https://github.com/electerious/Lychee/issues/254#issue-46959878 I would think that an analogous solution could work for sorting the photos within album: 

> A new MySQL table called lychee_collections with id, title, description, sysstamp, public, visible, downloadable, password and albums. The last one contains a list of albumIDs, separated by commas.

Wouldn't it be better to store the list of photos (separated by commas) and optionally arrange them according to the list as well? But as said, I might be completely off

**Comment by artkrz** [comment]
👍 for manual order per album.

**Comment by aplsms** [comment]
I have sort command for sorting albums by latest photo date:

update a1 set sysstamp=(select  max(takestamp) as date from lychee__lychee_photos group by album where lychee__lychee_photos.album=a1.id);

It would be nice to have special button in the album menu;

**Comment by Kyoshiro-san** [comment]
Hello,

To follow up to mck, you can do this whenever a photo is moved:
* After asking for a move in the UI, let's assume the album ID is _Aid_, the moved picture'd id _Pmoved_id_ and the new next-to-it picture's position _Pnext_pos_
* I think this very simple query could work (no need to renumber, but correct me if I'm wrong): UDPATE `lychee_photos` SET `position` = `position` + 1 WHERE `position` >= _Pnext_pos_ AND `album_id` = _Aid_;
* Then you set the moved picture's position to freed number _Pnext_pos_: UPDATE `lychee_photos` SET `position` = _Pnext_pos_ WHERE `id` = _Pmoved_id_;

I know this would increase ids forever and never renumber but I don't think someone would reorder pictures more than what a bigint would allow ^^. Maybe there could be some safety checks for that and a renumber job that could be run from the admin ?

Cheers
Loïc

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
