### ISSUE TITLE
Do not disable right-click

### ISSUE THREAD

**Issue by rom1v** [electerious/Lychee#213]
I don't know the reason, but right-click is disabled on Lychee, which is irritating.

Some browser features can be accessed using the right-click (even if some are also accessible with a menu or a shortcut).

**Comment by PeterTheOne** [comment]
I'm also for not disabling right-click. If the user tries to copy past his user/password he/she can't use the right-click menu.

**Comment by electerious** [comment]
True! I think right-click should only be disabled where Lychee uses its own right-click menu. Inputs are a good point.

**Comment by electerious** [comment]
Fixed in v3.0
