### ISSUE TITLE
Amazon S3 implementation

### ISSUE THREAD

**Issue by deimosfr** [electerious/Lychee#223]
Hi,

It would be good to store to Amazon S3. What do you think about it?

Thanks

**Comment by garygitton** [comment]
+1 on s3 implementation.

**Comment by joelmeyerhamme** [comment]
Would anyone consider writing a plugin for this?

**Comment by emory** [comment]
I'd be so pleased with this — it's my only real issue with Lychee that I like to host it outside my house and smaller instances are ideal but I end up paying more for storage with less availability. I'm happy to test but lack the skillset required to implement.

**Comment by Bramas** [comment]
No need for a plugin I think. I'm currently using it (actually an equivalent), and it works like a charm.

Just use s3ql to mount your storage as a hard drive, then create a lycheePhotos folder, move all your picture located on uploads/big/* into it, remove uploads/big and create a symbolic link from uploads/big to lycheePhotos.
When mounting with s3ql, make sure user permission are not ignored and set the right permission to lycheePhotos.

Everything is fast.
You should definitly try this. If you are scared, with a small number of photos (it will cost you 3cents)

**Comment by gnarmedia** [comment]
I am considering writing something like this soon if enough people find it useful.

**Comment by emory** [comment]
The only caveat @Bramas, is that people on PaaS/hosting environments likely can't use userspace filesystems like those provided by `fuse` and I imagine `s3ql` is something that uses `fuse` to mount an S3 bucket as a filesystem?

I could go that route but I think a native plugin would be more flexible and also allow me to run Lychee on a service like Gandi's PHP application instances like I do today but leverage that S3 storage directly via the S3 API and not require `fuse` filesystems.

**Comment by Bramas** [comment]
You're totally right.

**Comment by smw355** [comment]
+1 on native plugin support for S3!

**Comment by teohhanhui** [comment]
Use a filesystem abstraction layer such as http://flysystem.thephpleague.com/ to avoid having to support specific storage services.

**Comment by emory** [comment]
That's been suggested, @teohhanhui, but does nothing for users in environments where they cannot use userspace filesystems.

**Comment by emory** [comment]
OK @teohhanhui was not suggesting what I thought they were. Flysystem in Lychee would probably be sufficient to solve everyone's problems as long as they could use composer. I am not sure if users in hosting environments (my use-case) would be able to use it or not; the best solution would probably be one that can be bundled with Lychee for end-users, but it supports the majority of file bucket and storage back-ends that would be desired.

**Comment by Bramas** [comment]
I don't think it *need* composer. I mean, we can easily include flysystem in a plugin, as a lib.

**Comment by electerious** [comment]
How about creating a dedicated class for all file related tasks like reading/saving in Lychee? Could be replaced easily with a custom implementation for S3 and doesn't require to add S3 directly into Lychee.

**Comment by teohhanhui** [comment]
@electerious That's exactly what a filesystem abstraction library like Flysystem provides. Please avoid building your own...

I'd also highly recommend using composer for dependency management. You can of course still include the installed dependencies into a distribution file if needed (but they shouldn't be checked in to the version control).

**Comment by emory** [comment]
@electerious My first impression of @teohhanhui's recommendation was apprehensive but after reading about Flysystem in more detail I thought it was an excellent suggestion, at least from the end-user perspective.

**Comment by geekpete** [comment]
Scaleway also has S3 compatible storage that would benefit from being able to set the endpoint url with standard S3 libraries.

**Comment by anklaa** [comment]
+1 This would be one "killer feature". Even the Adobe Cloud does not support something similar. 
A couple of reason, why this feature could be very interesting for photographers: 
- Amazon S3 storage is cheap
- It's easy to backup your files form your client (windows||mac) to s3
- You could run lychee on an ec2-webserver

**Comment by llamallama** [comment]
This seriously needs to happen

**Comment by arno01** [comment]
And now, having the Minio [Minio is an open source object storage server with Amazon S3 compatible API](https://minio.io) -- this would be marvelous to see the S3 API compatibility!

**Comment by StephenDart** [comment]
would really like a minio integration or other s3 compatible store.
Would be good to define a bucket for photos, and then have the same password enabled folders below, or if not possible as least have a bucket for a folder. 
Looking at the api, think it would need a :before to create a bucket/folder, unless its predefined as a location. 
There is a few available php s3 classes that could be used.

**Comment by arno01** [comment]
Not sure if that helps, but since I do enjoy the Lychee, I've just setup a monthly donation to the project. :-)
The Donate button is at the bottom of this page https://lychee.electerious.com/

**Comment by Coysh** [comment]
+1 for this

**Comment by mickael-kerjean** [comment]
If you need S3 or minio support, I released [this](https://github.com/mickael-kerjean/nuage/wiki/Release-0.2:-Photo-Management)

**Comment by arno01** [comment]
@mickael-kerjean nuage looks like a really nice interface and very likely will replace Lychee for my use-case. Where can I find ``nuage_transcode`` code?

**Comment by mickael-kerjean** [comment]
@arno01: yep that's the one. and that's the exact idea as transcoding is quite CPU intensive and can make the entire thing feel slowish when you try to render multiple RAW pictures from DSLR

**Comment by arno01** [comment]
One could also use in-built Gallery in the Nextcloud along with the S3 external storage module.
I have tested it with the Minio, it is working as long as there are no directories. It will work with the directories once https://github.com/nextcloud/server/issues/9808 is resolved.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
