### ISSUE TITLE
[Feature] System informations

### ISSUE THREAD

**Issue by Venopsis** [electerious/Lychee#227]
Hi,

What do you think about add a line about plugins into the system informations page?

Example:

System Information
------------------
Lychee Version:  2.6.2
DB Version:      020602
System:          Linux
PHP Version:     5.4
MySQL Version:   50537
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugin: Watermark / Plugin2 / Plugin3

It would be great to be sure if one plugin is actived correctly or not.

--
Cordially, Venopsis

**Comment by electerious** [comment]
Implemented.
