### ISSUE TITLE
ctrl+a also selects the "about" tab

### ISSUE THREAD

**Issue by TheZoker** [electerious/Lychee#230]
Hi there,

Pressing ctrl+a selects all images, thats great!
But it does also selects all information in the "about "tab

![img_2014 09 15_12h00m37s_001_](https://cloud.githubusercontent.com/assets/1368405/4269678/44c33e5a-3cbf-11e4-83e9-d6aa4a973043.png)

Please fix it :)

**Comment by electerious** [comment]
Fixed in the next version of Lychee (v3.0).
