### ISSUE TITLE
Ugly thumbs for images with transparency using ImageMagick

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#235]
When ImageMagick is installed on the system, generated thumbnails from transparent photos are looking ugly.

Transparent photo attached for testing (Hardly/Not visible on GitHub). Anyone knows a solution? (@bb-Ricardo maybe?) 

![thumb](https://cloud.githubusercontent.com/assets/499088/4567542/32d9c7c4-4f32-11e4-8ef7-e3588425304d.png)
![transparent](https://cloud.githubusercontent.com/assets/499088/4567549/3ed84b4a-4f32-11e4-94fa-1cf1b0ee99f6.png)

**Comment by HoffmannP** [comment]
Do you have any idea how you would like lychee to handle this issue?
One could put any picture over a checkerboard pattern like some graphic programs

**Comment by bb-Ricardo** [comment]
This is what I came across: http://stackoverflow.com/questions/6742718/php-imagick-detect-transparency
At the moment it seems very hard to detect.
Except you want to use the command line, which seems silly.

And adding a image to every image slows down the process, as it effects only ~5% of images regularly.

**Comment by HoffmannP** [comment]
We could use

    (new Imagick($FILE))->identifyImage()['type'] == 'PaletteAlpha'

for PNGs only. You are right, alpha only effects only 5%, but also only PNGs which are quite rare among usual photos, so that might be worse a try

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
