### ISSUE TITLE
Poor performance with many albums

### ISSUE THREAD

**Issue by r0x0r** [electerious/Lychee#241]
With a large number of photos, it takes quite a bit for photos to load. It would be nice to display an animation, while photos are being loaded to signal the user that something is going on.

**Comment by kfriedenberger** [comment]
r0x0r, this didn't work for me on v 3.0.3; slightly tweaked implementation below. now my 21,000 photo repository with hundreds of albums fires up quickly; there was also a sorting issue to be fixed

        public function getAll($public) {

                # Check dependencies
                self::dependencies(isset($this->database, $this->settings, $public));

                # Call plugins
                $this->plugins(__METHOD__, 0, func_get_args());

                # Initialize return var
                $return = array(
                        'smartalbums'   => null,
                        'albums'                => null,
                        'num'                   => 0
                );

                # Get SmartAlbums
                if ($public===false) $return['smartalbums'] = $this->getSmartInfo();

                # Albums query
                $query = Database::prepare($this->database, "SELECT a.id, a.title, a.public, a.sysstamp, a.password, p.thumbs FROM (SELECT album, GROUP_CONCAT( thumbUrl SEPARATOR  '|' ) AS thumbs FROM ? GROUP BY album ORDER BY star DESC) AS p JOIN ? a ON p.album = a.id WHERE public = 1 AND visible <> 0 ORDER BY " . substr($this->settings['sortingAlbums'], 9),  array(LYCHEE_TABLE_PHOTOS, LYCHEE_TABLE_ALBUMS));
                if ($public===false)
                        $query = Database::prepare($this->database, "SELECT a.id, a.title, a.public, a.sysstamp, a.password, p.thumbs FROM (SELECT album, GROUP_CONCAT( thumbUrl SEPARATOR  '|' ) AS thumbs FROM ? GROUP BY album ORDER BY star DESC) AS p JOIN ? a ON p.album = a.id ORDER BY " . substr($this->settings['sortingAlbums'], 9),  array(LYCHEE_TABLE_PHOTOS, LYCHEE_TABLE_ALBUMS));

                # Execute query
                $albums = $this->database->query($query);
                if (!$albums) {
                        Log::error($database, __METHOD__, __LINE__, 'Could not get all albums (' . $database->error . ')');
                        exit('Error: ' . $this->database->error);
                }

                # For each album
                while ($album = $albums->fetch_assoc()) {

                        # Parse info
                        $thumbs = $album['thumbs'];
                        $album = Album::prepareData($album);


                        # Process thumbnails
                        if (($public===true&&$album['password']===false)||($public===false)) {
                                $k = 0;
                                $thumbs = explode("|", $thumbs, 4);

                                if (is_array($thumbs)) {
                                        foreach ($thumbs as $thumbUrl) {
                                                $album['thumbs'][$k] = LYCHEE_URL_UPLOADS_THUMB . $thumbUrl;
                                                if (++$k == 3) break;
                                        }

                                }
                                # Add to return
                                $return['albums'][] = $album;
                        }
                }

                # Num of albums
                $return['num'] = $albums->num_rows;

                # Call plugins
                $this->plugins(__METHOD__, 1, func_get_args());

                return $return;

        }

**Comment by electerious** [comment]
@kfriedenberger So sorting works fine in your version? Can you open a PR?

**Comment by kfriedenberger** [comment]
Yes and will do

----------------------
Kirk Friedenberger
312.925.2661

**Comment by electerious** [comment]
#372

**Comment by Thomvh** [comment]
Opening Lychee takes ages here. Only got 1600 photo's uploaded of the total 22.000.

**Comment by electerious** [comment]
@Thomvh  Yes, there's a known performance bottleneck. We need to fix the bug mentioned in this issue. Here's an unfinished solution: https://github.com/electerious/Lychee/pull/372 Help is welcome!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
