### ISSUE TITLE
Lightbox function not working correctly in Android browser

### ISSUE THREAD

**Issue by StefanOltmann** [electerious/Lychee#244]
I noticed on my Android 4.0.4 tablet that the "lightbox function" (where you view the images in large and navigate back & forth) is not working correctly in the Android stock browser. The image is displayed, but if you try to navigate instead you scroll the album behind that picture. It's a strange behaviour.

However, if you use a current chrome for Android app, it works.

**Comment by electerious** [comment]
Closing the issue because it's outdated and maybe fixed.
