### ISSUE TITLE
Block access after 10 wrong login attempts

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#246]
The login should be blocked after 10 wrong login-attempts for at least 10 minutes.

- A value `blocked` should be added to `lychee_settings`. `0` when unblocked and filled with a timestamp when blocked.
- Add to the `settings.md` and `faq.ms` how to unblock
- Add error to the front-end

**Comment by lbdroid** [comment]
I disagree with this being added as a feature of this software. What is required from this software's end, is only to generate clear log events to the system log indicating successful and failed login attempts. It should be up to the system to monitor the logs and control access, using something to the effect of fail2ban.

**Comment by electerious** [comment]
This feature won't be part of Lychee. Lychee will only log failed log in attempts as suggested by @lbdroid and @qligier: #382.
