### ISSUE TITLE
No search option while loged out

### ISSUE THREAD

**Issue by jelferink** [electerious/Lychee#249]
We are not able to search through the pictures if we are not loged on. Search is only visible after logging in. We use the latest version.

**Comment by suiluj** [comment]
Hello :)
I would like to have a search function for all my users, too.

Perhaps now is the time? ;)
Thanks a lot for your great gallery. :+1: 

Julius

**Comment by oxidworks** [comment]
Hi, this would be an interesting feature. I would like to see it as an opt in :-)
Cold we speed up the implementation with a donation?
Thanks anyway for this nice software :thumbsup:

**Comment by waldenn** [comment]
I needed the same feature. This fix below worked for me. Just add an extra input element into the public header section:

~~~~
    <div class="header__toolbar header__toolbar--public">

      <a class="button" id="button_signin" title="Sign In">
        <svg class="iconic"><use xlink:href="#account-login"></use></svg>
      </a>

      <a class="header__title"></a>
      <input class="header__search" type="text" name="search" placeholder="Search ~@�">

    </div>
~~~~

**Comment by dennisSmidswater** [comment]
Yeah i ran into the same question, is it possible to search without being logged in?

**Comment by phraemer** [comment]
> The demo is modified version where the user is always logged in.

This is a real shame as the rest of it is pretty great. I spent several hours setting this all up and testing it out only to find out that demo feature doesn't work as presented. Please make it clearer so nobody else who needs this wastes their time. Thanks.

**Comment by mp-drew** [comment]
This is literally the only thing preventing me from using this otherwise great software. It would be nice to have an admin user and then everyone else just goes to the site and searches.

**Comment by phraemer** [comment]
I wonder if you would consider some sort of fund raising for features?
I'd pledge some money to get this for example. You could set a goal amount and maybe 4 or 5 people could chip in for a few hours of your time?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
