### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#254]
- Collections are "virtual album groups"
- Collections can be marked as private or public (In this case the sharing of the albums will be overwritten)
- Collections can only contain references to albums, not to photos or other collections
- Each album can be located inside on Collection only

Implementation:
- [ ] A new MySQL table called `lychee_collections` with `id`, `title`, `description`, `sysstamp`, `public`, `visible`, `downloadable`, `password` and `albums`. The last one contains a list of albumIDs, separated by commas.
- [ ] Lychee => Smart Albums, Collections, Albums
- [ ] On the top right of Lychee: Add => Add Collection
- [ ] Move Album to Collection via right-click or toolbar-button
- [ ] Back-Buttons needs to go back to the parent collection when inside an album
- [ ] Search should find and list Collections

The ability to share (mark as private or public) should be implemented later. The first iteration of Collections should be as simple as possible and just contain a group of albums, without other additional benefits beside the grouping. New features should be added after.

**Comment by lustyffh** [comment]
any updates on this feature? Looking forward to see some structure for my many albums

**Comment by electerious** [comment]
No news, yet.

**Comment by horst2** [comment]
Hello,
is there a plan, when this feature will be available? Horst

**Comment by candoucreative** [comment]
Any news ?

**Comment by electerious** [comment]
A lot of stuff has been rewritten for Lychee v3.0. There're still no Collections, but I'm looking forward to implement them.

**Comment by candoucreative** [comment]
is there any date for v3.0?

**Comment by electerious** [comment]
Will be finished when it's ready :) No ETA, yet. I guess it will take some time.

**Comment by pmichelazzo** [comment]
Did you have a place where we can see the roadmap? This could be nice for everyone thinking to help you.

Regards

**Comment by electerious** [comment]
Sorry, but there’s currently no roadmap available. I'm choosing from often requested features or features I think it’s worth to spend time on, but there’s no real order or roadmap.

**Comment by Codelica** [comment]
Would love to see this.  It's the one feature that keeps me from bringing in a rather large collection.  Hope there is time at some point. :)

**Comment by palitu** [comment]
I agree with this, I use lycheesync to get all of my photo's into lychee, and typically i have my unsorted folder structure:

|--2014
|       |--1_Jan
|       |--2_Feb
|       |--3_Mar
|       ..
|--2015
|       |--1_Jan
|       |--2_Feb

etc.

it really does make a mess of the front page.  So i am really looking forward to collections!

I would then create virtual albums - where i would mark individual photos to go into certain folders, either "Misc_2015" or "Our_Camping_Trip", which would all be sorted by year.  But i guess in this case, i will have to create physical albums to import into lychee.  maybe even an albums instance and an all photos instance of the site .

**Comment by Dasoren** [comment]
Any update on this?

**Comment by adhawkins** [comment]
I'm considering moving from Gallery as it is now an abandoned project. However, I organise my albums into categories, which contain sub albums at various levels of depths (currently 3 or 4 levels deep as a maximum).

I'd be more inclined to move over to Lychee if it were to support this feature. I've installed it and had a play and was somewhat surprised to find that all albums had to exist at the top level.

Any expectation on when such a feature is to be implemented? The proposed 'Collection' that can only contain other albums probably wouldn't cut it for me. Personally I'd prefer it if there were no distinction. An album can contain either images, other albums or both. There is (AFAICS) no real reason to limit it to the proposed feature.

Would appreciate some idea as to whether this is likely, or if I need to continue my search for a suitable replacement for Gallery.

Thanks

Andy

**Comment by electerious** [comment]
Hey @adhawkins, there're no real technical reasons to limit it to the proposed feature, but implementing unlimited album and photo nesting would add another layer of complexity. Especially UX wise. Lychee focuses on simplicity, that's why I want to stay with the proposed 'Collections'. It's not planned to add various levels of depths and it's not yet sure when this feature will be implemented.

**Comment by liljenstolpe** [comment]
I like the concept of collections, but I would actually like to make them based on tags/keywords in the photos themselves.  For example, I may keyword an image with both 'camping' and 'aurora'.  I would like it to actually show-up in both the 'camping' and 'aurora' collection.

**Comment by palitu** [comment]
yeah, i have been playing with tags, and trying to use lychee to sort out
our bulk photos, but there doesn't seem to be a nice way to view all the
tags.

a tag based collection would work really well.

Typically, we go through and tag a batch based on an event - "christmas
2015", or go through the lot and find some that don't fit a category
"2015", so that we can see all of our nice photos from 2015.

i would add to the right click context menu Tagging, and have a list of the
last 5 or so tags that have been entered, so that it is easy to add to the
collection, then a search box or something to find the other tags.

Using tags seems like most of the work has been completed already, and it
is just a method of showing the collections that is required to have
something functional.

**Comment by baataboom** [comment]
I struggled just a bit getting Lychee install on Solaris 11, but finally got it after a couple of days. Then I found this 'issue' when uploading photos.  I really like Lychee. But not being able to have subgroups (Collections, subfolders, virtual albums, whatever) of photos is a showstopper for me. When you have thousands of photos, there is a real need for multiple layers of subgroups of photos. I really don't see how others are managing without this feature.

Anyhow, Lychee looks like a good fit for me in the future. But I'll have to wait further until this feature implemented. I'm glad to see it is being worked.
Thanks

**Comment by palitu** [comment]
I have it by naming my folders YY-MM, and having them sorted by titie.

that being said - i would love collections!

**Comment by palitu** [comment]
For me - i want to basically have a nice web front end, that mimics the
folder structure i have in place for my photos.

I get them onto my server via owncloud - but the gallery is not up to
scratch yet, then i sort using a sort photo script nightly, then sync
lychee via lycheesync.  these are the 'raw' photos, unsorted etc.

works great, but i would love to being able to assign photos to albums, so
have general 2016 photos, birthdays, holiday etc.

**Comment by pyro2927** [comment]
@palitu: my use case is identical to yours.  Would love collections for this reason.

**Comment by electerious** [comment]
[Quote](https://github.com/electerious/Lychee/issues/607) from @hrniels:

> Yes, we are working on a subalbum feature. See the branch feature/subalbums. It's not completely finished yet and you also need to rebuild dist/* first (see docs/Build.md), but you can already give it a try, if you like.

**Comment by haivala** [comment]
Any updates on this?

**Comment by electerious** [comment]
@hrniels Is there anything from your side that has to be done before we can ship sub-albums? Here're my two pending todos:

- [ ] Improve "Add Album" dialog => Always add to current album / no select
- [ ] Testing

**Comment by hrniels** [comment]
I don't have anything for sub-albums anymore. But some time ago I started to extend the multi-select feature to allow selective downloads, which is kind of related, because the multi-select is in the same branch. However, I couldn't finish that yet, because I had many other things to do recently. I think I can continue with it after the next week.

**Comment by electerious** [comment]
@hrniels Sounds good, but let's put this into a later release.

**Comment by electerious** [comment]
Please help us testing! Here's the fully working PR for sub-albums: https://github.com/electerious/Lychee/pull/639

**Comment by ophian** [comment]
@electerious 
Good work.  Thanks for an easy looking approach for subalbums!
_Testing Feature/subalbums branch..._

What I don't like so far is that you have to add a public photo to the parent(s) album(s), to have an album thumb. 
It would really be nice to give the capability to set one photo "hidden" per album and this to be used as the albumthumb only, if set. This would avoid having one added (public) photo in each parent album just for the thumb and would also help as a quicky to implement and select an individual thumb in the real photo albums.

**Comment by electerious** [comment]
> What I don't like so far is that you have to add a public photo to the parent(s) album(s), to have an album thumb.

The current thumb situation isn't optimal. There's definitely space for improvement.

> Could you also please explain, why you both changed the album id and the new parent fields to the 14-digit microtime+ bigint approach?

Lychee uses the microtime approach for a while now (correct me if I'm wrong). It's possible to share photos as hidden without a password. A simple id would be too easy to guess. The approach has been discussed already and it was the best solution for the problem.

**Comment by ophian** [comment]
> Lychee uses the microtime approach for a while now (correct me if I'm wrong).

You should know it... :) Yes, for the photos.  The albums had the better simple IDs. This changed with the 3.2.0 test version. I wanted to keep them being simple to better distinguish between albums and photos approaches. IMHO it does not matter that you can guess them, they are public or not.

> It's possible to share photos as hidden without a password.

But not to choose the one as the album thumb, where there are more.

**Comment by kasim1r** [comment]
+1 from me. Essential feature. 👍 :

**Comment by ultramizer** [comment]
So, as we are seeing this project taking up the pace again, can we talk about this request again please? What would it take to implement folders or collections as described in this post? This feature is really the only thing keeping us from using Lychee at the moment, since we need to manage big databases by customer, year and job, and this would kinda be a good option for that!

**Comment by AkselMeola** [comment]
I was thinking about it. It would be cool if there were some collections or smth, but then I realized that maybe there is a simpler option just to get some sense into the organization. 
My worry is basically such: I want my albums be categorized into years. So each year would have some sort of separation from other albums. 

My simple idea for it was to maybe create some kind of "category" option for albums and in the view it would just make a separated sections with the category title. 

Category title 1
----------------------------------------------------
Album 1, Album 2, ...

Category title 2
----------------------------------------------------
Album 3, Album 4, ...

A special settings would allow to either use this categorization or not. 
It is a very basic idea, but maybe easier to solve initially. Anyway, just my 2 cents into the matter.

**Comment by flainn** [comment]
I like the looks of Lychee, and I've finally got it set up and working, but I was rather astounded to find that not only does Lychee not support nested folders -- the feature has been on your to-do list for nearly four years!

I'm afraid I'm going to have to go with one of your competitors, perhaps CopperMine. Not being able to organize 20 years / hundreds of gigabytes of photos into nested folders is a deal-breaker.

Do let us know if you ever implement this feature, and I'll take another look.

**Comment by augras** [comment]
Hello, i would like to know if the subfolders feature will be soon include in the master branch ?
Thank you for your work and an answer.
Philippe

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
