### ISSUE TITLE
password protected guest

### ISSUE THREAD

**Issue by georg90** [electerious/Lychee#267]
Hi!
Beautiful work! Really like the style of Lychee :)

I'd like to use it as a personal photo "backup" to show the images to family/friends simply by visiting a website.
So in general all images should be password protected..
Lychee only features a password protection for public albums/links, but this way I'd have to enter the password everytime a want to see an album.

I created a rather hacky solution: https://github.com/georg90/Lychee/commit/22f4e8837c5303f0351d6522dad6ed126b7e73df
Where I check if the session is already started (from Lychee login) if not create a new and check if the user is logged in..

Before Lychee I have a simple login page like this:

```
<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
if(isset($_POST['submit'])) { 
$password = $_POST['password']; 
if($pass === $password) { $_SESSION['GUEST_LOGIN'] = "logged_in";  
header("Location: Lychee/");
exit;
}
else { 
header("Location: index.php");
}
}
?>
<form method="post" action="index.php" class="form-4">
                                    <h1>Login</h1>
                                    <p>
                                        <label for="password">Password</label>
                                        <input type="password" name='password' placeholder="Password" required> 
                                    </p>

                                    <p>
                                        <input type="submit" name="submit" value="Continue">
                                    </p>       
                                </form>
```

So now I run into a problem, whenever somebody is visiting the ```/Lychee``` folder directly from the url - he get's an error message but the ```header ()``` part isn't executed...so the user stays on the empty page and is not redirected to the login page..

Any ideas on a nicer way how to implement the redirect? 
Or is somebody interested in something more substantial and code a "real" password protected guest area?

Thanks!

**Comment by electerious** [comment]
Closing the issue as this feature could be part of the planned Multiuser-functionality: https://github.com/electerious/Lychee/issues/132
