### ISSUE TITLE
UTF-8 SQL-syntax error

### ISSUE THREAD

**Issue by eisensafran** [electerious/Lychee#270]
Hey there,
I have a really annoying problem when setting up lychee. 
The mySQL-database was created successfully (every table is in the right place as far as I can see), but when I try to upload a photo I get only a 500 server status code.
The creation of new albums is no problem.
In the lychee-logfile there is this kind of cryptic error message:
```
- Could not update database 
(You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use 
near '-368952_lychee-as CHARACTER SET utf8 COLLATE utf8_general_ci' at line 1)
```
The PHP-version I am running is 5.3.2, which doas not support UTF-8 as far as I know. Is there a fallback I can use?

Thank you so much for your time!

**Comment by electerious** [comment]
Have you found a solution?

**Comment by eisensafran** [comment]
Nope – my workaround was actually an upgrade to PHP 5.4 witch solved the issue.
