### ISSUE TITLE
Splitting uploads/big directory

### ISSUE THREAD

**Issue by nwl** [electerious/Lychee#271]
I have about 50k photos and it seems that all of the originals will be stored in the big/ directory. Is there some way of creating a hashed structure otherwise the size of the directory is going to cause major performance issues when performing rsyncs etc

**Comment by electerious** [comment]
@bb-Ricardo I like your idea. You are using the first 4 chars of the filename-hash as the folder-name, right?

**Comment by bb-Ricardo** [comment]
exactly. easy to generate and easy to find.

**Comment by electerious** [comment]
This should also work fine with existing photos and only effect new uploads. I will take a look at it!

**Comment by sillygilly** [comment]
@electerious just wondering if this was started, I think it would be a great improvement. Along with lazy image loading for the other issue you linked above.
