### ISSUE TITLE
Open album/photo in new tab when holding ctrl/cmd

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#274]

**Comment by Aidenir** [comment]
I would rather have ctrl/cmd for selecting multiple images, right now its possible to drag select but not selecting multiple images that are not beside each other. Just my 2 cents.

**Comment by electerious** [comment]
[That's planned](https://github.com/electerious/Lychee/issues/339), but the hotkeys may overlap. Good point!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
