### ISSUE TITLE
Upload failure using Lychee with Safari

### ISSUE THREAD

**Issue by davbeny** [electerious/Lychee#279]
Hello,

I've installaed Lychee on a raspberry Pi using the following steps: 

1) apt-get update && apt-get upgrade -y
2) apt-get install php5-fpm php5-gd libgd2-xpm libpcrecpp0 libxpm4
3) apt-get install nginx
4) mkdir /var/www
4) mount /dev/sda1 /var/www (filesystems in ext4)
5) chown -R www-data:www-data /var/www
6) apt-get install -y php5-mysql mysql-server
7)Modify /etc/php5/fpm/php.ini by adding the following:

extension = php_mbstring.dll
extension = php_exif.dll
extension = php_gd2.dll
max_execution_time = 200
post_max_size = 200M
upload_max_size = 200M
upload_max_filesize = 20M
max_file_uploads = 100

8) service php5-fpm restart
9) apt-get install -y git
10) 
cd /var/www
git clone https://github.com/electerious/Lychee.git
mv Lychee/* .
rm -rf Lychee/

rm /etc/nginx/sites-available/default
11) vi  /etc/nginx/sites-available/lychee: 
server {
root /var/www;
index index.php index.html index.htm;
location ~ .php$ {
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
}
}
12) service nginx restart 
13) ln -s /etc/nginx/sites-available/lychee /etc/nginx/sites-enabled/lychee

-Lychee is up and running then, What informations do I need to provide for the database?

-Where can I find the user/password and modify it afterwards in the database?

-I'm unable to upload pictures in the different directories (error 413) when trying with Safari.

Thank for your help

**Comment by electerious** [comment]
That's the content of the file, not the output ;) You need to open the file in your browser. If this is what it shows in your browser, PHP might not be installed correctly.

**Comment by electerious** [comment]
Additional information needed.
