### ISSUE TITLE
provide conf directive to declare path to Image Magick

### ISSUE THREAD

**Issue by calimou** [electerious/Lychee#281]
I am using a synology diskstation running DSM 5.1 where 'convert' resides in /usr/syno/bin - Lychee doesn't seem to find it.

Here is the diag output :
```
System Information
------------------
Lychee Version:  2.7.0
DB Version:      020700
System:          Linux
PHP Version:     5.5
MySQL Version:   50539
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
```

**Comment by electerious** [comment]
Lychee uses `extension_loaded('imagick')` to detect Imagick. I guess it's a problem of your installation or PHP if the Imagick extension can't be found.

**Comment by calimou** [comment]
Ok... It is used as a PHP extension, not as a system command (with "convert"). So indeed, it's not installed and not easily installable on DSM (but I'm OT here.)
