### ISSUE TITLE
processed photo and uploads folder : observation, suggestion

### ISSUE THREAD

**Issue by calimou** [electerious/Lychee#282]
Observation : intuitively I wouldn't have set the folder "uploads" to hold Lychee own processed items (thumbs...etc) but only original/user item.

Here is a simple suggestion, what about isolate "user" vs "lychee internals" data ?
So I'm coming to the "data" folder... processed files could stand in that folder, within a subfolder named "processed" (for example). While keeping "uploads" for import purpose only.

On the top of that, there could also be two configurations directives to set "processed" and "upload/import" folders.

**Comment by electerious** [comment]
This would make sense, but it's not possible to change this without breaking support for existing users. All direct links to photos posted on the web will be broken :-/

**Comment by electerious** [comment]
Will close the issue for now, but keep the idea in mind. Maybe I will find a solution for it.

**Comment by calimou** [comment]
I think something has to be done at least for new installations.

If we are able to change the path of "processed" and raw "upload" folder from Lychee configuration, there would an alternative for then new user to begin with from a good start.

For a new user on the next version, Lychee could use updated paths.

For existing user, nothing change. But if he wants to, he can :) I would say any responsible user knows it's required to read the release notes :) So he becomes aware of the existence of additional configuration directives - which consequences for changing it are documented on the website/wiki and in the config file as comments.

**Comment by electerious** [comment]
The problem with alternative options is that they are hard to maintain. You always need to keep an old installation with the old path to test it. The only option is to move all photos to the new folder. However, this could produce problems for big libraries. The release notes aren't a place to notice this change, as not many users are ready it.

It's a nice idea, but the advantage isn't high enough to give this task a priority.

**Comment by calimou** [comment]
When I say about the release notes, of course it implies it is documented everywhere else it is needed to... 

I don't want to bother too much with this issue, so I'll provide my very last arguments in the hope it gets a little more priority then I'll let it go :) It's only my point of view btw, and you are the only one who decide in the end.

First, not being able to configure where to store files is weird to me. As simple as that. I understand the maintenance benefits and it is a good point but it's not enough to convince me.

It can also leads to some storage issues in specific cases. For example If you want to store files elsewhere than in the same folder level than Lychee you need to have access to a tool that allow you to create symbolic links to walk around the issue. OR... you need to edit code by hand (I saw you suggested this in an issue) ? That's not a solution, at least not better than adding a configuration directive (even with all the potential maintenance drawbacks).

All in all, to me if there should be ONE user-adjustable core setting, it would be that one.

Cheers,

**Comment by electerious** [comment]
Seems like you are talking about defining a custom location for the folder. This is indeed possible and planned, as you already found out (https://github.com/electerious/Lychee/issues/240) :) As this will be configurable one day, it would also make sense to use `data/` for all new installations. I think you are right here. However, other thanks have more priority for now.
