### ISSUE TITLE
Installation on 2.7 didn't work

### ISSUE THREAD

**Issue by Aeggy** [electerious/Lychee#283]
I try to install Lychee 2.7 on a Server of jWeiland.net (Domain Factory) without luck. Whatever i tried it fails with "Connection failed, unable to connect...". I installed Piwigo too and it worked without any problems. I used credentials like this:

DB Host: 127.0.0.3
DB Name: db123456_789 (auto-generated from Server)
Passwort: 123abc456def

The Server environment is:
MySQL 5.6
PHP 5.4.16

Besides Piwigo and Lychee in this Server rund Wordpress and TYPO3 without any installation problems and without any other issues.

**Comment by electerious** [comment]
Can you attach the output of the diagnostics (`lychee/plugins/check/index.php`)?

**Comment by Aeggy** [comment]
Its seems this didn't work: http://sub.domain.de/plugins/check/index.php 
Error 001: Configuration not found. Please install Lychee first.

**Comment by electerious** [comment]
Is there a new table in your database? If not: Could you try to create and specify one in the installation process of Lychee?

**Comment by Aeggy** [comment]
No luck, same error as beginning

**Comment by Aeggy** [comment]
In which file at which line Lychee tries to connect the database?

**Comment by electerious** [comment]
It's a basic connection check using `mysqli`: https://github.com/electerious/Lychee/blob/master/php/modules/Database.php#L81

**Comment by electerious** [comment]
Have you found a solution?

**Comment by Aeggy** [comment]
No, but on Wednesday a good friend of mine will take a look at the code too. May he found a solution.

**Comment by electerious** [comment]
Let me know when you have news. I will close this issue for now.

**Comment by Aeggy** [comment]
Sorry, for my late answer. Working hard to get dbook.org done. So there is no time for me to find the issue.
