### ISSUE TITLE
MySQLi or PDO ?

### ISSUE THREAD

**Issue by calimou** [electerious/Lychee#284]
I was installing the software on a hosting service which doesn't provide MySQLi but only PDO, and noticed Lychee didn't work here - it's a choice and definitively not Lychee's fault of course, but doing a little more research on the subject, I got to the paragraph "Should I Use MySQLi or PDO?" on http://www.w3schools.com/php/php_mysql_connect.asp and it seems PDO could be a better choice if multiple database systems. 

Just wanted to raise this one as information.

**Comment by electerious** [comment]
Yes, PDO would be the better choice with a lot of benefits. It's on the roadmap. However, implementing it will be a lot of work, that's why it may take time. More: https://github.com/electerious/Lychee/issues/83
