### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#285]
`docker build` and `docker run` runs without any errors, but I'm not able to access `localhost:8000`.
	
```
Successfully built bb3bf644d1f8
bash-3.2$ docker run -v /var/lib/mysql --name lychee_data -v $(pwd)/data:/app/data -v $(pwd)/uploads:/app/uploads -i -t -d -p 8000:80 lychee
b88a2035812fe7f992a31db2aabdd930d5fac9b6f51612a6ac6c4e3c3958c095
```

@renfredxh Any ideas?

More about this issue: https://github.com/electerious/Lychee/pull/252

**Comment by onyxrev** [comment]
@electerious I built the image and port 8000 works for me. If you're not on Linux the docker host may not be localhost.  Try this IP on port 8000:

```
env | grep DOCKER_HOST | sed 's/DOCKER_HOST=tcp:\/\/\(.*\):.*/\1/g'
```

**Comment by HoffmannP** [comment]
give us the output of `netstat -ptan` and of `docker ps -a`

**Comment by electerious** [comment]
Great to hear that it's working. I don't have Docker on my computer at the moment, so I will close the issue and suppose that I did something wrong.
