### ISSUE TITLE
Lychee not showing big photos -- and is not uploading files above 2MB

### ISSUE THREAD

**Issue by ortoco** [electerious/Lychee#286]
My lychee script is not showing big pictures and only uploads files smaller than 2MB.
Everything above lychee says "finished" but the photo's wont show at all. When importing from the server directory lychee does load photo's above 2MB. But still wont show big photos in the albums.

Wat could be wrong? I have the permissions 777 set right. And even re-uploaded lychee and installed it into a new clean database to make sure there are no damaged files or something...
My php.ini configuration:
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 35M
memory_limit = 256M
The diagnostics:

Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  2.7.0
DB Version:      020700
System:          Linux
PHP Version:     5.3
MySQL Version:   50529
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.0

http://jeroen.globalchat.nl

**Comment by electerious** [comment]
Could you share an album with some working and non-working photos? It would also be great if you could send me a mail with the login, so I can try it myself (You can find the mail on the [site](http://lychee.electerious.com)). The installation looks fine so far.

**Comment by ortoco** [comment]
I deleted my copy of lychee.






Verzonden met Windows Mail





Van: Tobias Reich
Verzonden: ‎zaterdag‎ ‎10‎ ‎januari‎ ‎2015 ‎00‎:‎30
Aan: electerious/Lychee
CC: ortoco





Could you share an album with some working and non-working photos? It would also be great if you could send me a mail with the login, so I can try it myself (You can find the mail on the site). The installation looks fine so far.
