### ISSUE TITLE
CTRL+R doesn't refresh the page but opens the rename title menu

### ISSUE THREAD

**Issue by PeterTheOne** [electerious/Lychee#288]
CTRL+R doesn't refresh the page but opens the rename title menu, I don't like that. R alone also opens the rename menu, so I guess one could filter for the CTRL+R shortcut.

**Comment by electerious** [comment]
Windows?

**Comment by PeterTheOne** [comment]
Windows/Chrome

**Comment by electerious** [comment]
Ah my mistake. It's fine on OS X. Are there other problematic hotkeys on windows used by Lychee? What would be a cross-platform modifier? Shift?

**Comment by PeterTheOne** [comment]
It's the only hotkey I noticed so far. Btw. Shift+CTRL+R seems to work.

**Comment by PeterTheOne** [comment]
This is maybe an issue of it's own: I think it's strange that you can select images by holding and dragging middle or right mouse button, holding left mouse button should be enough. As far as I know most browsers have the option to scroll through pages by holding and dragging the middle mouse button, so it's a problem that you select images while you try to scroll.

**Comment by electerious** [comment]
Could you take a look at the v3.0 branch? The issue should be fixed (but I'm not sure anymore :d). Let me know if it's working.
