### ISSUE TITLE
Firefox: Strange horizontal scrollbar on div#content

### ISSUE THREAD

**Issue by PeterTheOne** [electerious/Lychee#289]
On Firefox there is a strange horizontal scrollbar on div#content. `#content:before { display:block; }` seems to help.

**Comment by electerious** [comment]
Can you attach a screenshot?

**Comment by PeterTheOne** [comment]
http://s10.postimg.org/dagc9f3cp/lychee_ff_scrollbar.jpg

**Comment by PeterTheOne** [comment]
http://s24.postimg.org/q0ena76ut/lychee_ff_scrollbar.jpg

**Comment by electerious** [comment]
Will take a look at it.

BTW: Don't use the v3.0.0 branch. It's in development and a lot of things may be broken.

**Comment by PeterTheOne** [comment]
thnx
