### ISSUE TITLE
error when using single apostrophe in album description

### ISSUE THREAD

**Issue by PeterTheOne** [electerious/Lychee#290]
I get an `You have an error in your SQL syntax` error when using single apostrophe `'` in the album description.

I'm on the 3.0.0 branch.

**Comment by electerious** [comment]
Some with the current version. Thanks for the report!

**Comment by electerious** [comment]
Does this fix your problem? https://github.com/electerious/Lychee/pull/296

**Comment by PeterTheOne** [comment]
works great, thanks!
