### ISSUE TITLE
$database->set_charset() gives warning with mysql v50095 (and prevents Lychee from loading propertly)

### ISSUE THREAD

**Issue by calimou** [electerious/Lychee#291]
Hi,

I've been testing Lychee to a hosting provider, where those two lines prevent Lychee from loading (I only get Lychee background, no button at all)  : 
```php
		# Avoid sql injection on older MySQL versions by using GBK
		if ($database->server_version<50500) $database->set_charset('GBK');
		else $database->set_charset('utf8');
```

With the following error : 

Warning: mysqli::set_charset(): Error executing query in ..../php/modules/Database.php on line 24

debug info : $database->server_version returns : 50095
running php 5.4.35

Commenting those line "solve" the problem

**Comment by electerious** [comment]
Does the following fix the problem?

```php
if ($database->server_version<50500) @$database->set_charset('GBK');
else @$database->set_charset('utf8')
```

**Comment by calimou** [comment]
Yes, it works like that. (I don't understand why this warning was stopping Lychee loading other elements ?)

**Comment by electerious** [comment]
Because Lychee expects a JSON response from the server, not a "Warning…". I will add the @ symbol in order to ignore the warning. BTW: Your hosting provider should update MySQL.

**Comment by calimou** [comment]
Thanks Tobias (you're right about MySQL update, of course).

**Comment by electerious** [comment]
Should be fixed now!
