### ISSUE TITLE
default umask and/or chmod issue

### ISSUE THREAD

**Issue by calimou** [electerious/Lychee#292]
Still when trying to install Lychee on this particularly well secured hosting provider... File are created by php with permission 600. An improvement to this would be to add some umask() and/or chmod() into Photo.php

**Comment by electerious** [comment]
What's the problem with the current permissions and how would you change them?

**Comment by calimou** [comment]
Hi !
Okay, my original post missed a point: I get files with mode 600 and they are **not** owned by the user running the webserver.
I admit It's one way of thinking hosting, on the other hand I think this is the role of the application to make sure of the permission for the file it produce ( whatever the desired permission is )

**Comment by electerious** [comment]
Hm sorry, but I'm still not sure what's your intention. Maybe you can do a PR to show what you mean or explain the problem further. I will close this issue for now as there are a lot of other features to implement.

**Comment by calimou** [comment]
Hi Tobias,
Look, the issue here is, in some hosting conditions, **the files produced by Lychee may be not readable by the PHP or the webserver** (which means those files could be either not accessible by visitors or by Lychee itself). I think that the permissions for those files should be adjusted by Lychee after they are created.

Even if it hasn't happened to anyone for now, this is a possibility which is not currently handled in Lychee. (and you are not alone, I remember having an equivalent discussion with Gallery 3 developers back in time... who have rejected the issue for wobbly unsound reasons)

I'm not going to open a PR for now. It's just a matter of either adding umask(0022); prior to create thumb/sized photos (and maybe a chmod($path, 0644); when files gets uploaded).
You would know better than me where to put this in a clean way.

In addition I don't really understand why issues you don't understand, or even being good ideas are closed. I think it should be marked as "incomplete" or "low priority" at some point. (I personally feel a bit obscured when it occurs, while I'm trying to put a contribution effort to the software).

Cheers.

**Comment by LudovicRousseau** [comment]
@calimou the user id used to execute the PHP code creating the files is NOT the user id used to run the PHP code to read the files? That would be a very strange configuration of the web server.

Maybe you could give more details about the configuration of your hosting service so @electerious can understand the problem and provide the correct solution.

Or maybe you can propose a patch that works for you.

**Comment by calimou** [comment]
Hi Ludovic, Tobias.

Okay. Let's forget what I said about PHP execution that wouldn't be able to read files he just wrote himself. It doesn't make sense. It was a mislead, sorry. 

The point is, PHP and the webserver does not run as the same user on this hosting service.

- PHP runs as the user that own the account (ie, myself, calimou). File created by PHP are by default owned by myself with mode 600.
- The Webserver run as its own dedicated user. So it cannot read files owned by myself with mode 600.

So, the problem relates to the webserver which is not able to read the files produced/managed by Lychee (through PHP).

- *destination file's permission after a move_uploaded_file() seems arbitrary*. I noticed moved files in big/ folder are set with 640 mode. I don't know why but it can happen to me or anyone else, or the behavior can even change tomorrow. Lychee could makes sure that files he moves to big/ folder is readable by anyone by setting the perm 'read' bit for "other", ie 644 so the webserver can read it. To solve this I suggest adding `if (file_exists($path)) chmod($path, 0644);` just after `move_uploaded_file` is called in Photo.php.

- Processed files are created with mode 640 too, owned by myself. `if (file_exists($path)) chmod($path, 0644);` in adjustFile() , createThumb(), createMedium() could help.

Hope it clarify the situation.

PS: inverting the idea, if Lychee was in need to use of some own temporary files, it would a good idea to set the mode to something that deny the webserver from access it.

**Comment by LudovicRousseau** [comment]
I understand now. Maybe the best solution is to add a call to ``umask(0022)`` at the beginning of the PHP scripts creating files.

I would not want to have this patch in the default Lychee code so it may be better if you manage that as a patch in your own version of Lychee.

Maybe you can configure the way PHP is started for you and configure umask() outside of Lychee?

**Comment by calimou** [comment]
Hi Ludovic,

It's not a problem if you don't want to have this patch in the default Lychee code, but could you please provide a reason ? I would understand if you answer my issue is a (very?) isolated one and it's not worth it. But overall I'm convinced it is the job of any software to handle correctly the permissions of files it produces (whether it is to secure or to open), not the one of the hosting service.As simple as that.
