### ISSUE TITLE
unable to create DB

### ISSUE THREAD

**Issue by Wav3** [electerious/Lychee#295]
At the installation-process Lychee can't create the test-db "lychee_dbcheck" on MySQL-System where the user only can create Databases with a predefined prefix.

So the option to solve this problem for me is, edit php/modules/Database.php and hard-change the databasename at line 88 and 90.

But this is not a very nice solution, so you can create a optional field named "prefix" in the installationform.

**Comment by electerious** [comment]
I think it would be better to check if it is possible to create the database name specified in the setup instead of "lychee_dbcheck". That would fix your problem as you can simply choose a prefixed name during the installation, right?

**Comment by electerious** [comment]
Does this fix your problem? https://github.com/electerious/Lychee/pull/296

**Comment by Wav3** [comment]
yes. this fix my problem.

thanks
