### ISSUE TITLE
Reset Admin User

### ISSUE THREAD

**Issue by DominikDary** [electerious/Lychee#298]
Hi,
I did an upgrade from Lychee 1.3 to 2.7 and in the beginning I was able to sign into the admin area.
After I have logged out, I'm not any longer able to sign in.

Deleting the data/config.php file opens up again the database config, but not the admin user configuation.
How can I reset the admin user ?

Thanks!

**Comment by electerious** [comment]
I guess it's not the best idea to upgrade from a version this old. If you have the option, start-over with a fresh Lychee v2.7 installation.

To reset the login:
Open the database table `lychee_settings` and remove the values (not the whole entry) of `username` and `password`.
