### ISSUE TITLE
Facebook metadata and thumbnail

### ISSUE THREAD

**Issue by toach** [electerious/Lychee#299]
Hi,
When sharing a single photo on facebook, I had no thumbnail on my FB wall.
After checking with https://developers.facebook.com/tools/debug/
i found that og:description and og:url where needed by FB.

Adding this http://pastebin.com/EQvf8Q5R in php/modules/misc.php solved the issue for me.

Lychee is a great app!

Thanks!

**Comment by electerious** [comment]
Thanks for the tip!

The following would be better for the description:
```php
$return .= '<meta property="og:description" content="'.$row->description.' - via Lychee">';
```

Your current `og:url` is a direct link to the photo and should be a link to the Lychee-page, according to their docs. I will take a look at it and add both to the `getGraphHeader()` function.

**Comment by electerious** [comment]
The `view.php` of Lychee v3.0 will include `og:description` and `og:url`.
