### ISSUE TITLE
Cannot access image properties

### ISSUE THREAD

**Issue by loup-brun** [electerious/Lychee#300]
I would like to access the image properties, such as the *title*, *description* (and possibly other properties, such as the date, tags, etc.). If I set a custom title via the GUI, the image title remains the file name (for example, if the file name is ```2014_01.jpg```, the title will be ```2014_01```).

Is it possible to get access to these properties?

**Comment by loup-brun** [comment]
**Update:** the title works (it's just a matter of emptying the cache).

However, is there a way of accessing the image properties - description, date?

**Comment by electerious** [comment]
There shouldn't be any caching when changing the photo title.

You can edit other properties using the info-box. Just press the "i"-Symbol on the top right when viewing a photo. Values like the date aren't editable at the moment.

**Comment by loup-brun** [comment]
I want to access the data from each photo using the Jekyll plugin. However, the data retrieved from Lychee does not contain the 'description' property. This is what I mean by _accessing_ the image properties.

[Enhancement] Furthermore, it would be awesome if each image could receive _additional_ properties created by the user.

**Comment by electerious** [comment]
The API of Lychee returns the description. I recommend to contact @tobru, the developer of the Jekyll plugin.

Custom information per photo would be a nice addition. It would be great if you could open a new issue for this feature request.

**Comment by loup-brun** [comment]
Managed it with the Jekyll plugin, thanks!
