### ISSUE TITLE
Fail to upload from dropbox

### ISSUE THREAD

**Issue by NarsilAnduril** [electerious/Lychee#302]
Hi,

(almost) Everything is in the title : I can browse dropbox from within Lychee, select an image, and hit ok, but then ... "Woops, it looks like something went wrong, please reload ..."

Some wrong php setting I suppose ?

Diego

**Comment by electerious** [comment]
Is there an error in the browser console?
 What does the diagnostics say (Settings>Diagnostics)?

**Comment by NarsilAnduril** [comment]
The browser console says :

POST http://www.xxxx.xxx/Lychee/php/api.php [HTTP/1.1 200 OK 479ms]
Object { description: null, params: "importUrl&url=https%3A//dl.dropboxusercontent.com/1/view/ov29jlr4vt3x110/Chargements%2520appareil%2520photo/2012-07-06%252008.25.24.jpg&albumID=0", response: false } main.js:4
lychee.error() main.js:4
upload.start.dropbox/</<.success/<() main.js:5
lychee.api/<.success() main.js:4
J.Callbacks/c() main.js:2
J.Callbacks/d.fireWith() main.js:2
n() main.js:3
.send/t/<() main.js:3

POST http://www.xxxx.xxx/Lychee/php/api.php [HTTP/1.1 200 OK 66ms]

And diagnostics :

Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  2.7.1
DB Version:      020700
System:          Linux
PHP Version:     5.3
MySQL Version:   50540
Imagick:         1
Imagick Active:  1
Imagick Version: 1620
GD Version:      bundled (2.1.0 compatible)

**Comment by electerious** [comment]
Hmm … Could you try to import an extremely small photo using Dropbox? Does this work?

**Comment by NarsilAnduril** [comment]
A 22kb file gives the same result

**Comment by electerious** [comment]
That's interesting. Are there any errors in the Lychee Log (Settings->Show Log)?

**Comment by NarsilAnduril** [comment]
The los says "2015-02-10 16:29:18 Europe/Zurich - notice - Settings::setDropboxKey (117) 	- Dropbox key is either too short or too long"

**Comment by NarsilAnduril** [comment]
Looking at my drop-ins permission in Dropbox, I have to set a Drop-ins domain. My Lychee install in a subdirectory (mean www.mysite.com/Lychee) but dropbox doesn't allow this. I only can enter www.mysite.com. Could this be the problem ?

**Comment by electerious** [comment]
Entering www.mysite.com is correct and should work. Not sure why it isn't for you. Are there any related errors in the PHP error log?

**Comment by electerious** [comment]
Have you found a solution?

**Comment by NarsilAnduril** [comment]
No, I didn't, and I don't have access to php logs (hosted server) so no
chance to investigate further I believe...

Diego Marin
email mobile

**Comment by electerious** [comment]
Can't help you without additional information, sorry. Try to contact the support. They are helpful (most of the time) and can send you the php log.

**Comment by NarsilAnduril** [comment]
Hi Tobias,

Sorry for the delay : I didn't spend much time on this issue but in fact,
it was quiet simple : allow_url_fopen was set to 0 in
php.ini, couldn't work fine like this.

Thx

Regards
Diego

Diego Marin
Rte de Morges 4
CH-1304 Cossonay-Ville
+41 76 822 11 56
+41 21 510 50 25

2015-02-24 21:18 GMT+01:00 Tobias Reich <notifications@github.com>:

**Comment by electerious** [comment]
I will look if I can add a check to the diagnostics if allow_url_fopen is 1. Thanks for letting me know!

**Comment by NarsilAnduril** [comment]
One more question : where can I find the version of Lychee I run ?

Diego Marin
email mobile

**Comment by electerious** [comment]
You can find it in the Login-Dialog.

**Comment by electerious** [comment]
An `allow_url_fopen`-check has been added to the diagnostics.
