### ISSUE TITLE
Lychee

### ISSUE THREAD

**Issue by Fshamri** [electerious/Lychee#303]
Hi,
will you please give me some information on how to use the Lychee api?

Thanks a lot

**Comment by tobru** [comment]
You can find an example here: https://gist.github.com/tobru/9171700

**Comment by Fshamri** [comment]
I am using postman extension for chrome browser... :)




Sent from Samsung tablet

-------- Original message --------

**Comment by electerious** [comment]
There's currently no public API documentation, so the only way to find out is to inspect the requests made by the Front-End. Let me know if you have specific questions.

A documentation is planned.

**Comment by Fshamri** [comment]
Will follow your suggestions.
Thanks
