### ISSUE TITLE
Cant login and set password 2.7.1

### ISSUE THREAD

**Issue by birdkiwi** [electerious/Lychee#304]
Fresh install. All worked fine. Until i decided to sign out and enter with login again.
When i login, page refresh and nothing happens. 
Ok, lets try delete password and login field in DB. Done.
Refresh page, ok, lychee showed me modal with username and password i can set.
When i set it, error message shows up: 

**Error: Function not found! Please check the spelling of the called function.**

My request was: 
**function=setLogin&username=123&password=caf1a3dfb505ffed0d024130f58c5cfa**

**Comment by electerious** [comment]
I guess that the new error is because you deleted the username- and password-field in the DB. Try readding these entries with an empty value. Lychee should then ask you for a new login.

Try if this fixes your problem. If not: Do you have the same problem in other browsers?

**Comment by birdkiwi** [comment]
electerious, please sorry.
it was hosting problems, all hdd space been used, so exceeding the quota made such strange problems!

anyway, thanks for your support

**Comment by electerious** [comment]
No problem. Hope everything works fine, again!

**Comment by pdrappo** [comment]
I had the same problem in my VPS, i fix the issue giving write permission to the folder where PHP save SESSIONS for the virtualhost that i created. May be this helps someone
