### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by DominikDary** [electerious/Lychee#307]
Hi, when I upload a new Image into an album I'm getting the error: 'Server returned an unknown response.'

The web console says:
```js
Object { description: "Upload failed. Server returned the status code 500!", params: XMLHttpRequest, response: "" } main.js:4
lychee.error() main.js:4
upload.start.local/o/a.onload()
```
When going to http://myserver.tld/plugins/display/log/, I see this entry:
```
- notice - Photo::add (164) 	- Skipped adjustment of photo 
```
The error message in the `error_log` of apache is:
```
[Sun Feb 22 16:05:00 2015] [warn] [client 1.3.4.6] mod_fcgid: stderr: PHP Fatal error:  Trying to clone an uncloneable object of class Imagick in /var/www/vhosts/myserver.tld/php/modules/Photo.php on line 265, referer: http://myserver.tld
```

It seems like an issue with my `imagemagick` installation, right? Do you may have any suggestions?

**Comment by electerious** [comment]
Thanks for the detailed report! :) I would try to deactivate ImageMagick in Lychee: https://github.com/electerious/Lychee/blob/master/docs/Settings.md#imagick

I think this should do the job. Try a newer version of ImageMagick if it works without it. Are there other projects on your server which use ImageMagick successful?

**Comment by electerious** [comment]
Any news?

**Comment by ophian** [comment]
Hi 
I got these "_Skipped adjustment of photo (imagename)_" notices with (v.3.0.0) Server import images having a rgb color profile set by camera (it was a Sony, I think). It seems a normal wheezy imagemagick installation will not work with such color profiles. They were imported but sometimes threw an error of being corrupted on view. I needed to convert and enhance them for web later on. But I did not have these other errors though. Maybe it will need a fallback or something?

BTW A fine system. Something I have been searching for to replace some older galleries. Well done!
Is there a roadmap and feature request list? While this is using quite new html5 features, do you have a bottom line of tested supporting browsers?

**Comment by electerious** [comment]
There's no public roadmap. Only the issues here on GitHub. You can find a list of supported browsers in the [FAQ](https://github.com/electerious/Lychee/blob/master/docs/FAQ.md#which-browsers-are-supported).

Do you know if this is a problem of ImageMagick or Lychee? Are there known solutions?

**Comment by ophian** [comment]
No sorry, I don't know.

**Comment by electerious** [comment]
Can't reproduce. Additional information required.

**Comment by napcae** [comment]
This is maybe related to #467
