### ISSUE TITLE
Commenting on photos

### ISSUE THREAD

**Issue by onitreb** [electerious/Lychee#308]
I was wondering if this is a feature you're considering.

I hadn't thought of it until I shared a Lychee album with a friend and he asked "Cool. How do I comment?"  :)

Few ideas:
Commenting on/off toggle per Album.

Public/comments on/off toggle

Commenting allowed if visitor has password to private Album. How do distinguish comments from multiple users with same password, though...

Show/hide comment stream.

3rd party comment system plugin? Disqus?

Thanks

**Comment by electerious** [comment]
Commenting would be a great feature. Disqus is nice, but I don't want to dependent on 3rd party sites. It would be very complex to handle accounts/users and spam correctly. Maybe it would make more sense to extend the API and allow front-end plugins in Lychee, which could then implement this feature using a service of choice.

**Comment by CryssDOTnet** [comment]
+1

**Comment by Bramas** [comment]
+1 for front-end plugins :)

**Comment by ejemba** [comment]
Hi do the front-ends plugins has been introduced ?

**Comment by cheristi** [comment]
+1

**Comment by mozzenior** [comment]
+1

**Comment by RoldanLT** [comment]
Even just a facebook comment will do :).

**Comment by wildfang** [comment]
Any news on this? Is it going to make it to a release?

**Comment by ramonakira** [comment]
This would indeed be a nice-to-have!

**Comment by TheRoboKitten** [comment]
I 50th this fr!! :)

**Comment by crazikPL** [comment]
@electerious is there any way to give you a motivation for this? any amount of BTC/LTC needed? :)

**Comment by barrowclift** [comment]
Bump, this would be a fantastic feature for sharing photos with friends and family without having to use closed-source alternatives like Google Photos or iCloud Photo Sharing.

**Comment by PeteJStewart** [comment]
I agree this would be great!  It wouldn't necessarily need to be that complicated or moderated.

I'd like to be able to share some images with friends and family on a private album.  In this case I'm not concerned about moderation and don't want people to log in.  The people who can access this album are the people I've given the password to.
All I'm after is a comment form with name and comment.
This could be a MVP for this feature and only usable on private albums to start.

This way, the feature is extremely simple and could then be enhanced as time goes on.
I'd be happy to help out with the code for this.

Obviously the ability to create plugins for the front end would also be great if that doesn't already exist.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
