### ISSUE TITLE
Better marksystem

### ISSUE THREAD

**Issue by janstieler** [electerious/Lychee#310]
Hi,
I'm looking since a time to an easy photomanagmenttool which is working like the pro softwares.
And with Lychee I found some which will have the abilities to be one :).
The thing is the possibility to mark photos in different ways. Actually you have only the possibility to set an star on or off. Because if you have to choose photos from an shooting you have to set a staged tagging for photos who are okay or not and between.
It could be realized through more stars, numbers and/or colors as example.

Greetings,
Jan

**Comment by electerious** [comment]
I'm always looking forward to improve Lychee for professional usage, so it would be great to know more about your workflow. Are you rating your photos or do you just want to mark them like: Keep/Consider/Remove? To go a bit off-topic: What's the first thing you do after uploading photos?

Feel free to write me a mail if you have some time! :)

**Comment by sillygilly** [comment]
I think it would be beneficial to click on the star when rating, a small drop down with 1 to 5 appears. This can simply be stored in the DB in the star field. Then visually you would just put a number in front of the star.

The view image page could then setup a key press handler for 1 to 5 that simply rates a picture without the need to do any mouse activity?

**Comment by sebastianseidel** [comment]
The idea of sillygilly sounds great... I would highly welcome such a feature!

**Comment by janstieler** [comment]
Hi,
sorry but what is "sillygilly"?

**Comment by sebastianseidel** [comment]
"sillygilly commented on Jul 18"

**Comment by janstieler** [comment]
Oh, okay I don't recognized that this is a nickname. I thought i missed some new slangword or something else :).

**Comment by HoffmannP** [comment]
I'm adding my 5¢ to this as a more general approach to this discussion:

Backend
---
There are some obvious information about an image that are already saved in the database. Like the file name, camera information etc.
But we all agree that we'd like to add more information, stuff like tags that describe or categorize the image, stars or points to comment on the quality, usability etc. We might want to use software like a [blurriness detector](http://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/) to rate the software or could use face detection to add names. One could add information about the location, the photographer, the camera, the date…

There are so many ways to store additional information about an image that we might agree that there is no way to satisfy everybody's needs. So there are two ways to go, we either
* build a system that is open so every user may add his/her category of information or 
* agree on one fixed set of information that is hard(er) to change/extend

I think it would be a very interesting feature to build a simple API that supports CRUD for a category of information. Like the star/not-star information or 0-star to 5-star information. Or anything else.

Frontend
---
And here is where the magic happens. The current UI is clean and simple. This is, what we love about lychee. Star or not star.

If one could add an UI like this with the ease of installing/activating a plugin. May bee change star to thumb up or down or a rating from one to five? Wouldn't that be great? Sure, not every lychee installation would look the same, but every installation would be adapted to the users need. And one that just want's to star or not could do that, and all the others that rather rate from one to [schfifty five](https://www.youtube.com/watch?v=-XccUMOQ978) could do that as well.

**Comment by lcorbasson** [comment]
I would suggest turning stars into tags with a namespace (e.g. stars:0 to stars:5) to make them adaptable to anyone's setup with a few lines of code. Appearance in the frontend can then be managed by plugins. This would of course benefit of #409.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
