### ISSUE TITLE
Image description visible in slideshow

### ISSUE THREAD

**Issue by sread** [electerious/Lychee#311]
I know you're in the middle of a big re-design, have you considered making the description more visible in the slideshow view? It would be nice for visitors to the albums who might not find (or bother with) the info pane.

**Comment by electerious** [comment]
What do you mean with slideshow? The view when an image is opened or when an photo is in fullscreen?

**Comment by sread** [comment]
When the image is opened, but before it goes fullscreen.

**Comment by electerious** [comment]
It's currently not planned to show the description outside the infobox. Maybe the planned API documentation will help to build a better slideshow site using photos from Lychee.
