### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by Enoch247** [electerious/Lychee#312]
I noticed that when I first installed Lychee and had not yet set php to except large file uploads, it would fail when uploading photos above the size limit without any indication of the failure. It would be nice if instead an error was shown along with and indication of which files failed out of the entire batch.

I took a peek at the php files for adding photos in the master branch. I'm more comfortable around microcontrollers and C, but I think I understand how the error reporting works. If you would like me to take a crack at fixing this, could you give me a hint as to how to detect when this error occurs?

**Comment by electerious** [comment]
Lychee will receive an fatal error when PHP runs out of memory. The best way to catch those is to register a global shutdown function with `register_shutdown_function(…)`. You can also set an error handler with `set_error_handler(…)` for errors in a script. This one won't fire in your case, but it would be a nice addition. Both handlers should be defined in `php/define.php` and should output a plain string like this: 'Error: Function failed to execute' (Strings starting with 'Error:' will be recognized as an error). Additional information should be saved to the log (`Log::error()`), but I'm not sure if the database is available in this case.

I added this enhancement my roadmap!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
