### ISSUE TITLE
Lychee's website needs a valid SSL

### ISSUE THREAD

**Issue by isntall** [electerious/Lychee#317]
As Lychee has become more popular, more people will you use it. 
Lychee will need a valid SSL cert, especially if the users use SSL on the sites they host; newer browsers give an alert saying that there is non-https content on the page, due to the call home Lychee has built in.

I think that the site needs a wildcard cert at *.electerious.com would be appropriate. I've seen them for $95USD, or possibly getting one from the new Firefox initiative that is trying to give valid certs to everyone (i can't remember the name at the moment). I think that the Lychee community should pitch and help buy this.

Thoughts?

**Comment by darix** [comment]
www.startssl.com is even for free. ;)

**Comment by electerious** [comment]
I agree that we should prevent a warning, but a SSL certificate just for a version check…? I'm currently returning the number of the newest version. Could there be a better way? I guess that it's not possible to use GitHub to serve the version because of the same-origin policy?

**Comment by bjoerns1983** [comment]
StartSSL is a trusted Isreal based CA, there is no problem with that.
But you also get a Comodo Positive SSL cert for 8,30€/year at namecheap, which i use for my Owncloud etc. 
Nevertheless i dont bother about these alerts.

**Comment by LudovicRousseau** [comment]
You can also use a certificate from CAcert https://www.cacert.org/
It is free and easy to use.
But most browsers do not include the CAcert root certificate.

**Comment by bjoerns1983** [comment]
CACert is a nice project, but it wont solve the problem, because no Browser or OS ships there root Cert by default.
Thats why i bought an cert for my owncloud, installing their root cert to all my devices (incl. iPhones etc.) was a too big hassle.

**Comment by w00kie** [comment]
You can also wait until letsencrypt.com goes live, but today startssl is probably the best solution to get a good free SSL certificate.

**Comment by Enoch247** [comment]
I also used startssl.com to get a free ssl cert for my site (https://mechbits.com). They give away what they call "class 1" certs for free and market their "class 2" product to people interested in building online retail grade sites. I host an owncloud instance and did not want to have to tell people to ignore the big scary browser warning about self signed certs everytime I shared a file with them.

I see electerious.com is hosted by apache2/ubuntu (same as my server) I'd be willing to explain the steps I went through to get my signed cert and share my config files as examples. I managed to set it all up and a few hours while typing one handed, watching TV and holding my son in the other arm. I'm sure with less distractions it is even easier!

**Comment by electerious** [comment]
I'm keeping an eye on https://letsencrypt.org. Public beta starts soon.

**Comment by LudovicRousseau** [comment]
You can also get a free (and valid for 3 years) TLS certificate from https://buy.wosign.com/free/

**Comment by lcorbasson** [comment]
@electerious The public beta for Let's Encrypt just started, and if you're using Apache it's only a matter of minutes :-)

**Comment by electerious** [comment]
Soon https://github.com/electerious/Lychee/commit/d516409afc3908890661e25feb82c7b74805ab90

**Comment by bb-Ricardo** [comment]
Hi, you should probably add more domain names then just these:
![domains](https://cloud.githubusercontent.com/assets/771836/11918053/da6ec2ee-a721-11e5-9e5c-871ab10713fe.png)
i.e.:
* lychee.electerious.com
* electerious.com
* www.electerious.com

and it would be great to default to https.

jm2c
