### ISSUE TITLE
request: support multibyte folder name

### ISSUE THREAD

**Issue by am01125** [electerious/Lychee#319]
Hi,

I use lychee v3.0.0.
In this version (and 2.7), multibyte file name is allowed but multibyte folder name is rejected.
Please improve it to be usable.

Thanks!

**Comment by am01125** [comment]
sorry, it needs more description.
when i use 'Import from Server', photo files are not imported if directory paths contain multibyte strings.

**Comment by electerious** [comment]
Thanks for the report. The Import takes place in [this file](https://github.com/electerious/Lychee/blob/master/php/modules/Import.php). Could you open a PR if you find a solution?

**Comment by am01125** [comment]
I have no idea.
I am not really an expert, but I tried mb_convert_encoding().

# Get all files
$encoding = mb_detect_encoding($path, 'auto');
$files = mb_convert_encoding($path, 'UTF-8', $encoding);

mb_convert_encoding() seems to return null.
I hope someone solve this request.

**Comment by LudovicRousseau** [comment]
@am01125 maybe you could give more details:
- what is the operating system used by the server?
- what is the directory name that cause problem?
- what encoding is used on the server for the directory name?

**Comment by am01125** [comment]
Hi LudovicRousseau,

I don't know what information is necessary.
If you need more, plese ask me.

> operating system

FreeBSD 10.1-RELEASE-p8
Apache 2.4.12
MariaDB 5.5.41
PHP 5.4.39, php -m is below:
Core
curl
date
ereg
exif
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
mysql
mysqli
mysqlnd
OAuth
openssl
pcre
PDO
pdo_mysql
Reflection
session
SimpleXML
SPL
standard
zip
zlib

> directory name that cause problem

All Japanese 2-byte chars seem to cause.
Concretely, I tested "日本語". (means "Japanese")

> encoding

I use UTF-8.

***
By the way, I wrote blow testcode before edit 'Import.php', and it works.


      <?php
      // target dir
      $read_dir = "/mnt/streaming/lychee/uploads/import/";

      // open dir
      $dir = dir($read_dir);

      // path
      $path = $dir->path."/";

      // init
      $row = 0;
      $file = array();    // file name
      $type = array();    // file type

      while (($temp = $dir->read()) !== false) {
          // exclude "." and ".."
          if ($temp != "." && $temp != "..") {
              $file[$row] = mb_convert_encoding($temp, "auto");
              switch (filetype($path.$temp)) {
                  case "dir":
                      $type[$row] = "directory";
                      break;
                  case "file":
                      $type[$row] = "file";
                      break;
                  default:
                      $type[$row] = "unknown";
                      break;
              }
              $row++;
          }
      }

      // close dir
      $dir->close();

      // output
      for ($i = 0; $i < $row; $i++) {
          echo 'file name ： '.$file[$i].' ( '.$type[$i]." ) \n";
      }

      ?>


-- terminal --

      > php testcode.php
      file name ： 日本語 ( directory )
      file name ： testcode.php ( file )


too much for me :-p

**Comment by electerious** [comment]
Not sure what's necessary to fix your problem. I'm open for a PR and additional details, but will close the issue for now.
