### ISSUE TITLE
v3 - IE no svg

### ISSUE THREAD

**Issue by ophian** [electerious/Lychee#320]
`<use>` with an external source does not work in IE 9, 10, 11. 
https://css-tricks.com/svg-use-external-source/

There might be a solution with https://github.com/jonathantneal/svg4everybody, see https://css-tricks.com/examples/svg-for-everybody/, but I did not get it to work yet.

Any ideas?

**Comment by electerious** [comment]
The SVGs will be injected into the `index.html` using [gulp-inject](https://www.npmjs.com/package/gulp-inject). I'm working on it. Thanks for the reminder :)

**Comment by electerious** [comment]
The icons are now working in IE. Tested with version 10 and 11.

**Comment by ophian** [comment]
:+1:
