### ISSUE TITLE
v3 request - a config option to disable full Photo

### ISSUE THREAD

**Issue by ophian** [electerious/Lychee#322]
analog to "Download Photo" option.

**Comment by ophian** [comment]
I just note here that this is not about disabling image access to users. I think it is a valid request for the owner to only allow js layered screens. (For the moment I just disable it by the contextMenu.photoMore splice thing, set to `splice(0, 2)`)

**Comment by electerious** [comment]
This feature has been requested multiple times now. See https://github.com/electerious/Lychee/issues/243 and https://github.com/electerious/Lychee/issues/231. However, I'm still think that this is a user friendly feature and shouldn't be disabled. Photos may be displayed in a small size depending on the screen. Users should be able to see the full photo in this case.

**Comment by ophian** [comment]
I am with you, that from a user perspective the open form is best. My perspective was from the owners and design view, since as far as I remember, the full photo was just viewed by direct link using the browser. I fell over it, since I had images which were not as big as the actual browser screen. Then the full image was shown placed left-upper on a white background. And that looked bad. Therefore I needed a disable option. And it would be so easy to do, see my not very ambitious patch..
I am sorry I did not see these other request issues.
