### ISSUE TITLE
Special characters not correctly exported when downloading zip archive

### ISSUE THREAD

**Issue by VictorLamoine** [electerious/Lychee#327]
- Create an album with a special character in it; eg: `Pâques`
- Put somes photos in it and allow download
- Download the archive
- The folder name inside the zip archive is `PÃ¢ques`

Another example: `Noël` will become `NoÃ«l`
Tested on Ubuntu 14.04, Firefox 37.0.1, Chromium 41.0.2
Lychee 2.7.2

May be related to #176

**Comment by electerious** [comment]
Tested it on OS X 10.10.3 with Lychee v3.0 and it worked fine. Encoding is always weird. I'm not sure if something changed with Lychee v3, but I don't think so. I guess it has something to do with default encoding of the OS. Hard to test without being able to reproduce it.

Would be great if you or someone else could take a deeper look at it!

**Comment by electerious** [comment]
I think that you need to supply a different filename encoding when unzipping the download. Works fine with UTF-8.

![the unarchiver](https://cloud.githubusercontent.com/assets/499088/7338578/3f215446-ec50-11e4-9fb9-6fa419aaa67a.png)

**Comment by VictorLamoine** [comment]
Indeed, the problem is not from Lychee but from Ubuntu `file-roller`; it works fine with `unzip`

```bash
$ unzip Pâques\ 2015.zip 
Archive:  Pâques 2015.zip
  inflating: Pâques 2015/DSC05551.jpg  
  inflating: Pâques 2015/DSC05601.jpg  
  inflating: Pâques 2015/DSC05576.jpg  
```
