### ISSUE TITLE
Obfuscate shared albums URL

### ISSUE THREAD

**Issue by BenoitDuffez** [electerious/Lychee#330]
This is about albums that are:

* not visible
* downloadable
* shared
* no password

Currently, the URL is easily guessable: it ends with the album ID. So once you are given the URL to one album, you can try to get other albums just by changing the URL. This may not be the desired behavior.

Could it be possible that albums that match the criterion described above, the URL would be obfuscated with some kind of hash? I used to use this feature on Picasa Web Albums, where the albums were available without password, but the URL was impossible to guess (something like `/AlbumName?authKey=<hash>`).

I tried to protect the album with a password, and pass `password` to the URL in various ways, it didn't work.

**Comment by electerious** [comment]
The “not visible” feature is for people who want to share an album, but don’t want to present it on their Lychee page. What you want is this: https://github.com/electerious/Lychee/issues/27
