### ISSUE TITLE
Cannot upload photos with vertical orientation

### ISSUE THREAD

**Issue by bozakov** [electerious/Lychee#334]
The upload of photos with vertical orientation fails:
> "Server responded with an unknown response. Please take a look at the console..."

The chrome console says:
> "server responded with a status of 500"

Strangely horizontal (landscape) photos are imported without any issues.
Is there anyway to verify if this is a problem with Lychee or with my provider?

Thanks for the great work!

**Comment by electerious** [comment]
I recommend to take a look at the Lychee Log (Settings > Show Log) or at the PHP Error Log. If you want, you can attach the photos so I can try to verify the issue.

**Comment by bozakov** [comment]
Thanks for the prompt reply! The log contains several entries of the form:
>  - notice - Photo::add (170) 	- Skipped adjustment of photo (IMG_XXXX)

The image file names correspond to the photos which were successfully uploaded.
Here is an example photo which fails:

![img_0130](https://cloud.githubusercontent.com/assets/546058/7401578/9bd24ac0-eec5-11e4-9c7d-20f7588a80ba.JPG)

**Comment by electerious** [comment]
Could you please post the output of the diagnostics (Settings > Diagnostics)? The image works fine on my installation. I guess that PHP runs out of memory and stops with a fatal error.

**Comment by bozakov** [comment]
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Lychee uses the GBK charset to avoid sql injections on your MySQL version. Please update to MySQL 5.5 or higher to enable UTF-8 support.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  2.7.2
DB Version:      020700
System:          Linux
PHP Version:     5.6
MySQL Version:   50173
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment]
Your installation uses the GD library to convert/rotate the photo on upload. This one takes a lot of memory and the PHP script crashes. I'm sure that this is the case here. Sadly, there's no way to fix or catch the error. You can try to scale the image down before uploading it and it should work fine.

**Comment by bozakov** [comment]
Ok, thats good to know - thanks! Could you tell me which imagemagick tool is used for the rotation, or how Lychee checks for imagemagick? I was under the impression that it should be installed on my hoster's server (at least I can execute 'convert' and 'mogrify' when I'm logged in)

**Comment by electerious** [comment]
Lychee checks if the ImageMagick PHP extension is available. You can use `phpinfo()` to check if the extension is installed.

**Comment by bozakov** [comment]
Awesome! the extension was missing - AND my hosting service allows me to install it! Everything is working now. Great job on pinpointing the problem!

Thanks for your help and your software!
