### ISSUE TITLE
Share option not shown

### ISSUE THREAD

**Issue by polypmer** [electerious/Lychee#336]
The "share" option, top right corner of an album's page, doesn't display. I can click where it ought to be (before the download button) and it works, but it isn't visible.

**Comment by electerious** [comment]
Please let me know your OS, Browser (+ version) and the version of Lychee. A screenshot (or screencast) would be a great help.

**Comment by polypmer** [comment]
sure: I'm using Ubuntu Gnome 15, firefox 37, Lychee 2.7.2 and a screen shot:
![screenshot from 2015-04-30 14 16 52](https://cloud.githubusercontent.com/assets/10081511/7423665/7995ea16-ef65-11e4-9833-021601c765d1.png)

**Comment by polypmer** [comment]
the share button (I see that it's yellow) does work using conkeror (mozilla) on arch. Also, it was working, until recently on my Ubuntu machine (maybe updating did something funny?).

**Comment by electerious** [comment]
Are you using a Firefox extension which could block the share icon? I never heard about this problem before. You could also try the Lychee v3.0 branch and check if it is working with the new version.

**Comment by polypmer** [comment]
I'm using uBlock, but on my other devices uBlock doesn't block the button. Also, in other browsers on this computer (the computer in question) the button *does* show up. 

I see that the class icon-share has this attribute in the in-line css: display: none !important;
Everything works like gravy when I cross this out (i'll attach some screenshots), but again this is only happening on this browser/os. 

![screenshot from 2015-05-04 22 42 53](https://cloud.githubusercontent.com/assets/10081511/7466348/0835b5a2-f2af-11e4-9315-98ecb35fa821.png)
![screenshot from 2015-05-04 22 36 24](https://cloud.githubusercontent.com/assets/10081511/7466349/0dd1e1c0-f2af-11e4-8030-c5ddb64c5538.png)
![screenshot from 2015-05-04 22 36 22](https://cloud.githubusercontent.com/assets/10081511/7466350/13649fce-f2af-11e4-91c8-1a6ccc4baafa.png)

Seeing as how this otherwise works (on my other devices and browsers + I can click on the invisible button if I find it really necessary) I'll close this issue.
