### ISSUE TITLE
Make photo downloadable

### ISSUE THREAD

**Issue by pogShawn** [electerious/Lychee#337]
I couldn't find this in docs or issues. The make album/photos option downloadable option "No" is defeated simply by opening image in a new tab. I'm not a linux_er: am I simply missing a permission on my photos files or is this an issue?

btw, I'm an experienced technical  writer, if there is anyway I can help with user docs (part-time), I will, just direct me.

Thanks for your service,
Shawn

**Comment by electerious** [comment]
Hi Shawn, the option Downloadable "No" just disables the download button. You can still open photos in a new tab and manually download them. More about this: https://github.com/electerious/Lychee/issues/322

I'm not exactly sure, but I think this answers your question :)

**Comment by pogShawn** [comment]
Boy that was prompt, Tobias,
     I understand. Thanks.
Shawn

**Comment by electerious** [comment]
I will close this issue. Further comments can be added to #322. Thanks for offering your help! I will let you know if there's anything to do.
