### ISSUE TITLE
Feature: sub albums

### ISSUE THREAD

**Issue by CryssDOTnet** [electerious/Lychee#338]
Hi!

Would it be hard to implement sub albums?
I have several albums as "portolio" and one album for a group with general pictures. Now I want for individuals in this group a sub album without cluttering the index view and possibly infringe one's privacy.

Thank you!

PS: Your software is by far the clearest, cleanest and FASTEST I have tested so far. Keep up the good work!

**Comment by electerious** [comment]
Hi, there's already an issue for sub-albums (collections). I guess that's what you want: https://github.com/electerious/Lychee/issues/254
