### ISSUE TITLE
Advanced content selection

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#339]
Select albums/photos using shift/comand-selection

**Comment by nicegonice** [comment]
I want to select  inconsecutive photos,use shift didn't work.
My system is windows7

**Comment by qligier** [comment]
Use the control key.

**Comment by nicegonice** [comment]
I'm sorry,I press Ctrl and click photos,it just can't select  inconsecutive photos.

**Comment by qligier** [comment]
On Windows the key to select non consecutive files is the control key. This isn't an issue with Lychee, as it can't be changed: the upload windows is always the same.

**Comment by electerious** [comment]
@qligier I guess @nicegonice doesn't mean the upload.

Selecting photos individual photos/albums isn't implemented, yet. You can only select consecutive ones.

**Comment by qligier** [comment]
Right, my bad :sweat_smile:. Sorry for that.

**Comment by nicegonice** [comment]
@qligier  @electerious  Thank you so much!  
 :sweat_smile:
Selecting individual photos/albums is planned?

**Comment by electerious** [comment]
Yes, that's the issue you are commenting on.

**Comment by electerious** [comment]
@hrniels implemented an advanced content selection. It's now possible (`feature/subalbums` branch + you need to rebuild the source) to select multiple photos/albums by holding the meta-key (cmd on macOS and ctrl on Windows).

**Comment by electerious** [comment]
Open bugs:

- [x] It's possible to select smart albums with click+move
- [ ] It's possible to select albums and photos at the same time with click+move and shift

**Comment by electerious** [comment]
We're done here. This feature should be part of the next minor version (properly v3.2). Big thanks to @hrniels for implementing it!
