### ISSUE TITLE
Access Denied to Database

### ISSUE THREAD

**Issue by DonPete** [electerious/Lychee#342]
I have attempted to setup Lychee on a Debian 8 machine with Nginx.

Upon loading the web interface I entered a simple username and password into the required fields, and click connect.  Then I am greeted with this screen http://i.snag.gy/TQKhF.jpg

I have all the required PHP modules loaded, and MYSQL installed on the machine.

**Comment by electerious** [comment]
What does the diagnostics say (Settings>Diagnostics)?

**Comment by DonPete** [comment]
Sorry, I thought I included that.

It says:
Error 001: Configuration not found. Please install Lychee first.

**Comment by electerious** [comment]
Please try again with the newest version of Lychee (v3) and send me the new diagnostics (including the system information).

**Comment by electerious** [comment]
Can't reproduce.
