### ISSUE TITLE
[security] session or cookie foo with multiple instances of lychee

### ISSUE THREAD

**Issue by zettihh** [electerious/Lychee#344]
Hi Tobias,

as there is no multi-user support yet, I've installed **multiple instances** of lychee on my vps.
Due to lack of a wildcard ssl cert, I use aliases/folders for accessing the instances.

`/var/www/lychee1` -> `https://mydomain.com/photos1`
`/var/www/lychee2` -> `https://mydomain.com/photos2`

Of course with two databases, totally seperated folders, different logins/crendetials and so on ...

##### When I login to photos1 this login is also valid for photos2. I don't have to re-login, this sounds to me like a security vulnerability.

I am not really familar with php session handling and cookies, but here my thoughts about it.

- Cookie is always valid for `domain = mydomain.com` and `path = /`.
- As long the cookie is valid for `/`, this happens on accessing by folders not by subdomains.
- I think this can be solved by an additional `path` or `url` value to `lychee_settings table` from which the cookie path can be set.
- Of course this will not prevent someone from editing the cookie, but I am sure, you will find a secure solution :) 

Maybe you can have a look into it.

Thanks
Carlo

**Comment by electerious** [comment]
Thanks for the information! We need to store an unique key in the session to identify the Lychee installation. The id could be generated after the initial setup.

**Comment by electerious** [comment]
Lychee now stores an identifier in the database and session. Loggin into A keeps you logged out in B. However, both installations are still using the same session: Logging into a different installation (e.g. B) will log you out of A. Thats much better, but there's still save for improvement.

Please take a look at the develop-branch and let me know if it is working for you.

**Comment by zettihh** [comment]
thanks, works fine :)
