### ISSUE TITLE
Integration with ownCloud

### ISSUE THREAD

**Issue by hitam4450** [electerious/Lychee#346]
Hi, 

For file management I use OwnCloud (current version 8.03) including my photos. However, since I like lychee very much, I would like to ask, if there will be a special app for OC to connect / integrate lychee with OwnCloud!

Thanks & regards, hitam4450

**Comment by electerious** [comment]
Hi, there's no way to integrate both systems, but you can sync Lychee with any directory containing photos using this plugin: https://github.com/GustavePate/lycheesync

Hope that helps :)

**Comment by hitam4450** [comment]
Thanks for yore reply and comment!
