### ISSUE TITLE
syntax error, unexpected '[' in php/modules/Album.php on line 691

### ISSUE THREAD

**Issue by alexmbird** [electerious/Lychee#348]
I've just upgraded from 2.7.1 to 3.0.0.

On my first visit to the gallery I was prompted to set a new password.  So far so good.

All further hits result in a PHP error:

```
PHP Parse error:  syntax error, unexpected '[' in /path/to/Lychee/php/modules/Album.php on line 691
```

I've checked and the code at 691 is brand new, introduced with commit e67eca81ae1492aaf11d2f22532aa5ff9ff24d49.  

Can it please be fixed?  My gallery is completely b0rked and I don't expect rolling back to 2.7.1 will help as it uses the old password format.

Background information:
* PHP 5.3.10
* Code installed from a `git clone` as per the installation instructions
* Running under php-fpm, Nginx frontend

**Comment by electerious** [comment]
Thanks for the detailed report! I will take a look at it. Try to comment the line and avoid the merge-function for the moment.

@rhurling Do you know why this error occurs without executing the merge-function?

```php
$albumID = array_splice($albumIDs, 0, 1)[0];
```

**Comment by rhurling** [comment]
I would say the error occurs, because it's a Syntax Error which happens on parsing the file.
It uses array dereferencing (see http://docs.php.net/manual/en/migration54.new-features.php), which was introduced in 5.4.

**Comment by rhurling** [comment]
This should fix it:
```php
$albumID = array_splice($albumIDs, 0, 1);
$albumID = $albumID[0];
```

**Comment by alexmbird** [comment]
@electerious - thanks, with that workaround in place everything is fine.

**Comment by electerious** [comment]
@alexmbird Could you please try the newest version? Let me know if it's fixed.

**Comment by alexmbird** [comment]
Just checked and it's fixed now.  Thanks!
