### ISSUE TITLE
Problem download album with ampersand in password

### ISSUE THREAD

**Issue by Varlorg** [electerious/Lychee#356]
Hi,
I'm using Lychee 3.0.1, I have create a album protected by a password containing an & 
when I try to download the album , all the metadata are in the URL so I've got something like 
websitephp/api.php?function=Album::getArchive&albumID=1&password=passwordbeginning&endofpassword
so I got Warning: Wrong password! because it think the password is only  passwordbeginning  whereas it is "passwordbeginning&endofpassword"

If I replace it by %26 I got an timeout but this is maybe beacause it's on a raspberry pi

**Comment by electerious** [comment]
You're right. Thanks for letting me know! I will take a look at it.

**Comment by Varlorg** [comment]
I got some time to check the code and find a fix.
The password value must be escaped before been send using escape function 
Here a patch: https://gist.github.com/Varlorg/2357b0d94008e3965bbf

**Comment by electerious** [comment]
@Varlorg Thanks for the suggestion. I will give it a try!

**Comment by electerious** [comment]
Fixed on `develop`. Thanks for the report and help.
