### ISSUE TITLE
Internal Server Error at "Download Album"

### ISSUE THREAD

**Issue by matheburg** [electerious/Lychee#357]
Hello, I am facing a problem at my first steps with Lychee. I have copied Lychee to my Strato Webspace and created a MySQL database for it. Everythings seems to work out fine, but the Album Download. Whenever I try to download a whole album (in both cases: private and public) the server responds with an "Internal Server Error" ("The server encountered an internal error or misconfiguration and was unable to complete your request.").

Performing the check/index.php it also returns an error:

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Error: Wrong property for sorting in database

System Information
------------------
Lychee Version:  3.0.1
DB Version:      030001
System:          SunOS
PHP Version:     5.3
MySQL Version:   50543
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         

Do you have any suggestions? Thanks a lot!

**Comment by matheburg** [comment]
Ok - I have just found out that it has something to do with the number of pictures (maybe as well with the size) I want to download. The border seems to be between 19 and 20 pictures of ~3MB.

**Comment by matheburg** [comment]
Now I have taken a look at phpinfo and replaced all configuration (within php.ini) which could have been the restricting reason, but this didn't work. Although I am not even sure whether php+fastcgi have anything cashed and thus not properly updated according to this new settings. I don't see any way out of this misery :(

**Comment by matheburg** [comment]
Just another hint: It is not caused by the number but by the size of images. I could download an album of 100 mini images without problems. From my observation the maximal zip file size COULD BE 64MB. But it is also possible that the memory limit for the zip creation is exceeded. As I told you, I could not change this behaviour by reconfigurations within the php.ini.

**Comment by isntall** [comment]
To get some basics
- What web server are you using?
-What type of php? (fpm, mod_php, etc)

I've had issues in the past with Nginx and PHP fpm, needing settings changed to allow larger files.

**Comment by matheburg** [comment]
Here you can find the php setting: http://www.mswedding.de/info.php; does this help?

**Comment by electerious** [comment]
I can't provide help for individual server configuration problems, but I'm sure that PHP is running out of memory. Try to take a look at the PHP error log.

**Comment by matheburg** [comment]
thanks for your help: I am now sure that this issue occurs due to memory limitations of my webspace provider. For strato it currently is: 128MB for PHP memory, and 30MB maximum file download at PHP; what a pity...
