### ISSUE TITLE
Can't upload photo on xampp Windows XP

### ISSUE THREAD

**Issue by tomipnh** [electerious/Lychee#358]
I am using xampp on Windows (version 1.8.0 which is working still on Windows XP Pro). 
After setup new database I have installed Lychee without any errors. However when i login and tried upload photo (jpg) I am only getting error "Photo type not supported! Please take a look at the console of your browser for futher details."

Error in console: error - Photo::add (98) 	- Photo type not supported

Inside apache logs I didn't found anything useful.

Is there any requirements which  xampp doesn't meet?

**Comment by electerious** [comment]
What does the diagnostics say (Settings>Diagnostics)?

**Comment by electerious** [comment]
Can't reproduce.
