### ISSUE TITLE
Unable to import images from networked drive, not even with symlinks

### ISSUE THREAD

**Issue by MarceFX** [electerious/Lychee#360]
Hi,

I just installed Lychee on a Windows 7 virtual machine at the office. I'm using WAMP to run Apache and MySQL. Lychee seems to work well with local files, but not with networked folders. I tried using symlinks, but no luck either. Any ideas? 

Thanks

**Comment by electerious** [comment]
I never tried this, but I think that symlinks shouldn't be a problem. Have you checked if the file permissions are correct (= PHP-user can work with the linked files)?

**Comment by MarceFX** [comment]
Thank and sorry for being such a pain in the ass... That was it :-)
