### ISSUE TITLE
Add fullscreen button

### ISSUE THREAD

**Issue by k4r7u** [electerious/Lychee#362]
If the mouse is moved out of the browser tab, the picture is shown without the menu. This is by the way a pretty cool feature. Unfortunately, if I put my browser in fullscreen, I am of course not able to move the mouse out of the browser. It would be great if this fullscreen feature could also be triggered by a button.

**Comment by Unresponsive** [comment]
Came here to write about exactly the same problem. :) Another approach would be to enter fullscreen mode if the cursor hasn't been moved for some time.

**Comment by electerious** [comment]
Going fullscreen when the user hasn't moved the mouse of some time is how we should do it. It's intuitive  and eliminates the need for another button.

**Comment by suiluj** [comment]
Yes! Yes! Yes! Could someone please include this function in some of the next updates!

**Comment by electerious** [comment]
Implemented by @hrniels https://github.com/electerious/Lychee/pull/583
