### ISSUE TITLE
Photo duplicats & Wrong property for sorting in database

### ISSUE THREAD

**Issue by milosjovac** [electerious/Lychee#364]
Hi all, thanks for the great lib! 

I installed Lychee and followed all instructions. All required extensions are added, and .ini file is changed to follow your recommendations. Anyhow odd behavior is noticed during a month long use:

- Sometimes same photo get uploaded multiple times. Once this happens, same photo(or sometimes photos) will be uploaded with next few bulk uploads. I noticed once that problematic photos that got duplicated were saved in "data" folder. After cleaning it everything worked as a charm. Last time duplication has been happened, this folder didn't contain any photos. Any idea what can be wrong? 

- Also Settings->Diagnostics shows the warning: Wrong property for sorting in database. 

Full Diagnostics:
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: Wrong property for sorting in database

System Information
------------------
Lychee Version:  3.0.1
DB Version:      030001
System:          Linux
PHP Version:     5.6
MySQL Version:   50542
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment]
Is this issue still present? I'm not sure what's casing it.

**Comment by electerious** [comment]
Can't reproduce. More information needed.
