### ISSUE TITLE
Improving navigation between images

### ISSUE THREAD

**Issue by Unresponsive** [electerious/Lychee#365]
First of all thanks for Lychee, it's one of the most modern and beautiful looking image albums!

I do think navigation between images could be improved. My less experienced users are often baffled how do you get to the next image. Some try clicking on the photo but nothing happens. Often they end up clicking on (< Close image / back to album), and then click on the next image in album. Obviously that is very inconvenient. The reason for the confusion is that there are no visual clues for navigation, unless you position the cursor very close to the left and right edge, only then tiny arrows appear.

The simplest improvement would be to add behavior when clicking on the image brings you to the next one. Or make the hover areas which show navigation arrows much wider, like 33% or even 40% on each side (and clickable in that area). (And the arrows could be bigger, too!) (BTW, visual clues on the sides are sending the wrong message — that you can't click anywhere in the hover area to advance to the next photo. Two reasons — 1) pointer/hand cursor does not show; 2) when you hover on the arrow, it becomes brighter, so the user thinks you HAVE to click precisely on it to navigate. I think lightening it up on precise hover impedes navigation and is counterintuitive, because you actually don't get different behavior clicking on the arrow or outside of it, however the animation suggests you will.)

Now on to mobile. Navigation between images is impossible on older browsers (Safari on iOS 6). So tapping on an image to advance would help greatly in this case as well (tap on the left side to go back an image). Swiping sort of works on the current iOS 8 Safari, but is inelegant, as you have to wait for a couple of second to get visual confirmation it worked (it takes some time for the image to disappear and the next one to show). Preloading the next image (I know this is already discussed in an another thread) and animating the image in the direction of the swipe would really improve user interface/experience IMHO.

**Comment by electerious** [comment]
Short answer: You're right and I'm looking forward to improve the navigation. Something similar to the one in iOS is planned. I couldn't find an iOS screenshot showing this element, but I'm thinking of something like this: http://1.f.ix.de/scale/geometry/600/q75/imgs/18/1/4/5/3/2/3/5/screen800x500-7fd6ce3e5e5b7654.jpeg (the photo-navigation on the bottom).

**Comment by allienworks** [comment]
+1 for "click for next image" feature. It's fine on desktop now, but I can't navigate to the next image on my BlackBerry 10 otherwise then going back and selecting another one.

**Comment by amanpatel** [comment]
+1 Its not a big priority for me right now, but I would probably contribute to get this done.

**Comment by integer** [comment]
Any update for this issue? May I help in any way?

Lychee is beautiful piece of software, but without mobile friendly navigation between images it is no so usefull as it could be.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
