### ISSUE TITLE
My workflow: Duplicates

### ISSUE THREAD

**Issue by hzulla** [electerious/Lychee#367]
Hi,

here's our workflow at home: My wife and I each own a smartphone. We also have several cameras that we both use. We don't edit these photos much, just need a smart way to store and backup them all in one place.

On a regular basis, we used to copy the cameras' storage media's contents to a laptop that runs `f-spot`, a Linux photo management program. We don't remove photos on the storage cards right away, since `f-spot` doesn't import duplicates to its collection and auto-groups the collection based on the exif shot date. But `f-spot` appears to be abandoned software (or at least it's fairly difficult to have it built for current Ubuntu).

Lychee looks nice, but it doesn't handle duplicates properly for us to work.

Reading #48, it appears that you consider duplicates in the collection either a deliberate choice or a user's mistake. That's not true in our case. We just expect the software to handle duplicates by not importing them.

However, would you a accept a patch to Lychee that will check for duplicates during upload and removes them automatically?

**Comment by electerious** [comment]
How about building a tiny script that checks the database for duplicates and removed them? Should be easy to do by using the `checksum` and `id` (= upload time) values. What do you think?

Another idea would be a new setting in the database. Something like `skipDuplicates`.

**Comment by electerious** [comment]
In work :)
![lychee - tbla](https://cloud.githubusercontent.com/assets/499088/8393426/b9c8e012-1d0e-11e5-94da-f5ba05264979.png)

**Comment by electerious** [comment]
Lychee 3.0.3 includes the ability to skip duplicates on upload: https://github.com/electerious/Lychee/blob/master/docs/Settings.md#skip-duplicates-on-upload

**Comment by hzulla** [comment]
Thank you! I will give it a try.
