### ISSUE TITLE
Importing Massive Sets of Photos

### ISSUE THREAD

**Issue by deidyomega** [electerious/Lychee#374]
I am trying to import 36K photos, at around 17GB.

And it uploads about 1.5K, then it says complete.. deleting the ones it uploaded.  Then I need to click import, start the process over again.. right now I am on set 7, and have about 9k uploaded.

You really need to create an simple mass upload tool, even if using php-cli to upload a large set of photos...

**Comment by deidyomega** [comment]
Also... after finally getting 36k of files uploaded...

#Have you heard of paging????

Seriously, it takes 5 minutes to load, then moving down is nearly impossible.

**Comment by electerious** [comment]
Calm down.

**Comment by deidyomega** [comment]
Sorry about the double post.

Anyway, with 17GB of data and 36k photos without paging, the system fails.  When I had 5k, it worked fine... which is impressive.

I can give you access if you care to watch your browser spin for a while.

**Comment by electerious** [comment]
Lets split the problem into two issues:
Import not working well when importing photos => https://github.com/electerious/Lychee/issues/371
Poor performance when using Lychee with many albums => https://github.com/electerious/Lychee/issues/241

**Comment by deidyomega** [comment]
#241 => not sure if it applies, it's one album, 'unsorted'.

**Comment by electerious** [comment]
All your photos are currently in one album?

**Comment by deidyomega** [comment]
Yea, all images are within the 'unsorted' album.

**Comment by electerious** [comment]
Oh, that should be really really slow. It could be worth to add some kind of lazy loading and/or [Clusterize.js](http://nexts.github.io/Clusterize.js/) as I'm not a huge fan of the old-school pagination.

**Comment by deidyomega** [comment]
Clusterize might work, why don't you like pagination?  Google image search uses pagination effectively. It uses pagination, but auto loads the next section when you hit a hidden div.   However, with a super set, lazy loading may not be effective.

10k+ photos may work, but after you get this working, but with ~40k, I imagine it would crash before it ever got 1/2 way down the page, unless lazy loading is also unloading the previous images

**Comment by electerious** [comment]
https://github.com/electerious/Lychee/issues/472
