### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by ooozd** [electerious/Lychee#377]
I did an update as described in the documentation by pulling from the repository. After that a reload of the Lychee site lead the some 'Function not found' error message. A server reboot only made it worse: blank page with no error message—even not in the apache logs.

**Comment by electerious** [comment]
Hi, is your site available online? You you send me the link?

**Comment by ooozd** [comment]
Thank you for the answer. I just found the solution: after the update you have to reload about 10 times for about 15 minutes. Then the new version is working o_O

**Comment by electerious** [comment]
How many photos do you mange with Lychee? Maybe it took some time to update.

**Comment by ooozd** [comment]
It’s quite a lot photos actually. If it it possible, I would suggest a message during the update. Something like 'Lychee is updating its database. After the update it will be available again.'.

**Comment by electerious** [comment]
Yes, that makes sense, but it should't happen again. Updates only take milliseconds. There was only one update operation that took a while and I guess that's the one causing your issue. New installations and newer versions aren't affected.

**Comment by ooozd** [comment]
Thanks for your support!
