### ISSUE TITLE
[nginx] lychee doesn't work

### ISSUE THREAD

**Issue by Wonderfall** [electerious/Lychee#378]
Hi, 

I tried installing Lychee but it didn't work. This is what I see when I go to my Lychee instance : 
<img width="1165" alt="screen shot 2015-07-13 at 23 32 01" src="https://cloud.githubusercontent.com/assets/5507232/8661376/654b0f82-29b7-11e5-8526-bb1730e00fd3.png">

I can't even see what's in plugins/check/index.php (blank screen).
Here is my vhost.conf, I'm using nginx as my web server : https://gist.github.com/Wonderfall/e6e16d72c1fad2993638
I tried restarting php5-fpm & nginx but Lychee still doesn't work.

I'm already hosting some vhosts (like owncloud, wordpress...) without any problem, on my dedicated server running Debian Jessie. I really don't know where it fails... Thanks.

**Comment by ottonet** [comment]
Had some troubles getting lychee to work with nginx as well. Finally got it working with [this](https://gist.github.com/ottonet/3e488ff995193f02fa2d) config.
