### ISSUE TITLE
GPS exif information missing after upload

### ISSUE THREAD

**Issue by jamesingham** [electerious/Lychee#380]
I noticed after uploading some images that the file size changed (when comparing the original with the uploaded file in /uploads/big). So I started to see what was different and then noticed that the location data was missing in the uploaded version. Is this data removed intentionally?

In #180 it was mentioned that you are planning to show the location in the future. This makes me think that it isn't supposed to be removing the exif gps data.

**Comment by jamesingham** [comment]
I wonder if this is part of the problem... It looks like imagick is not installed. I'm running Lychee on my local Synology NAS so I'll try get that working and test it again.

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.0.3
DB Version:      030003
System:          Linux
PHP Version:     5.5
MySQL Version:   50543
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment]
I'm not removing them explicitly, but maybe your OS (e.g. iOS removes the EXIF data when uploading via a web-form). Lychee itself shouldn't modify the EXIF data of your photos in `/uploads/big`.

What happens to the rest of the EXIF information?

**Comment by jamesingham** [comment]
The first images I uploaded were taken with an iPhone, however I had copied them to Mac OS X a couple of years ago before then uploading them to Lychee yesterday. I used a geotag viewer and also checked by viewing the image properties in Mac OS X to confirm that the gps data was being removed.

I'm at work right now (Lychee is running locally at home), but I will upload a couple of example images on here later today. One before and one after uploading and you should be able to see the EXIF data differences.

I will also test by using Windows to upload the images and see if it makes a difference.

**Comment by electerious** [comment]
That would be a big help. Thanks!

**Comment by jamesingham** [comment]
Do you think the lack of Imagick might be not helping the situation? I was looking to install it but I'm pretty limited on my Synology NAS!

**Comment by electerious** [comment]
I don't think this makes a difference. Photos in `/uploads/big` aren't modified. They are copied to the folder using PHP.

**Comment by jamesingham** [comment]
Silly picture but this was what I was using to test it yesterday.

For some reason this picture which is 3.2MB (with gps exif) is then a 5MB file (without gps exif) after uploading.

![before-upload](https://cloud.githubusercontent.com/assets/326552/8744250/a27cce50-2c6d-11e5-8f38-b8e13425189c.jpg)
![after-upload](https://cloud.githubusercontent.com/assets/326552/8744249/a277face-2c6d-11e5-8d8e-559123338580.jpg)

I will test with Windows 7 in a couple of hours.

**Comment by jamesingham** [comment]
I've just noticed that after uploading those above that one appears landscape and one appears portrait in the chat, however on my desktop (and on Lychee) they are all portrait. Is the device orientation saved in the EXIF or something?

**Comment by jamesingham** [comment]
![screen shot 2015-07-17 at 10 28 41](https://cloud.githubusercontent.com/assets/326552/8744414/f6d2616c-2c6e-11e5-9329-e5b75504612a.png)

**Comment by electerious** [comment]
Yes, the photo orientation is saved in the EXIF metadata. It's handled different by every browser and system.

I see the same when using your photo, but it still has the EXIF data. Try using Preview to display them. The info-pane in OS X is broken and hides info randomly.

**Comment by jamesingham** [comment]
Do you see the lat/long on both images then?

**Comment by jamesingham** [comment]
I've just tested with preview and I only see the GPS data on before-upload.jpg. There is some exif data, just not the location data.

**Comment by jamesingham** [comment]
I'm starting to think that this is to do with the browser when uploading. I will run some tests with different setups and get back to you.

**Comment by jamesingham** [comment]
Sorry it took so long but I ran some tests and the exact same thing happened to me using Windows 7 (Google Chrome). I will try some more browsers.

**Comment by jamesingham** [comment]
Hi,

I ran up a debian server today on AWS, modified php to your recommended settings and confirmed that all of the php extensions were enabled. I then setup the database and uploaded the same image and experienced the same behaviour.

The image starts off as 3.2MB with the EXIF data and then after it's been uploaded it is a 4.8MB file with no EXIF data.

I was testing this with Chrome, Safari and Firefox on Mac OSX.

What browser / server setup have you been using? I am very curious as to why this happens!!

Thanks

**Comment by jamesingham** [comment]
Here is an interesting scenario...

I read online that flickr retains the exif information when uploading, so I uploaded the same image to flickr (using Chrome on Mac OS X) and all the exif data was there (they show you on their web view) and it was the same 3.2MB file. Then I got the URL to the original image on flickr and imported it to Lychee by using the "Import from Link" option. Then I downloaded the image to my computer from Lychee and it was a 4.8MB file without the EXIF information again... are you sure there is no processing going on?

I wonder if I have the wrong version of a php extension or something...

**Comment by jamesingham** [comment]
# Solved

Regarding my earlier message today, it turns out that Imagick wasn't installed and I forgot to check for this test - should a note be added to [Installation]?

I don't know why the image size changes, but I can confirm that after installing the latest version of Imagick (sudo apt-get install php5-imagick) my images now retain the EXIF information after being uploaded.

It's a shame that I cannot install imagick on my NAS but I am happy to run this on a webserver instead!

[Installation]: https://github.com/electerious/Lychee/blob/master/docs/Installation.md
