### ISSUE TITLE
Display photos from an OwnCloud instance

### ISSUE THREAD

**Issue by Kernald** [electerious/Lychee#387]
I currently store my photos on an OwnCloud instance, and sync it accross my different devices. The bundled gallery in OwnCloud is really simple - too simple. I love the Lychee UI and UX.

Would it be possible to run Lychee in something like a read-only mode? Fetching pictures in an already existing folder (without making copies of it), and generate needed data (thumbnails, metadata databse...) somewhere else?

**Comment by 1337sup3rh4x0r** [comment]
I use this to do the same:
https://github.com/GustavePate/lycheesync

**Comment by Kernald** [comment]
Looks great and nothing to modify on Lychee's side. Thanks!

**Comment by Kernald** [comment]
Well, it makes a copy of every picture (not only thumbnails) in Lychee's folder. I'm looking for a way to avoid that.

**Comment by 1337sup3rh4x0r** [comment]
Then some other tool, namely Photoshow, might be better suited for you:
https://github.com/thibaud-rohmer/PhotoShow
It doesn't look as nice as lychee though.

**Comment by electerious** [comment]
@Kernald lycheesync is currently the only solution to do what you want. Lychee itself requires its own folder-structure, generated thumbnails and a down-scaled version of the full image to provide the best experience.

**Comment by Kernald** [comment]
In fact, Lycheesync has an undocumented option to use symbolic links instead of copies. See GustavePate/lycheesync#31 : this is what I needed. Thanks!
