### ISSUE TITLE
Removing Albums but not Photo's

### ISSUE THREAD

**Issue by Thomvh** [electerious/Lychee#390]
Is it possible to remove all the albums which are automatically created when importing? But I don't want to delete all of the photo's. That seems the only option there is to delete the photo's and albums.

**Comment by electerious** [comment]
Yes, you can only delete individual photos or an album and all the photos it contains. Here are two handy tips to make it easier for you:

- Merge: Right click or select a range of albums to merge them.
- Select All: `cmd+a` or `ctrl+a` to select all albums or all photos > Move or merge them into an album.

![merge](https://cloud.githubusercontent.com/assets/499088/9288306/cdb69df0-4340-11e5-9b97-280026b0659b.gif)
