### ISSUE TITLE
Feature Requests: Public sharing with view.php

### ISSUE THREAD

**Issue by petebulley** [electerious/Lychee#392]
## Public share menu
Currently when an album is shared publicly, and the user viewing the album is not signed in, photos within the album do not have the share menu. Only when the user is signed in is the share menu visible. 

Would it be possible to add the share menu to public photos when the user is not logged in, with social networks etc.? This could be an option when sharing an album so it can be toggled on/off for each album?

![example-4](https://cloud.githubusercontent.com/assets/13861853/9347842/a6c91c86-464c-11e5-81ce-36195064348f.png)

## Public album sharing with view.php
From what I understand having read other issues, sharing photos on Facebook only works seamlessly when the photo in question is not in a public album.

Since it might be fair to assume that it is a popular use case that users would wish to share photos in public albums, is there a work around to this?

Single photos in a public album have a URL like this: http://electerious.com/lychee_demo/#5/13902216891974

When sharing this link on Facebook, due to the ajax issue explained [here](https://github.com/electerious/Lychee/issues/294) and [here](http://stackoverflow.com/questions/5167759/trying-to-update-facebook-open-graph-meta-tags-using-client-side-jquery-and-ajax), the thumbnail won't load:

![example-1](https://cloud.githubusercontent.com/assets/13861853/9347679/991fbf6a-464a-11e5-8b68-06e6df74644e.png)

However if the URL is manually changed to replace the album ID `/#5/` with `/view.php?p=`: http://electerious.com/lychee_demo/view.php?p=13902216891974 it works perfectly in Facebook:

![example-2](https://cloud.githubusercontent.com/assets/13861853/9347715/fc77b626-464a-11e5-96fd-2ec2307b6df0.png)

Pretty easy work around for anyone who is tech savvy but my wife, friends and family will never cope with this. Therefore my feature request is that when a user accesses the share menu, the URL shown and used when a social network is selected, uses view.php by default rather than index.html.

![example-3](https://cloud.githubusercontent.com/assets/13861853/9347830/7bc18078-464c-11e5-855b-4c119e3bf571.png)

Thanks

PS: Lychee is fantastic so thanks a lot and do keep up the good work!

**Comment by Thomvh** [comment]
Another request, which is in line with this one. Changing the url of public folders.
I host lychee at home. So lychee automatically creates links like: http://192.168.1.3/xxxx but I wanna change that to my public domain.

**Comment by electerious** [comment]
> Would it be possible to add the share menu to public photos when the user is not logged in, with social networks etc.? This could be an option when sharing an album so it can be toggled on/off for each album?

This has been planned for a long time, but it's still not implemented. I will keep it in mind.

> Pretty easy work around for anyone who is tech savvy but my wife, friends and family will never cope with this. Therefore my feature request is that when a user accesses the share menu, the URL shown and used when a social network is selected, uses view.php by default rather than index.html.

Yes, I think this makes sense. Twitter, Facebook etc. are already using the view.php. Will change the share-link, too. => Done

@Thomvh The ability to change URLs is not planned. Lychee always uses the URL you use to access the UI. Is there anything that prevents you from using your public domain? Could you give me some additional insides about your setup?

**Comment by Thomvh** [comment]
It runs on an proxmox setupbon my home network. Thats why it uses an
internal ip adres.
Op 21 aug. 2015 10:00 PM schreef "Tobias Reich" <notifications@github.com>:

**Comment by petebulley** [comment]
On the first issue above - public share menu, do you have a plan for implementation?

Another related question is whether it's possible for the URL used in meta when sharing (I'm thinking specifically about Facebook, so meta property="og:url") to be the album URL rather than the photo (view.php) - I don't know if this would work? If it's not something you want to include is there something I can change in misk.php for this? The reason for the request is that when people click on the photo shared on Facebook, they then see only the specific photo and cannot reach the album, we would like them to see the album but I would understand if not everyone would want this.

Appreciate your response, thanks for everything with Lychee, it's a great app!

**Comment by electerious** [comment]
@petebulley It's not possible to share the main site with open graph data included. That's why the share menu copies a link to the view.php. You can still share the album URL if you want. Here's more about the problematic: https://github.com/electerious/Lychee/issues/294

**Comment by electerious** [comment]
Moved the open task to a separated issue: https://github.com/electerious/Lychee/issues/473
