### ISSUE TITLE
trouble uploading .gifs

### ISSUE THREAD

**Issue by psjbeisler** [electerious/Lychee#393]
i dont know if its just some .gifs or what, but I seem to keep getting failed uploads:

2015-08-18 22:37:01 America/New_York - error - Photo::add (98) 	- Photo type not supported
2015-08-18 22:37:24 America/New_York - error - Photo::add (98) 	- Photo type not supported
2015-08-19 18:16:50 America/New_York - error - Photo::add (102) 	- Photo type not supported
2015-08-19 22:03:16 America/New_York - error - Photo::add (102) 	- Photo type not supported

**Comment by electerious** [comment]
Just tried a few gifs, but they all seem to work. Could you please attach the gif and post the output of the diagnostics (Settings -> Diagnostics)?

**Comment by psjbeisler** [comment]
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.0.5
DB Version:      030003
System:          Linux
PHP Version:     5.6
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1
Plugins:

**Comment by psjbeisler** [comment]
I just tried again (with the same file) and it worked this time... -_-

**Comment by electerious** [comment]
That's strange. Could you attach one of those failing gis?

**Comment by psjbeisler** [comment]
http://i.imgur.com/JEZRwUy.gifv

Downloads as .gif, upload to Lychee. watches failure

**Comment by electerious** [comment]
The gif works fine on my computer and fails on my server. Same image, same PHP version.

**Comment by electerious** [comment]
It's because of an upload error.

> UPLOAD_ERR_INI_SIZE: The uploaded file exceeds the upload_max_filesize directive in php.ini.

There's currently no check if the upload failed. Lychee continues and tries to verify the image, which isn't possible.

I will add additional checks. Thanks for the report!

**Comment by electerious** [comment]
The next version of Lychee will show the correct error.

<img width="532" alt="lychee - unsorted" src="https://cloud.githubusercontent.com/assets/499088/9564058/5d8005e8-4e9a-11e5-81d4-8e602fb33d94.png">
