### ISSUE TITLE
Have Thumbnails Maintain Aspect Ratio

### ISSUE THREAD

**Issue by thindery** [electerious/Lychee#394]
I love everything this software does!  

Is it possible to have the thumbnails of the images keep their aspect ratio and not be cropped to a square?  I have clients that think my images are all squares.  Thanks!

**Comment by electerious** [comment]
Hi @thindery, that's currently not possible nor planned. We will keep the aspect ratio for now. Changing this would require CSS and PHP adjustments.

**Comment by davidmerfield** [comment]
Hi @electerious. I hope you eventually reconsider your position. The cropped thumbnails are not accurate representations of the full image for obvious reasons. 

I know it looks cleaner to have a grid full of squares. However, when you crop the previews, you change the photo. This makes finding a photo harder. For example, one of these photos is a panorama:

![Imgur](http://i.imgur.com/yqOKhhG.jpg)

You guys are building a photo application, please respect the photos. Lightroom, iPhoto etc..preserve your photo's aspect ratio in thumbnail view for good reason.

**Comment by gilav** [comment]
Hello

Mofifying the createThumb method in the php/Modules/Photo.php, overlaping a 'scaled_to_200_keeping_ratio' version of the image over a 200x200 back image works for me :

![200_200_thumbnail_with_image_ratio_ok](https://cloud.githubusercontent.com/assets/7136351/20305725/3a946dbc-ab37-11e6-82db-b68734f49f66.jpg)

In this way there is no CSS change. 

best regards

Gilles
