### ISSUE TITLE
Import files in place

### ISSUE THREAD

**Issue by vidit10** [electerious/Lychee#396]
I have all my files on my server, and to import them into Lychee, Lychee makes a copy of each file in /uploads folder. Because of this a same file is stored twice on my server.

I would like to suggest an in-place import where the files are read from their location and not copied/moved to any other place. Only thumbnails are created and stored in /uploads folder.

**Comment by electerious** [comment]
The import is currently not made for an in-place import.

I suggest to try [lycheesync](https://github.com/GustavePate/lycheesync). It has a build-in link mode, which does exactly what you want.

>  Don't copy files from source folder to lychee directory structure, just create symbolic links (thumbnails will however be created in lychee's directory structure)
