### ISSUE TITLE
"Function not found" error after during the upload of an image

### ISSUE THREAD

**Issue by raphael0202** [electerious/Lychee#398]
I've tried to upload an image after a fresh install of the last version of Lychee, but I get a "function not found" error.
Nothing displayed on the log, and no critical problems found on the diagnostic tool. I've disabled imagick for testing purpose.
You can find attached a screenshot of the response in the console.
![capture du 2015-08-24 21 22 50](https://cloud.githubusercontent.com/assets/9609923/9449996/6ab94596-4aa6-11e5-9156-bbf16a90c4e2.png)

**Comment by electerious** [comment]
Does this happen with all photos or just with specific ones?

**Comment by raphael0202** [comment]
It happens after all photos, but I reinstalled Lychee and everything works fine now

**Comment by ColinLubout** [comment]
I am having the same issue trying to upload 30 images, 3 of which had this issue the rest went in fine.

The 3 that failed are 3 of the largest ones but there were some others of that size that did work.

My max file upload in php is set to 50M and as far as I remember I have uploaded images over 20M in the past just cant find them.

**Comment by electerious** [comment]
@ColinLubout Can you take a look at the php error log? Should contain some additional details.

**Comment by electerious** [comment]
Can't reproduce the issue.

**Comment by Bramas** [comment]
Advice: set a large enough value for max_post_size php option
