### ISSUE TITLE
Apostrophes in Info

### ISSUE THREAD

**Issue by evermorian** [electerious/Lychee#400]
Using apostrophes in the description text while editing causes it to fail to save the changes to the description. My guess is that this is an issue with escaping apostrophes/single quotes.

**Comment by electerious** [comment]
Both album and photo description seem to work fine with special chars and apostrophes. I tried the following:

<img width="498" alt="lychee - s a d ad a" src="https://cloud.githubusercontent.com/assets/499088/9612589/c0ec8e64-50e6-11e5-9ecd-13e171fcc7e8.png">

Could you please attach the full version of the diagnostics (Settings => Diagnostics)?

**Comment by electerious** [comment]
Still can't reproduce this issue, but the next version of Lychee has an improved escaping mechanism which should fix all potential issues with special chars.
