### ISSUE TITLE
Feature: Advanced search or search within album

### ISSUE THREAD

**Issue by mjlurbanist** [electerious/Lychee#401]
When searching currently its possible to search for multiple tags or for items in other db columns, but I haven't found a way to search both. My particular use case would also be solved with a search bar confined to a particular album. Or any manner of more detailed search.

Use case: I'm organizing photos by subject (album), selecting the best group (star), and tagging those for use in projects by the focus of the photo. So my tags are the same across albums and I would like to search for the matching tag or tags within one album at a time.

**Comment by electerious** [comment]
I'm with you. An advanced search would be great.

**Comment by kriyeng** [comment]
I've added this lines in the search.php in order to filter by multiple tags, each of them required. I think maybe is usefull and works like search within results.

```php
	$terms = explode(" ", $term);
	$str_like = "";
	foreach ($terms as $value) {
		$str_like .= ($str_like=="" ? "" : " AND ") . " (title LIKE '%" . $value . "%' OR description LIKE '%" . $value . "%' OR tags LIKE '%" . $value . "%')";
	}
	$query  = Database::prepare(Database::get(), "SELECT id, title, tags, public, star, album, thumbUrl, takestamp, url FROM ? WHERE " . $str_like, array(LYCHEE_TABLE_PHOTOS));
```



I'm not a php developer, I'm sure the code could be better. 
Thanks for this great manager electeriuous!

**Comment by ultramizer** [comment]
@kriyeng i love you! That works like charm!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
