### ISSUE TITLE
Editing Login Timeout

### ISSUE THREAD

**Issue by guyhamilton** [electerious/Lychee#402]
Hi, great plugin!

I am having an issue during file upload from Dropbox or normal file upload. It seems the user is signed out after an hour or so and checking the log it looks like the uploads stop due to this. I just wanted to see if there was a way to keep the user signed in or edit the timeout so you can keep the user signed in for longer?

Anyways keep up the great work!

**Comment by electerious** [comment]
Glad you like Lychee!

Yes, it's possible to edit the session timeout. It primary depends on your php configuration. You can find more information online:

http://php.net/manual/en/function.session-set-cookie-params.php
http://www.php.net/manual/en/session.configuration.php#ini.session.cookie-lifetime

**Comment by twofoldcreative** [comment]
Thanks so much - will check it out!

**Comment by xxxzhi** [comment]
oh, thanks

**Comment by rsmith4321** [comment]
I know you marked this as closed but would it be possible to give more detailed instructions for staying logged in longer.  I would prefer a permanent login if possible.  Thanks.

**Comment by qligier** [comment]
It depends on your environment. You can change the session lifetime by setting the `session.cookie_lifetime` and `session.gc_maxlifetime` parameters to the desired value.

The first one sets the lifetime of the cookie stored in the client browser. The second one sets the time after the last modification on which a session can be deleted on server side. As soon as one or the other is deleted, your session ends. [More on these parameters](http://stackoverflow.com/a/1270960/4990350).

To set the parameter, you can either modify the code (with [ini_set](http://php.net/manual/en/function.ini-set.php) and [session_set_cookie_params](http://php.net/manual/en/function.session-set-cookie-params.php)), use an `.htaccess` file or modify your `php.ini` file depending on what server you run.
