### ISSUE TITLE
Remove Smart Albums

### ISSUE THREAD

**Issue by percivaland** [electerious/Lychee#405]
How can I disable the smart albums? I only want the albums I create to show up on my home page. 

I tried removing a few things in the album.php file and the view.js file but it seems I have removed all albums. I just want to get rid of the smart albums.

Thanks!

**Comment by electerious** [comment]
Sorry, but I can't provide any help for custom modifications. Smart Albums are a hard-coded part of Lychee. Removing them requires several changes. More: https://github.com/electerious/Lychee/issues/265
