### ISSUE TITLE
Multiple photo upload not working on iOS9

### ISSUE THREAD

**Issue by eriksc** [electerious/Lychee#407]
It seems that iOS9 allows iDevices to upload multiple photos at once in safari/chrome. Although in Lychee only the first one gets uploaded, and the rest keeps on waiting in upload pop up. Could this be some kind of bug on the lychee side?

**Comment by electerious** [comment]
I tried to upload multiple photos from Dropbox and Documents, but can't find a way to select more than one :-/ Only the Photos app allowed me to select multiple files. In this case everything worked fine.

BTW: The content of the upload-modal is constantly flashing for an unknown reason. Do you have the same problem or other Lychee-related bugs on iOS 9?

**Comment by eriksc** [comment]
Edit: as i'm trying this on Safari as well, it seems to work without problems, so it looks like it is an issue in Chomr eon iOS. Don't think it is an issue with Lychee in that. If you want to try it anyway, this was my original reply:

Great new feature, makes uploading from iPhone very easy :-)
---

I tried it in Chrome on iOS 9. These are the exact steps:

- View Lychee album in Chrome on iOS 9
- Click on + in right upper corner
- Choose 'Upload photo'
- You will see a popup from iOS with the options Take Photo, Photo Library and More.. (This 'more' option seems to let you choose photos from other apps, haven't tried it yet, but nice feature)
- Choose 'Photo Library'
- You will now see the same interface as in the Photos app. Choose an album and you can select multiple photos here.
- Click on 'Done' and watch it fail at the second upload in the modal.

**Comment by eriksc** [comment]
And I do not have any issues with the modal. Tested in Chrome and Safari on both iPad and iPhone. Works fine except the issue above for Chrome.
