### ISSUE TITLE
Upload Fail: Missing parameters or variables

### ISSUE THREAD

**Issue by jfael** [electerious/Lychee#410]
A friend sent me a photo taken with a Lumia phone but when I try to upload it for some reason it fails and gives me the following error:

"Can not execute function. Missing parameters or variables. Please take a look at the console of your browser for further details."

Tried with Chrome and FireFox, no change in behavior.
Tried to clear the EXIF data with no effect on the problem.

Here is the example photo for reference (just used my awesome paint skills to blur the photo a bit :) ).
![wp_20150826_002 medium](https://cloud.githubusercontent.com/assets/15029644/10363323/d38df558-6dab-11e5-808b-34dabe252eab.jpg)

### plugins/check/index.php
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.0.5
DB Version:      030003
System:          FreeBSD
PHP Version:     5.6
MySQL Version:   50626
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by HoffmannP** [comment]
You do not have Imagick installed, probablymerging  #408 could show that

**Comment by electerious** [comment]
@HoffmannP That's not the case. Lychee will use GD when Imagick isn't available. 

@jfael I can confirm that the image is casing issues. Not sure why, yet. Will take a look at it by time.

**Comment by HoffmannP** [comment]
The file is not realy a jpeg. On a linux system you can type `file $filename` and see that it's a

    JPEG image data, JFIF standard 1.01

so it's a (JFIF)[https://de.wikipedia.org/wiki/JPEG_File_Interchange_Format]. And JFIFs are not supported by `getimagesize` in `Photo::getInfo` @ `php/modules/Photo.php:727`.

**Comment by electerious** [comment]
I tested Lychee with JFIF-photos and they work fine. You can resave the image and it will work, too. Even with "JPEG image data, JFIF standard 1.01". It also works when removing the EXIF data from the photo using [ImageOptim](https://imageoptim.com). Not sure why.

**Comment by electerious** [comment]
@HoffmannP Seems indeed a problem with `getimagesize`.It simply returns nothing.

**Comment by jfael** [comment]
Humm, cleaning EXIF data does work...
I did try it before with "easyexifdelete" but the problem was still happening.
Tried it again but with different software "exif purge" and now it works.

Thank you for the workaround :)

**Comment by HoffmannP** [comment]
One could open a php-bug?
