### ISSUE TITLE
Upload bug related to resolution

### ISSUE THREAD

**Issue by citruspers** [electerious/Lychee#413]
I've encountered a really strange problem where Lychee fails the upload specific image files, generating a "server sent an unknown response" error. The uploader does continue to upload other files, however.

I've tracked the problem down to specific image files from different cameras and I tried the following:

Scale the photos down (maintaining aspect ratio)
Remove all metadata
Remove color profiles
Add color profiles
Installed imagemagick
Tried different jpeg settings

..all without success.

Then I noticed the problems only occur with vertical images (so far) so I elected to decrease the vertical pixel count by one pixel. Success!
Increasing the vertical pixel count also works around the issue.

So it seems that something weird is going on with specific aspect ratios and/or pixel counts. However, the problem both occurs with an aspect ratio of 1.5 as well as 1,762441314553991 so I don't think it's a rounding error.

Any thoughts? I've included one of the problematic files as well as a resized one to reproduce the problem and workaround.

--------------------------------

Working file:
![sdim0079_resized](https://cloud.githubusercontent.com/assets/9105058/10649637/703b3a5c-7845-11e5-9e70-340811bd8dbb.jpg)

Not working file:
![sdim0079_error](https://cloud.githubusercontent.com/assets/9105058/10649638/703b7e90-7845-11e5-902c-f3a545a2ce86.jpg)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Warning: Lychee uses the GBK charset to avoid sql injections on your MySQL version. Please update to MySQL 5.5 or higher to enable UTF-8 support.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.0.6
DB Version:      030003
System:          Linux
PHP Version:     5.3
MySQL Version:   50173
Imagick:         1
Imagick Active:  1
Imagick Version: 1650
GD Version:      bundled (2.0.34 compatible)
Plugins:         

Running on CentOS 6 + httpd on x86_64

**Comment by electerious** [comment]
I can't reproduce the error :-/ Both photos are working fine. With and without Imagick installed. Not sure what's casing the problem, you could/should try to upgrade PHP. Version 5.3 is [completely outdated](http://php.net/supported-versions.php).

**Comment by electerious** [comment]
Closing this issue as I can't reproduce it.
