### ISSUE TITLE
docker-compose for Lychee

### ISSUE THREAD

**Issue by isntall** [electerious/Lychee#414]
I have docker-compose working with Lychee and I'm wondering if anyone else would be interested in using this?

Why would someone want this?
* It allows for a persistent Lychee app backed by on disk storage and served with docker.
* It is fairly simple to get going (after getting Lycee and docker-compose) `docker-compse up`

I'm opting to use 2 separate containers (server and db) that use the official PHP and MariaDB containers from the Docker hub.

docker-compose can take care of the container linking, sets up the storage location.

If this is something someone else would be interested i can cleanup what I have on my fork of Lychee and submit patches git@github.com:isntall/Lychee.git branch docker-compose

I could even have Apache2 or NGINX options, possibly.

**Comment by HoffmannP** [comment]
I also run Lychee in a two container environment instead of a dedicated db+apache container, the `docker-compose.yml` is trivial, nevertheless should be added to the already existing docker information, so I vote :+1:

What's even more interesting to me is how you brought your pure Lyche container up to speed. I wrote a separate `Dockerfile` and include a `php.ini` instead of modifiyng it inside the Dockerfile. My extra is, that I changed the apache-user to me (the user on the host machine) to be able to modify Lychee files seamlessly. I must say I like the idea of not using apache as it's doesn't fit as an PHP-Server any more, lighttpd/NGINX are preferable.


#### docker-compose.yml

    web:
      build: lychee-php
      ports:
       - 81:80
      volumes:
       - ./code:/var/www/html/
      links:
        - db:mysql
    db:
      image: mariadb:5.5
      environment:
        MYSQL_ROOT_PASSWORD: $WHATEVER$
      volumes:
        - ./data:/var/lib/mysql


#### Dockerfile

    FROM php:5.4-apache
    
    RUN groupadd -g 1000 -r $LOCAL_USER && \
        useradd -u 1000 -r --create-home -g $LOCAL_USER $LOCAL_USER &&
        sed -i \
            -e "s/^User www-data/User $LOCAL_USER/" \
            -e "s/^Group www-data/User $LOCAL_USER/" \
            /etc/apache2/apache2.conf
    
    COPY ./php.ini /usr/local/etc/php/
    
    RUN apt-get -y update && apt-get install -y \
      zlib1g-dev \
      libpng12-dev \
      imagemagick && \
      docker-php-ext-install mysqli && \
      docker-php-ext-install gd && \
      docker-php-ext-install exif && \
      docker-php-ext-install mbstring


#### php.ini

    log_errors = On
    error_reporting = E_ALL
    display_errors = On
    html_errors = On
    error_log = /var/log/php.log
    
    max_execution_time = 200
    post_max_size = 100M
    upload_max_size = 100M
    upload_max_filesize = 20M
    memory_limit = 256M

**Comment by isntall** [comment]
I put together the php-fpm container and added a third container for NGINX into the docker-compose.yml
* git@github.com:isntall/Lychee.git branch docker-compose_fpm

I kept the NGINX container separate since it only needed some conf changes and did not require a rebuild.


And changed the branch name of the Apache2 branch
* git@github.com:isntall/Lychee.git branch docker-compose_mod-php

Both of these need more testing and I'm not sure which names make more since, but the worked in my quick tests. The Docker Hub descriptions will need to be written.

**Comment by isntall** [comment]
@HoffmannP I have added the ability to set the UID of the dir and files. 
If you run
`$ USERID=$UID docker-compose up`
the dir and files will be chown'ed to $USERID:www-data

I've only tested this on `docker-compose version: 1.5.0rc1`

If the USERID variable is not set or can not be set, the files are chown'ed to www-data by default.

**Comment by electerious** [comment]
The Dockerfile has been removed. I added a [new section](https://github.com/electerious/Lychee#docker) to the readme which links to some great alternatives. Feel free to fork and improve the repo provided by @kdelfour: https://github.com/kdelfour/lychee-docker
