### ISSUE TITLE
Lightroom tags not identified or imported

### ISSUE THREAD

**Issue by sdenaro** [electerious/Lychee#415]
I've tried two different ways to add tags on export, XMP sidecar and writing EXIF into the files. Neither are being identified. I'm exporting from Lightroom to Lychee via lychee upload as a post export action. Photos show up in lychee but no tags. The tags exist in the local export copies created before upload.

**Comment by electerious** [comment]
Hi @sdenaro. The current version of Lychee doesn't support Tags in photos. Tags are only added/removed from the database, not from the photo metadata itself. It's a planned feature. See #309.
