### ISSUE TITLE
Server returned the status code 200! Only for Nikon pictures. 

### ISSUE THREAD

**Issue by ZGingerAssassin** [electerious/Lychee#416]
Hey. I have just installed Lychee and when I try to upload a photo from my Nikon D5300 it returns the status code 200. I have tried different picture and they work fine, it only seems to be photos from my camera. I have attached the information for on the pictures from the camera. I have tried reinstalling XAMPP and still the same problem. Everything is up to date as far as I can see. 
Any help would be greatly appreciated. Many thanks.

Here is the diagnostics report:
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.0.6
DB Version:      030003
System:          WINNT
PHP Version:     5.6
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         
```

![image](https://cloud.githubusercontent.com/assets/7832403/10869322/12a42d7e-80a4-11e5-8f22-4e88f7873b6a.png)
![image](https://cloud.githubusercontent.com/assets/7832403/10869323/1c9f77a2-80a4-11e5-98cd-246cdbd7d2d1.png)
![image](https://cloud.githubusercontent.com/assets/7832403/10869324/37e3e138-80a4-11e5-8800-29cfaa097dce.png)

**Comment by electerious** [comment]
Maybe because PHP is running out of memory. Could you reduce the file size and try it again?

**Comment by ZGingerAssassin** [comment]
That seemed to have worked. I opened the photo in Photoshop and saved it as a JPG with low quality. Is there anyway to allocate more memory to PHP?

**Comment by electerious** [comment]
Yes, you can edit the `php.ini` to use Lychee without restrictions: https://github.com/electerious/Lychee/blob/master/docs/Installation.md#1-requirements

**Comment by ZGingerAssassin** [comment]
Thanks. I can only find .user in my Lychee folder. I have tried uncommenting the lines, but still get the same error. I am running XAMPP so I have also tried to edit the .htaccess. When I upload the file it says processing for about 3 seconds and then gives me the 200 error again. 

My diagnostics look like this now:

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.0.6
DB Version:      030003
System:          WINNT
PHP Version:     5.6
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:       

```

**Comment by electerious** [comment]
The `php.ini` isn't a part of Lychee. It's a part of your PHP installation: http://php.net/manual/en/configuration.file.php
