### ISSUE TITLE
Pictures selection, copying, displaying tags, ratings, etc...

### ISSUE THREAD

**Issue by radomici** [electerious/Lychee#423]
I found the folowing features would be helpful:
Selecting multiple pictures that are not consecutive, i.e. like selecting any picture with holding down Ctrl key.
Add rating to each picture in the form of stars (I think 5 stars is just right)
Options to turn on/off displaying tags, star, date, rating, or any other info in the About pane directly in the picture in preview screen.
Copying pictures directly into a different album instead of duplicating it into the same album and going back to it to move it to different album.
I'm usin Lychee on Sandstorm.io

**Comment by electerious** [comment]
Some of those features are already planned:

> Selecting multiple pictures that are not consecutive, i.e. like selecting any picture with holding down Ctrl key.

https://github.com/electerious/Lychee/issues/339

> Add rating to each picture in the form of stars (I think 5 stars is just right)

https://github.com/electerious/Lychee/issues/310

> Options to turn on/off displaying tags, star, date, rating, or any other info in the About pane directly in the picture in preview screen.

That's not planned.

> Copying pictures directly into a different album instead of duplicating it into the same album and going

A agree that this would be a nice addition, but I don't think that it's necessary and just adds more lines to the codebase. A better way to select photos is a good trade-off and makes it easier to move the copies.
