### ISSUE TITLE
Wordpress import [enhancement]

### ISSUE THREAD

**Issue by ET-Bent** [electerious/Lychee#424]
Using Lychee for a few days now and I really like it.

A great improvement would be a 'import from Wordpress' option.

Some ideas on realizing this:

- The Wordpress installation has to be on the same host as Lychee
- Wordpress stores it's image at `/var/www/wordpressRoot/wp-content/uploads/YYYY/MM/`
- From the location above, **link** (symlink) all full scale files e.g. 'IMG_SomeName.jpg' to Lychee (don't copy files to reduce disk usage), exclude all files with extra resolutions 'IMG_SomeName-123x456.jpg' 
- Autocreate a "imported from Wordpress" folder in Lychee and auto update this folder with a cronjob (optional)

**Comment by electerious** [comment]
It's not planned to build a "complex" import directly into Lychee. The current import was not made for such a feature.

I suggest to try [lycheesync](https://github.com/GustavePate/lycheesync). It has a build-in link mode, which does exactly what you want.

>  Don't copy files from source folder to lychee directory structure, just create symbolic links (thumbnails will however be created in lychee's directory structure)
