### ISSUE TITLE
Create Medium sized photos JIT

### ISSUE THREAD

**Issue by palitu** [electerious/Lychee#425]
It would be a decent feature to create medium sized photos JIT when someone views an album.

I use the Lycheesync script to import my photo's, and have thousands.  I have modified the script to create the medium sized files, but as you could imagine, this is very time consuming.

It should not be too hard to create the medium file when someone clicks on the thumbnail, then display the medium file.  You can have a set medium cache size, which will delete files as needed.

Then have a site wide flag for whether you want to show medium files or not.

I will have a look in the source, but i am not great with php.

cheers

**Comment by electerious** [comment]
The idea doesn't sound bad, but I'm not sure how performant it is to create them on the fly with PHP. I think it's worth the trade-off, that uploads take longer. Adding caching, checks if a file exist and JIT generation would add much more complexity to the code.
