### ISSUE TITLE
Thumbnail squished instead of cropped (php7)

### ISSUE THREAD

**Issue by isntall** [electerious/Lychee#430]
I recently upgraded my PHP version to php7 since it was released.

While uploading photos worked fine, the thumbnail was squished instead of cropped.

below is my Diagnostics

System Information
------------------
Lychee Version:  3.0.7
DB Version:      030003
System:          Linux
PHP Version:     7
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment]
Imagick is installed and activated on your installation. Maybe an PHP7 + Imagick bug? Could you try to [disable it](https://github.com/electerious/Lychee/blob/master/docs/Settings.md#imagick)?

**Comment by isntall** [comment]
Thank you.

My issue looks to have been caused by imagick-3.4.0RC2.
The issue has been solved in 3.4.0RC3 
* [Change log] (https://pecl.php.net/package-info.php?package=imagick&version=3.4.0RC3)
  * Imagick::adaptiveResizeImage, Imagick::cropThumbnailImage Imagick::resizeImage,
Imagick::scaleImage, and Imagick::thumbnailImage have all had a rounding bug fixed.
An additional parameter has been added to each of them, 'bool $legacy'. If legacy
is true, the calculations are done with the small rounding bug that existed in
Imagick before 3.4.0. If false, the calculations should produce the same results as
ImageMagick CLI does.

**Comment by isntall** [comment]
What is the best way to re-build the image thumbnails?

**Comment by electerious** [comment]
Re-uploading them is the easiest way. If you don't want to delete them you could try to manually edit the thumbnails in the thumbs-folder. But that's properly time-consuming :-/

**Comment by isntall** [comment]
Also, if the image is in more than one album, it will need be removed from all of them and then uploaded. The thumbnail does not get re-created for a duplicate image.

**Comment by bb-Ricardo** [comment]
here a short script to regenerate all thumbnails if you have shell access to your lychee installation. you have to execute it in the "**upload**" directory! And if unsure create a copy of your **thumb** folder first.

you might want to manipulate the find command with "**-mtime -20**" for example to only rebuild the thumbnails for pictures uploaded within the last 20 days.

```bash
for image in $(find thumb -type f | grep -v "@2x"); do
	echo "processing $image"
	FN=$(basename $image)
	FN=${FN//\.*/}
	convert big/$FN.* -thumbnail '200x200^' -gravity center -extent 200x200 -quality 90 "thumb/$FN.jpeg"
	convert big/$FN.* -thumbnail '400x400^' -gravity center -extent 400x400 -quality 90 "thumb/$FN@2x.jpeg"
done
```
