### ISSUE TITLE
Insert Path to Zip File when creating new Album

### ISSUE THREAD

**Issue by endrikus** [electerious/Lychee#432]
Hallo, 
i used it for a large amount of Pictures and try to Split the Albums in 1 GB Folders.

But my Server need a lot of Memory when it should creat the Downloadable Zip Folder on Demand. 

I Upload a zip file to my FTP and then unzip it and import the Pictures to an Album.

Maybe it is possible to add a Path to the Zip file during creating the Album and if you wont type in the path it will create it on demand otherwise it will be stored in the database and the link will opened whenn you will download it.

**Comment by electerious** [comment]
Hi @endrikus, such a feature isn't planned, sorry.
