### ISSUE TITLE
Show albums above photos in search

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [electerious/Lychee#434]
I think it will be better we the Album Name matches were shown on top the File Name matches.

When I am searching something, its mostly bringing up so many file name matches on top that it is getting difficult to go to the album name matches in bottom. I think in most cases number of file name matching will be way more than album name matching.

If you do not wish to change the current behavior of showing file name matching on top in default, please at least make an option so we can toggle this behavior.

**Comment by electerious** [comment]
True. Most people have more photos than albums. That makes it difficult to find albums.

**Comment by electerious** [comment]
The next version will show the albums above the photos in the search.

**Comment by dotcomUNDERGROUND** [comment]
Awesome! Thanks for it!
