### ISSUE TITLE
Version 3.0.8 stills indicates 3.0.7 in Diagnostics page

### ISSUE THREAD

**Issue by LudovicRousseau** [electerious/Lychee#436]
I just upgraded Lychee from 3.0.7 to 3.0.8.
The login dialog indicates 3.0.8.
But the Diagnostics page (``/Lychee/plugins/check/``) stills indicates 3.0.7:
```
System Information
------------------
Lychee Version:  3.0.7
```

I am not sure where this version comes from. I note that the file ``src/package.json`` has
```
  "version": "3.0.7",
```
https://github.com/electerious/Lychee/blob/master/src/package.json#L3

**Comment by electerious** [comment]
Thanks for letting me know. Should be fixed now! :)
