### ISSUE TITLE
Move to next photo after after moving a picture

### ISSUE THREAD

**Issue by hDoubleU71** [electerious/Lychee#437]
While moving a picture to a different folder, don't jump back to image overview, but step over to the next existing picture.
I think this will enhance the sorting of pictures after a import process a lot.

**Comment by electerious** [comment]
Good idea, but introduces some problems with the current implementation: You don't see the photo disappear. It would be necessary to add a subtitle notification or animation that the photo has been moved. I will leave the issue open and keep the idea in mind.

Tip: You can right-click on thumbs to move them quickly.

**Comment by electerious** [comment]
This feature will be part of the next version. Implemented it! :)
