### ISSUE TITLE
Feature request: make Album thumbnails description configurable

### ISSUE THREAD

**Issue by hDoubleU71** [electerious/Lychee#438]
It would be nice to change teh description / labels of the album thumbnails, for example replace the creation date with the number of pictures in the album etc.

**Comment by electerious** [comment]
Hi @hDoubleU71. My target is to keep the configurations and options in Lychee as basic as possible. I decided not to show the photo count as it's more or less irrelevant and just a detail. A description has to be bigger to be readable, which would cover to much of the album thumbnail.
