### ISSUE TITLE
Update Purges Some Album Info

### ISSUE THREAD

**Issue by evermorian** [electerious/Lychee#440]
After updating the last couple times ("manually"), when I first access the Lychee installation with a browser, the public column for all rows in the lychee_albums table is reset to 0 and, the password column for all rows is blanked. While it is not a huge thing to reset those, it kind of seems unnecessary. Any chance of fixing that in the next release?

**Comment by electerious** [comment]
That's not how it should be. It sounds like Lychee runs all database updates, even when it shouldn't. Some information I need to debug:

- How to you update, e.g. which files do you replace?
- Please attach the output of the diagnostics.
- Is there an error related to a database update in the log (Settings -> Show Log)?

**Comment by evermorian** [comment]
I have been updating by downloading the new .zip file from git, extracting the files, then replacing everything except the uploads/ and data/ directories (as per the instructions on the update page).  When I connect to the web UI, it prompts me to create a login.

I see in the diagnostics that Lychee would rather have a newer version of PHP.

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Error: Upgrade to PHP 5.5 or higher

System Information
------------------
Lychee Version: 3.0.8
DB Version: 030003
System: Linux
PHP Version: 5.3
MySQL Version: 50546
Imagick: 1
Imagick Active: 1
Imagick Version: 1641
GD Version: 2.0
Plugins:

There are no recent errors (i.e., from the last update) in the log.

**Comment by electerious** [comment]
I made several changes to the update mechanism: https://github.com/electerious/Lychee/commit/634c3621db40ae3478d051231b264190a45f6843 Will be included in the next update and could fix your problems. However, I'm still not sure what's casing them on your installation.

**Comment by electerious** [comment]
Lychee 3.1 is out and this issue might have been fixed. Please reopen the issue if it still happens.
