### ISSUE TITLE
Feature Request: Auto import out of defined folder (Monosnap support)

### ISSUE THREAD

**Issue by helloeckstein** [electerious/Lychee#443]
Hi. I just installed Lychee, which is really awesome plugin, thank you for developing this!
But I'm just standing in front of a problem for me. I use monosnap for instant sharing screenshots to my ftp server. Sadly, with this method, there isn't any way to have an overview over all uploaded files expect to look on the ftp via a ftp client. So I tried to fill this gap with Lychee. I saw, that there's the way to import files from the server to an album. This is a good start, but when I create a new screenshot, I have to reimport the new ones to have them visible in the album. Also, it would need to keep the location and filename of the uploaded file, so that it still works with Monosnap.

For Example:
I make a screenshot which is instantly uploaded to my ftp by Monosnap in the `website/s` folder and automatically gets named to someting like `20160106AqRgX.png` (or however the settings in Monosnap are set). With the uploading process, a custom url is created too like `www.domain.me/s/20160106AqRgX.png`. It would be really nice now to have the possibility to create a new album in Lychee where I can define a path from where (as written before, in this case `website/s`) Lychee should show the images and not move it to it's own folder or renames it.

This would be such a big improvisation for me and eventually others could use this too.
Thanks for your attention and best greetings
Stefan Eckstein

**Comment by LudovicRousseau** [comment]
Maybe you should have a look at PhotoShow http://www.photoshow-gallery.com/
With PhotoShow you do not need to import the images. Just put them in the correct directory and they are available on the Web.

**Comment by electerious** [comment]
Had the exact same problem with [FileShuttle](https://github.com/FileShuttle/fileshuttle). It could be partially realized as a [plugin](https://github.com/electerious/Lychee/blob/master/docs/Plugins.md).

Will close the issue as I don't want to built this feature directly into Lychee.
