### ISSUE TITLE
Piwik integration

### ISSUE THREAD

**Issue by napo789** [electerious/Lychee#445]
Hello,

How can I add my website lychee to my piwik analystics ?

I need to put this code on webpage : 
```javascript
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{$PIWIK_URL}/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', {$IDSITE}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```
thanks a lot

**Comment by electerious** [comment]
Just add it to the `index.html` :)

**Comment by napo789** [comment]
it's works !
However, it's unfortunate we can not know which albums are displayed.

But it's well !

**Comment by electerious** [comment]
Perfect!

Yes, this won't work as the page stays the same. Lychee uses AJAX to load new content. You can add tracking events to the code, but that's a bit more complex.
