### ISSUE TITLE
PHP error from Database.php

### ISSUE THREAD

**Issue by zbits** [electerious/Lychee#448]
I just ran an import from server and logged these error/warning messages:

```
08:36:25 [error] 475#0: *834 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /www/x.z/i/php/modules/Database.php on line 291
08:36:25 x.z nginx[473]: PHP message: PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /www/x.z/i/php/modules/Database.php on line 291
```

Running Arch Linux, software versions:

```
# php --version
PHP 7.0.2 (cli) (built: Jan  6 2016 11:50:59) ( NTS )
# mysql --version
mysql  Ver 15.1 Distrib 10.1.10-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by electerious** [comment]
Is there a way to reproduce this error?

BTW: Lot of code related to the database will change in the next update. Could be fixed already.

**Comment by zbits** [comment]
I haven't uploaded many photos since I posted this.  If I see it again I will let you know.

Thanks for the fantastic software, it's fits my needs perfectly. I will send you a donation.

**Comment by electerious** [comment]
Lychee 3.1 is out and this issue might have been fixed. Let me know if it happens again.
