### ISSUE TITLE
Improve sharing behavior

### ISSUE THREAD

**Issue by zbits** [electerious/Lychee#449]
I just started using Lychee.  I'm very impressed and it fits my needs exactly.

When I want to make an album public, I was initially confused that by selecting the "Share Album" icon the "Visible" option is already selected, which meant to me that it was already active.

However, even when an album is public and visible without logging in, the Public smart album has nothing in it.  I have 4 public albums now and still nothing in the Public smart album, maybe I'm misunderstanding what they are for?

```
System Information
------------------
Lychee Version:  3.0.9
DB Version:      030003
System:          Linux
PHP Version:     7
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1
Plugins:         
```

**Comment by electerious** [comment]
You have some good points here. The behavior of sharing is not clear and should be improved.

> When I want to make an album public, I was initially confused that by selecting the "Share Album" icon the "Visible" option is already selected, which meant to me that it was already active.

"Visible" means that the album will be visible to visitors of your Lychee installation. It's a preselected sharing-option.

> However, even when an album is public and visible without logging in, the Public smart album has nothing in it. I have 4 public albums now and still nothing in the Public smart album, maybe I'm misunderstanding what they are for?

Smart Albums only contain public photos. So when you share albums, they won't appear in the "Public"-Smart Album.
