### ISSUE TITLE
Adding : base64 storing instead of plain files for small disk size hosting

### ISSUE THREAD

**Issue by Shotman** [electerious/Lychee#450]
Hey, I've came along lychee (it's really cool) for a project I have but on a restricted disk space hosting, that I must use, storing pics in database with their base64 encoding would be a nice feature to add. 

Maybe I'll work myself on a plugin.

**Comment by Bramas** [comment]
Your database is not restricted in space?? Because you know, a base64 image is not a small string. I don't think you want 1GB of data in your database, especially an SQL one.

**Comment by Shotman** [comment]
It's not unlimited SQL base, but you can still store more content that way than in plain files I think

**Comment by electerious** [comment]
Hey @Shotman. Thanks for the idea, but storing photos as base64 in the database is not planned.

**Comment by Bramas** [comment]
@Shotman for your info: [base64 images are 37% bigger](http://stackoverflow.com/questions/11402329/base64-encoded-image-size)
