### ISSUE TITLE
Sign In icon not always visible in Firefox

### ISSUE THREAD

**Issue by bof-sysadmin** [electerious/Lychee#452]
The Sign In icon in the upper left corner of the page is sometimes not visible in Firefox. When hovering over the spot I can see the "Sign In" title text and I can also click it. The login form pops up as usual.

![lychee](https://cloud.githubusercontent.com/assets/15260874/12552346/9c34654e-c371-11e5-99e0-954893bf3b1d.png)

The Sign In icon *does* show when I have opened an album beforehand. The icon is there when returning to the album overview page.

This has been tested on multiple computers with Firefox 43.0.4. This issue is not present in Chromium 47.0.2526.106.

**Comment by electerious** [comment]
Can't reproduce the issue :-/ Works fine on OS X with Firefox 43.0.4. Is the site zoomed in/out? Which version of Lychee are you using?

**Comment by bof-sysadmin** [comment]
Hey electerious,

I'm closing this issue because I can't reproduce it in Firefox 44.0, which suggests that it was a bug in Firefox 43.0.4 for Ubuntu Trusty. I was using Lychee 3.0.9.
Sorry for bothering you, and thank you for your work on Lychee!
