### ISSUE TITLE
Regenerating Thumbnails and Medium Images

### ISSUE THREAD

**Issue by Xiol** [electerious/Lychee#453]
Hi,

I've just finished uploading 4GB of images, then realised I didn't have ImageMagick enabled, so I've missed out on the 'improved thumbnails' and medium-sized images. I've not been able to find a documented way of regenerating these thumbnails. Is there any way I can regenerate these without having to reupload all the content?

If there isn't, I'd like to make this a feature request!

**Comment by Bramas** [comment]
I have written a plugin to do this because I had the exact same problem.
I'll create a repo for it ASAP.

**Comment by Bramas** [comment]
Done: https://github.com/Bramas/lychee-create-medium

**Comment by Xiol** [comment]
That worked great, thanks @Bramas!

**Comment by electerious** [comment]
That's a nice script. Thanks @Bramas! Will add it to the list of plugins/extensions.
