### ISSUE TITLE
Changing the title

### ISSUE THREAD

**Issue by Victhetiger** [electerious/Lychee#455]
Hi,

I'd like to change the branding "Lychee" on the title but I haven't found the option to do so.
This is just for cosmetic purposes, I'm getting tired of seeing "Lychee" on the title.

Sincerely,
Victhetiger

**Comment by electerious** [comment]
Hi @Victhetiger, [changing the title](https://github.com/electerious/Lychee/blob/master/index.html#L6) should do the job.

**Comment by Victhetiger** [comment]
Thank you, worked perfectly.
