### ISSUE TITLE
Apache2 serving corrupt images when stored on network drive

### ISSUE THREAD

**Issue by tgrossner** [electerious/Lychee#458]
I discovered something that other Lychee users might end up needing to know. 
I was seeing some images served up by my Apache2/PHP/Lychee server were being corrupted. Mostly results were half-formed images, some segmenting, etc. What I found when I did some research is that I needed to add "EnableMMAP off" to my apache2.conf file and restart apache2. See http://httpd.apache.org/docs/2.2/mod/core.html#enablemmap for details. I take it that this *might* have bitten me because I was serving up picture files that are stored on a network drive share rather than on the same filesystem as the apache2 host.

Anyway, if you see corruption in your pictures via the web interface, this might be the cause/fix for you. 

Enjoy!

**Comment by electerious** [comment]
Thanks for the tip! I edited the title so others might find it when having the same problem.
