### ISSUE TITLE
set to public/demo mode

### ISSUE THREAD

**Issue by nexusVI** [electerious/Lychee#459]
Great looking & working project, thank you!

I would like to use it as an internal image sharing service. Having it set up just like your demo site would be perfect, as I don't need or want user management at all. access will only be possible in our LAN, no need with user/pw. 

Can you give a hint on what changes you made for the demo?

**Comment by electerious** [comment]
I can't provide any help for customization, but you need to ensure that the user is always logged in by [setting the session](https://github.com/electerious/Lychee/blob/master/php/modules/Session.php#L105) before [checking if we is logged in](https://github.com/electerious/Lychee/blob/master/php/api.php#L60). Maybe that helps a bit.
