### ISSUE TITLE
Dates translations

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#461]
Hi, 
In which file can I find the names of the months?
I would like to translate them, thanks.

**Comment by electerious** [comment]
That's currently not possible, because Lychee uses `date()`. Should be changed in the future. Thanks for the request!

> To format dates in other languages, you should use the setlocale() and strftime() functions instead of date().
On 22. Februar 2016 at 09:14:55, zikamatej (notifications@github.com) wrote:

Hi,
In which file can I find the names of the months?
I would like to translate them, thanks.

**Comment by electerious** [comment]
The next version of Lychee will use `strftime` (thanks @qligier). Manually setting the correct locale information using [setlocale](http://php.net/manual/en/function.setlocale.php) should do the job. Could be placed in the [api.php](https://github.com/electerious/Lychee/blob/master/php/api.php) file. Can't provide any additional information as I never used setlocale, yet.

More is planned: https://github.com/electerious/Lychee/issues/207
