### ISSUE TITLE
Add spaces

### ISSUE THREAD

**Issue by silviupanaite** [electerious/Lychee#463]
A nice feature, to have, would be to add spaces that you could share with others.
space1 
 -- album1
 -- album2

space2 
 -- album1
 -- album2

**Comment by electerious** [comment]
Something like [Collections](https://github.com/electerious/Lychee/issues/254) or [Multi-User](https://github.com/electerious/Lychee/issues/132)?

**Comment by silviupanaite** [comment]
More like https://github.com/electerious/Lychee/issues/254.
