### ISSUE TITLE
Feature request: Resize while uploading

### ISSUE THREAD

**Issue by mscsnoopy** [electerious/Lychee#464]
Awesome work so far! just installed and works like a charm =)

May it be possible (or is it already available?) that images will be resized during upload to a ratio like 1024x768?
Main purpose is that in many forums it is only allowed to embed photos with a max. size of 1024x768

Thanks for the support

**Comment by electerious** [comment]
Lychee scales big photos down so they fit into 1920x1080 (when ImageMagick is installed). You can change the values in the code, but I can't provide any help for customization.

It's not planned to generate more sizes on upload, sorry.
