### ISSUE TITLE
Android Client 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [electerious/Lychee#465]
Hello, thanks for Lychee. 

I love it.
 
Does someone know an  Android client to upload pictures on the go?

**Comment by Klikini** [comment]
I don't think there are any, but you can upload pictures the same as from a desktop with the upload button, then choosing either a camera app or file. I just tested this.

**Comment by b-alidra** [comment]
Hi, I've started [this](https://github.com/b-alidra/ionic-lychee) last year... Feel free to test it

**Comment by electerious** [comment]
Lychee should work fine on Android as a web-app. An official client isn't planned, but it would be cool if someone build one.

@b-alidra Keep up the work! :)
