### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by gaelito17** [electerious/Lychee#466]
Hello 

I'm not able to run the application the first time due to a Javascript error:

> Uncaught TypeError: Cannot read property 'unsorted' of undefinedalbums._createSmartAlbums @ main.js:4(anonymous function) @ main.js:4o @ main.js:4u @ main.js:2d.fireWith @ main.js:2n @ main.js:3(anonymous function) @ main.js:3

I performed the installation and instead of having setup forms, I have a black screen. Any idea?

Thanks

**Comment by julnegre** [comment]
same problem... under debian8 & nginx

**Comment by electerious** [comment]
Could you please attach the output of the diagnostics (`plugins/check/index.php`)?

**Comment by gaelito17** [comment]
A blank page is displayed. Nothing in the console.

**Comment by julnegre** [comment]
for me i reinstall with apache2 and success, but i cant use it with nginx, i dont know why....

**Comment by electerious** [comment]
@gaelito17 I guess your PHP installation is broken or incorrectly configured. At least the diagnostics must show some text. Maybe the same issue as [here](https://github.com/electerious/Lychee/issues/498).

**Comment by gaelito17** [comment]
I also use NGINX. I will try with apache2

**Comment by electerious** [comment]
It should work with nginx, too. But I never used it and can't say how to set it up correctly.

**Comment by matunixe** [comment]
Yo,

You should try this configuration file for your Nginx vhost (works flawless for me):
```
server {
  listen 80;
  server_name lalilou.lol;
  # enforce https
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl http2;
  server_name lalilou.lol;

  # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
  ssl_certificate /usr/local/etc/letsencrypt/live/lalilou.lol/fullchain.pem;
  ssl_certificate_key /usr/local/etc/letsencrypt/live/lalilou.lol/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;

  # modern configuration. tweak to your needs.
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
  ssl_prefer_server_ciphers on;

  # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
  ssl_dhparam /usr/local/etc/ssl/dhparams.pem;

  # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
  add_header Strict-Transport-Security max-age=15768000;

        root /var/www/htdocs/lalilou.lol/Lychee/;
        index index.php index.html index.htm;

        location / {
                    try_files $uri $uri/ /index.html;
        }

        location ~ \.php$ {
                        include fastcgi_params;
                        fastcgi_index index.php;
                        fastcgi_pass 127.0.0.1:9000;
                        fastcgi_param PHP_VALUE "max_execution_time=1800
                                                 post_max_size=1500M
                                                 upload_max_filesize=32M
                                                 max_input_time=1800
                                                 max_file_uploads=300";
                       }
}
```

**Comment by electerious** [comment]
Any news?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
