### ISSUE TITLE
nginx upload file size

### ISSUE THREAD

**Issue by fooltech** [electerious/Lychee#467]
can upload files below 1mb but not above get following on console using Firefox
Object { description: "Upload failed. Server returned the …", params: XMLHttpRequest, response: "<html> <head><title>413 Request Ent…" } main.js:4:28964
lychee.error() main.js:4
upload.start.local/o/a.onload() main.js:5

Object { description: "Upload failed. Server returned the …", params: XMLHttpRequest, response: "<html> <head><title>413 Request Ent…" } main.js:4:28964

Any advice gratefully received

**Comment by electerious** [comment]
Have you tried to adjust the max upload size in the php.ini?

I recommend the following properties:

```
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 20M
memory_limit = 256M
```

Please also include the output of the diagnostics (Settings -> Diagnostics).

**Comment by fooltech** [comment]
Hi

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  2.7.1
DB Version:      020700
System:          Linux
PHP Version:     5.4
MySQL Version:   50547
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.0.36

max_execution_time = 200 current value 200M
post_max_size = 100M current value 100M
upload_max_size = 100M current value 100M
upload_max_filesize = 20M  current value 20M
memory_limit = 256M current value 256M

Web console output on Firefox 44.0.2
Object { description: "Upload failed. Server returned the …", params: 
XMLHttpRequest, response: "<html> <head><title>413 Request Ent…" } 
main.js:4:28964
lychee.error() main.js:4
upload.start.local/o/a.onload() main.js:5

**Comment by electerious** [comment]
The server returns a 413, which is not send by Lychee itself, so the error might happen before starting the Photo-add process. The configuration looks good so far. You could try to take a look at the server logs to get more information.

> max_execution_time = 200 current value 200M
`200M` is just a typo, right?

**Comment by fooltech** [comment]
Hi

200m is a typo sorry

It would appear that the browser is requesting something too large for 
the server to process I am using nginx same thing occurs with Firefox 
and IE11

"<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
"
fooltech

**Comment by fooltech** [comment]
Hi

Sorted problem was with nginx

413 Request Entity Too Large errors trying to upload with nginx

need to modify nginx.conf to overcome 2M limit

add line

client_max_body_size	20M;

Thanks for your help
