### ISSUE TITLE
Uploading via FTP

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#474]
Hi, 
Is it possible to upload photos only via FTP in folders, which will then be recognized by Lychee as photos to sort in albums with the folder names? I don't own the server, I don't have permissions to SSH, or whatever I would use to load them up through SSH, Rsync or lycheesync.
Thanks

**Comment by electerious** [comment]
You can upload them and then manually start an "Import from Server". Is that what you're looking for?

**Comment by zikamatej** [comment]
Yes, thank you, I didn't notice :)
In the end it's useless for me because of the PHP limits given by the hoster. 
Thanks
