### ISSUE TITLE
First time run error

### ISSUE THREAD

**Issue by bagheera2k** [electerious/Lychee#476]
Hi!
I'm unable to run Lychee on my browser due to javascript error below:
`Uncaught TypeError: Cannot read property 'unsorted' of undefinedalbums._createSmartAlbums @ main.js:formatted:5344(anonymous function) @ main.js:formatted:5311o @ main.js:formatted:5422u @ main.js:formatted:1786d.fireWith @ main.js:formatted:1846n @ main.js:formatted:3591(anonymous function) @ main.js:formatted:3869`

I was using [this](http://idroot.net/tutorials/how-to-install-lychee-on-ubuntu-14-04/) guide to perform installation.

Lychee version is c0c924fc13c3b675de06167a95fcbd803b0e4148 (3.0.9).
![lychee_bug](https://cloud.githubusercontent.com/assets/16656998/13557660/949ec596-e3f5-11e5-9a39-93595add45ad.png)

I will provide any additional info if required,

**Comment by bagheera2k** [comment]
![lychee2](https://cloud.githubusercontent.com/assets/16656998/13557798/eda9a966-e3f6-11e5-9365-657956cd8310.png)

It seems to be php issue, since t is just unparsed php code...

**Comment by electerious** [comment]
Looks like it's just returning the PHP file as plain text. Are you sure your PHP installation on your server is fine/working?

**Comment by bagheera2k** [comment]
PHP installation was the problem. Solved.

**Comment by Slamour77** [comment]
Hi
I have the same trouble, and getting PHP reinstalled doesn't fix it. Could you precise how you did ?

**Comment by bagheera2k** [comment]
Hi, i'll check that tomorrow.
10 mar 2016 14:39 "Slamour77" <notifications@github.com> napisał(a):

**Comment by bagheera2k** [comment]
Hi,
I can't provide an exact answer, but i did few things. First of all, my server is running Debian 7 and i had to upgrade PHP and apache and that cost me complicated conflicts. I had to install packages including: php5-gd libgd2-xpm-dev php5-json libapache2-mod-php5 php5-mysqlnd  followed by command:
`sudo a2enmod php5` and several apache restarts.
Check if u have at least symlinks to php5.conf and php5.load in /etc/apache2/mods-enabled if u use apache as web server.
