### ISSUE TITLE
Creation time should sort by sysstamp

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#477]
Hi, 
I have about 12 albums on my server. I changed all of their sysstamp to the right date, but there is an album, where I did not change the `sysstamp` value, which is set to March 2016. All the other albums are older and show in the right order (Sorting: Creation Time, desc). The date shown under the album name is correct everywhere, but the March 2016 album is listed last instead of first.
Thanks for helping.
Version 3.1 #475

**Comment by zikamatej** [comment]
So, after some debugging and changing some values in the database I found out something. Lychee, even if it's set to sort albums by creation time (`sysstamp`), sorts albums by the album ID, which is an option Lychee does not even include :laughing: 

I just can't figure out how to change the setting in the `lychee_settings` database since phpMyAdmin tells me I can't edit it...

**Comment by electerious** [comment]
Sorting by creation time is the same as sorting by id. New albums always have a higher id than the previous ones. But yes, I agree that's confusing when changing the sysstamp. Should be updated.

**Comment by electerious** [comment]
Edit: Will stay with "creation time" === "id" for now. It might be possible to edit the sysstamp through the interface in a future version. A new option "date" would than sort by sysstamp.

**Comment by VictorLamoine** [comment]
How can I manually tweak the ordering then ? Should I modify the ID ?
