### ISSUE TITLE
[help wanted] Disabling Imagick in database

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#478]
Hi again, 
I need to change the value of imagick to 0 in the settings database. I can only use phpMyAdmin to do so, but it doesn't allow me to change it in the row, so I have to use a MySQL command to do so. I just don't know how, although I tried everything I found online, even on the official MySQL website.

My version of MySQL is 5.6.
Thanks

**Comment by electerious** [comment]
```sql
UPDATE `lychee_settings` SET `value` = '0' WHERE `key` = 'imagick' AND `value` = '0' LIMIT 1;
```

**Comment by zikamatej** [comment]
Thanks :)
