### ISSUE TITLE
Image Upload Issue

### ISSUE THREAD

**Issue by waseda** [electerious/Lychee#479]
I am testing this out as my picture management tool.  Installation and album creation is working fine.

But i realised the following:

I can upload images which was below 3MB. But any image above 3MB fails.  when trying to upload a image, i get 
![screenshot - 10_03_2016 02_51_17 pm](https://cloud.githubusercontent.com/assets/7609889/13657935/abff43d2-e6cf-11e5-9799-b0c981d0dc56.png)

So i check the console
![screenshot - 10_03_2016 02_53_51 pm](https://cloud.githubusercontent.com/assets/7609889/13657982/f3f2cda8-e6cf-11e5-8c15-112c02a21f0f.png)

What i can gather is that any image more then 3MB will fail.  I hope this can be looked at since all my images are hi-res and some are 9MB each.  So i cant be restricted to only less then 3MB.

I dont know if anyone else has had this issue.

PS: I am running this on WAMP, Windows 10, Chrome Browser

**Comment by waseda** [comment]
From plugins/check/

******************
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.0.9
DB Version:      030003
System:          WINNT
PHP Version:     5.5
MySQL Version:   50617
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         
*****************

**Comment by waseda** [comment]
My PHP:

file_uploads	On
max_file_uploads	20
upload_max_filesize	64M

**Comment by zikamatej** [comment]
It's there, in /plugins/check/

> Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

This is what the FAQ include:
```
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 20M
memory_limit = 256M
```

Set them like this in php.ini.

**Comment by waseda** [comment]
ok.. working now.

thanks  :)
