### ISSUE TITLE
Can't connect/import from dropbox

### ISSUE THREAD

**Issue by fadupla** [electerious/Lychee#485]
After entering the Dropbox Api Key and clicking on "Set Dropbox key", nothing happen on screen because there is a javascript error : 

`Uncaught TypeError: e is not a functiont.onload.t.onreadystatechange @ main.js:5`

file : _/dist/main.js_

**Comment by electerious** [comment]
Does this happen every time you try to set the dropbox key?

**Comment by electerious** [comment]
Can't reproduce the issue.

**Comment by aendrew** [comment]
I'm getting the same, followed by 

> main.js:6 Uncaught ReferenceError: params is not defined

Could it be the Dropbox API has changed?
