### ISSUE TITLE
Some comments about EXIF data

### ISSUE THREAD

**Issue by qligier** [electerious/Lychee#494]
Hello,

I would like to have more EXIF data shown for each photo. In my opinion, these data should be added:
- GPS lat/lon coordinates (could be used to put a minimap on the sidebar);
- Textual location (from IPTC data);
- The lens model.

In the "about" section, the second information to show up is the upload date, which is, I think, unmeaningful (or a lot less meaningful than the capture date). Would it be possible to put it in the last section or remove it?

We should also add an option to refresh the EXIF data stored from the file (it would allow updating EXIF data without reuploading the files).

What do you think?
Quentin

**Comment by electerious** [comment]
> GPS lat/lon coordinates

Would be useless without a map, which leads us to the question: Which map-service should we use?

> Textual location

Why not! Can you give an example?

> The lens model

Why not!

> In the "about" section, the second information to show up is the upload date, which is, I think, unmeaningful (or a lot less meaningful than the capture date). Would it be possible to put it in the last section or remove it?

I agree, but it makes sense where it is. It's not from the camera, so it doesn't belong to the "Camera" section. It's also not from the image itself. The last section is just about the sharing-properties.

> We should also add an option to refresh the EXIF data stored from the file (it would allow updating EXIF data without reuploading the files).

Wouldn't it makes more sense to let the user update the EXIF data stored in Lychee? Does someone actually change the EXIF data of his photos? Could also be problematic as [GD removes metadata](https://github.com/electerious/Lychee/issues/460) from the image when rotating a photo.

**Comment by qligier** [comment]
>> GPS lat/lon coordinates

> Would be useless without a map, which leads us to the question: Which map-service should we use?

I like [leaflet](http://leafletjs.com/) and [mapbox](https://www.mapbox.com/) (but the free plan requires an account and is limited to 50,000 map views / month).
There are plenty of map tiles services, as: [OpenStreetMaps](http://wiki.openstreetmap.org/wiki/Tiles), [Basemaps](https://cartodb.com/basemaps/), [stamen](http://maps.stamen.com/), ...
We could set the tile URL (i.e. `https://api.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png`) as a parameter and use OSM by default.

> Textual location

In Lightroom (and maybe other software), when you set GPS coordinates, the name of the place is added in IPTC metadata with reverse geocoding. 

>> In the "about" section, the second information to show up is the upload date, which is, I think, unmeaningful (or a lot less meaningful than the capture date). Would it be possible to put it in the last section or remove it?

> I agree, but it makes sense where it is. It's not from the camera, so it doesn't belong to the "Camera" section. It's also not from the image itself and the last section is just about the sharing-properties.

I find it very confusing so I'll try to find a good solution.

>>We should also add an option to refresh the EXIF data stored from the file (it would allow updating EXIF data without reuploading the files).

>Wouldn't it makes more sense to let the user update the EXIF data stored in Lychee? Does someone actually change the EXIF data of his photos? Could also be problematic as GD removes metadata from the image when rotating a photo.

Yep, that would be the best solution.
I had re-encoded all EXIF data to be "PHP-compatible" but this is not a common case.

**Comment by electerious** [comment]
> I like leaflet and mapbox (but the free plan requires an account and is limited to 50,000 map views / month).

leaflet looks like a good solution. Are there any limitations when using OSM? Do we need mapbox or is it just to make the map look better?

> In Lightroom (and maybe other software), when you set GPS coordinates, the name of the place is added in IPTC metadata with reverse geocoding.

PR welcome. You suggested to move the metadata into a different table, but I would add it to the photos table, too (for now).

> We should also add an option to refresh the EXIF data stored from the file (it would allow updating EXIF data without reuploading the files).

Here's a related discussion about writing data back to the images: https://github.com/electerious/Lychee/issues/44

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
