### ISSUE TITLE
Blank screen on fresh FreeBSD installation 

### ISSUE THREAD

**Issue by matunixe** [electerious/Lychee#498]
Hello,

I just setup a fresh Lychee installation on my FreeBSD 10.2 server.
As required I use the proper php extensions, proper nginx provided configuration and have setup the rightful access to the `www` user.

Take a look:
![](http://pix.toile-libre.org/upload/img/1458922754.png)
Full resolution [here](http://pix.toile-libre.org/upload/original/1458922754.png).

Obviously logs (php & nginx) tells me nothing other than access:
```
xx.xx.xxx.xxx - - [25/Mar/2016:17:17:48 +0100] "GET /dist/main.css HTTP/2.0" 304 119 "https://photo.mathiasblanchemanche.ch/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xx.xx.xxx.xxx - - [25/Mar/2016:17:17:48 +0100] "GET /dist/main.js HTTP/2.0" 304 120 "https://photo.mathiasblanchemanche.ch/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xx.xx.xxx.xxx - - [25/Mar/2016:17:17:48 +0100] "POST /php/api.php HTTP/2.0" 200 154 "https://photo.mathiasblanchemanche.ch/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
```

Thanks in advance for helping me.

**Comment by electerious** [comment]
I guess your PHP installation is broken or incorrectly configured. All PHP files are returning a blank page. At least the diagnostics must show some text: https://photo.mathiasblanchemanche.ch/plugins/check/index.php

**Comment by qligier** [comment]
Seems the same error as in #466, so it would be caused by nginx.

**Comment by matunixe** [comment]
As my collegue the diagnostics return a white blank page. I can assure you my php installation is OK and I don't think that's related to Nginx.

I use [this vhost file](https://github.com/electerious/Lychee/issues/466#issuecomment-201355804) under Debian 8.
