### ISSUE TITLE
[Question] Resetting password

### ISSUE THREAD

**Issue by SungMatt** [electerious/Lychee#500]
I have looked through all the issues pertaining to resetting passwords and I can't seem to figure which line to delete from the database.

Can you give a pointer as to what to edit? (I'll also put a note into the docs to help future users)

Thanks!

**Comment by electerious** [comment]
You can delete the whole `lychee_settings` table. Lychee will regenerate it and ask you to enter a new username and password.

**Comment by electerious** [comment]
Added a "How to reset username and password?" section to the FAQ.
