### ISSUE TITLE
Pictures with high resolution looks ugly ....

### ISSUE THREAD

**Issue by Droidwall** [electerious/Lychee#501]
Well, when i upload pictures with high resolution and see it through Lychee Interface the pictures looks ugly like you can see it here http://photo.dos-developers.com/#0/14593840738824

But when you open the file directly its more clear and everything which can be seen here : http://photo.dos-developers.com/uploads/big/206694900275cea8684e4f68a353c7a6.jpeg

Its like tooo sharp when seeing it through lychee ...

 I dont know how to say (sorry my first language is german lol ) 

I hope you got me :')

**Comment by qligier** [comment]
It seems that the will-change CSS property is messing with the image. Removing it solve the bug but the image is still too sharp during transitions, the rendering is optimized for speed and not for quality.

**Comment by Droidwall** [comment]
What do you think what can fix it? Because it look really ugly tooo sharp.

**Comment by electerious** [comment]
Fact: It depends on the browser and how it scales down the image. It looks much better in Safari and Firefox.

Chrome seems to do some magic when adding a composited layer around the image (that's what happens when using `will-change`). Removing `will-change` looks better in Chrome as @qligier said, but it still adds a composited layer during transitions. I wonder if there's another way to influence how the browser scales images down.

@Droidwall Fun fact: Ich stand ebenfalls an diesem Tag in Köln an der gleichen Stelle. Die Welt ist klein ;)

**Comment by electerious** [comment]
[image-rendering](http://devdocs.io/css/image-rendering) sounds like a solution, but makes no difference in Chrome as `optimizeQuality` isn't supported, yet.

**Comment by electerious** [comment]
- `will-change` cases Chrome to show rough edges all the time. Even during transitions.
- Removing `will-change` cases Chrome to show rough edges during transitions only.

- `will-change` hides all rough edges in Safari.
- Removing `will-change` cases Safari to show rough edges during transitions only.

**Comment by Droidwall** [comment]
Weired i tested it on Firefox an the Image is perfect lol. Hmm changing it to will-change: initial; seems to fix that problem on Google Chrome weiired what  google is doing O.o. It seems even Chrome on Android has also same problem but changing will-change transform to initial fixes the problem weired.....

@electerious Ja die welt ist klein ich mache immer dort bilder ;)

**Comment by Droidwall** [comment]
The only problem is while the animation is working the image looks ugly then 1 Second after its perfect..

**Comment by qligier** [comment]
The `initial` value has the same effect as deleting the property.

In [this article](https://dev.opera.com/articles/css-will-change-property/), it's recommended to add the property at the beginning of the animation and to remove it at the end with JS.
I think it's OK if the image looks more "crisp" during the animation, it helps the browser with processing load (it's a browser, not Photoshop). Looks like the best solution to me.
Let's hope the `optimizeQuality` value will be implemented (it's not standardized yet).

**Comment by Droidwall** [comment]
So i found a fix well its better to set the `will-change:transform;` After the animation which removes the ugly look...

**Comment by electerious** [comment]
> In this article, it's recommended to add the property at the beginning of the animation and to remove it at the end with JS.

I don't think that makes a difference. Chrome seems to create a composited layer during the animation automatically (even without `will-change: transform`). Removing the property after the animation would have the same effect.

The best solution is to remove `will-change: transform`. Looks a bit ugly during transitions, but that's better than having an ugly photo all the time.

**Comment by electerious** [comment]
Fixed. Will be part of the next release.
