### ISSUE TITLE
Error: Server Error or API not found

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [electerious/Lychee#508]
I have just upgraded to the 3.1 and after upgrading I am getting the error:
Error: Server Error or API not found
Screenshot: https://screenshot.felinetech.net/16/0412024114.jpg

At first i actually updated to 3.1 directly from 3.0.7. Then I again updated one-by-one to 3.0.8, 3.0.9 and then 3.1. But same result.

I looked into /php/error_log and I see lines:
PHP Fatal error:  Class 'Lychee\Modules\Config' not found in /home/xxxxx/public_html/php/index.php on line 49

**Comment by specktator** [comment]
:+1: The same ...

**Comment by electerious** [comment]
@dotcomUNDERGROUND Is there a file called 'Config.php' in `/home/xxxxx/public_html/php/Modules/`?

**Comment by dotcomUNDERGROUND** [comment]
@electerious Yes, it is there.
https://screenshot.felinetech.net/16/0412163004.jpg

**Comment by specktator** [comment]
@dotcomUNDERGROUND, Just to buy you (& @electerious ) some time: In the screenshot you posted you are in `[...]php/modules[...]` not in `php/Modules` as @electerious asked. Filenames are case sensitive. You should have two folders in your `php`  directory. One named `modules` and another named `Modules`.

**Comment by electerious** [comment]
That helps a lot!

@dotcomUNDERGROUND Make sure the folder is named `Modules` not `modules`.
@specktator It should only contain `Modules` as you can see here: https://github.com/electerious/Lychee/tree/master/php

**Comment by dotcomUNDERGROUND** [comment]
Thanks!

It looks like over 3.0.9 the folders were `modules` and `access`. And over 3.1 they got changed to to `Modiles` and `Access`. Anything else got changed in this way?

My FTP clients seems to be ignoring the case for the directories. 

Should I just remove everything other than `data` and `uploads` and then upload the latest as @specktator suggested?

**Comment by electerious** [comment]
Yes, you can delete anything expect `data` and `uploads`. `modules` and `access` are the only folders as far as I remember.

**Comment by qligier** [comment]
The safest is to delete everything other than `data` and `uploads` and reupload the new version. But uppercasing both directories should be enough.

**Comment by dotcomUNDERGROUND** [comment]
I went with removing the old files and uploading the latest. It's working fine now.

Thanks!

btw @electerious, may be you can consider a backward compatibility for the directory cap change issue?

**Comment by electerious** [comment]
It's completely backward compatible. You just updated incorrectly ;)

From the docs:

> 2. Replace all existing files, excluding `uploads/` and `data/`
