### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#511]
Hi, will Lychee be PHP 7 ready?

**Comment by qligier** [comment]
Hi, it should be PHP 7 compatible as it mainly uses PHP 5.6 features and syntax. I'll try it when I've some free time.

**Comment by ToeiRei** [comment]
I didn't see anything funny in the logs while running PHP 7 on my server. As far as I can see it's working

**Comment by qligier** [comment]
Thank you for your feedback!

**Comment by electerious** [comment]
Please let us know if you run into any problems. Lychee should work fine with PHP7 as far as I now.
