### ISSUE TITLE
SQL optimizations

### ISSUE THREAD

**Issue by qligier** [electerious/Lychee#513]
SQL. We like it :)
Here are some thoughts on the SQL design.

## Column datatype optimization

- `lychee_albums.id`: bigint to unsigned smallint (limit of 65'535, high enough I think (: )
- `lychee_albums.password`: varchar(100) to char(60) (Blowfish always outputs a 60 chars hash)
- `lychee_albums.sysstamp`: int to datetime or timestamp (that what they store)
- `lychee_photos.id`: bigint to unsigned mediumint (limit of 16'777'215), see comment after
- `lychee_photos.album`: varchar(30) to unsigned smallint to match `lychee_albums.id`
- `lychee_photos.checksum`: varchar(100) to char(40) (sha1_file outputs 40 hexadecimal char hashes)
- `lychee_photos.takestamp`: int to datetime or timestamp
- `lychee_photos.size`: varchar(30) to char(10)
- `lychee_photos.thumbUrl`: varchar(50) to char(37) (all filenames will be 36 or 37 chars long)

## Use index

You should really add indexes on field that are filtered or sorted in the queries:
- `lychee_photos.album` should definitively have one, as it's often used to select photos.
- `lychee_photos.public` and `lychee_photos.star` too if you want to filter on them with SQL. You could also get all photos and filter them with PHP, thus reducing the number of requests and their complexities (by example [here](https://github.com/electerious/Lychee/blob/e832ff0bf8f595bd541d92fdc0ebb75fb20ecebf/php/Modules/Album.php#L203)); not sure if it's worth it though.

## Photo IDs

The photo IDs should be regular, auto-incremented integers, stored in an unsigned mediumint column. If you want to also store the time of creation, let's add another datetime or timestamp column (it can be automatically filled at the creation of the row). Storing a large int in an oversized column messes up with the index.

## Tags
Tags should be in their own table, `lychee_photo_tags`, with columns `photo_id` (unsigned mediumint, index) and `tag` (varchar 30 should be enough). If so, column `lychee_photos.tags` should be dropped.

## Metadata
Metadata shoud also be in their own table, especially if we implement support for other formats. Table `lychee_photo_metadata`, with columns `photo_id` (unsigned mediumint, index), `metadata` (char 20 should be good) and `value` (varchar 50?).
If so, columns `width`, `height`, `iso`, `aperture`, `make`, `model`, `shutter` and `focal` from table `lychee_photos` should be dropped.

## Not so important optimizations

- `lychee_settings.key`: varchar(50) to varchar(20)
- `lychee_settings.value`: varchar(200) to varchar(60)
- `lychee_log.id`: int to unsigned mediumint
- `lychee_log.time`: int to datetime or timestamp
- `lychee_log.type`: varchar(11) to char(6)
- `lychee_log.line`: int to unsigned smallint

These tables are not really important, we only write in logs and we select everything in settings so datatypes and indexes are not really important as they won't change execution speed.

That's it for now. I'm not a MySQL expert so I could be wrong on some points but it seems

**Comment by electerious** [comment]
> Column datatype optimization

Agree to all of them. They could be updated using a [database-update-script](https://github.com/electerious/Lychee/tree/master/php/database). One question:

`lychee_albums.id` and `lychee_photos.id` store similar values since the last version of Lychee. Shouldn't they have the same  datatype?

> Use index

What's the benefit? Speed? Does it really matter?

> Tags

[Yes](https://github.com/electerious/Lychee/issues/409)

> Photo IDs

Works good as it is. Short ids are too easy to guess. Getting a hidden image is possible simply my incrementing the ID in the URL. Using the timestamp makes it at least a bit harder. Using it for the `timestamp` too is a bit wired but it works and I don't see any benefit from changing it. It would also break all existing links.

> Metadata

Agree! :) Could also be done with a database-update-script to stay backward compatible.

> Not so important optimizations

`lychee_log` => Yes
`lychee_settings` => No. The fields are bigger because the content is dynamic. It might contain another setting (one day) which uses the full field length.

**Comment by electerious** [comment]
I separated the changes I agree to into multiple issues. They could be part of an minor update which just addresses those database changes: https://github.com/electerious/Lychee/milestones/v3.1.2

**Comment by electerious** [comment]
> Use index

What's the benefit? Speed? Does it really matter?

> Photo IDs

Works good as it is. Short ids are too easy to guess. Getting a hidden image is possible simply my incrementing the ID in the URL. Using the timestamp makes it at least a bit harder. Using it for the `timestamp` too is a bit wired but it works and I don't see any benefit from changing it. It would also break all existing links.

**Comment by tribut** [comment]
> Getting a hidden image is possible simply my incrementing the ID in the URL. Using the timestamp makes it at least a bit harder.

Why not just use a standard autoincrement primary key as id and use the checksum for generating links (or a truncated version if you feel it is too long)? That should be secure and because you could use a different length would be easy to migrate to.
Alternatively, why not use the approach from [lychee-webroot](https://github.com/Bramas/lychee-webroot) and actually implement access control. This would make it possible to change an image back to private after it has been shared, enable shorter urls and eliminate the doubled effort needed to keep the "plugin" in sync (cf. https://github.com/Bramas/lychee-webroot/pull/2).

**Comment by tribut** [comment]
>> Use index
> What's the benefit? Speed? Does it really matter?

Yes, indices can improve speed by a lot. I just added an index on `lychee_photos.album` and it improved initial load time from ~25s to ~2s (800 Albums, 50k Photos).

**Comment by qligier** [comment]
Yes, indexes are the most important modifications in the list.

@tribut Thank you for the small benchmark. If it doesn't contain any sensitive data, would you mind sending me your database? I would try to benchmark the database structure modifications with a real set of data.

> Photo IDs

I think it's also important for performance. The IDs are used by MySQL to search and manage the photos so they should be MySQL-optimized.
The IDs can be guessed, yes. But I wouldn't call hard-to-guess-IDs secure because it's also easy to bruteforce them. Furthermore it's known that actual IDs are microtime of upload so it's not that hard to find them.
Also, the only way to get the filename of the photo is to ask the api, which should check the user permission before returning it. So knowing the ID is useless.
Last point, the photos can be accessed by anybody once their filename is known, so it's totally insecure by design. [lychee-webroot](/Bramas/lychee-webroot) corrects it but is also much more MySQL intensive (at least one MySQL request per file access, that could be too much for some servers).

**Comment by tribut** [comment]
>  If it doesn't contain any sensitive data, would you mind sending me your database? I would try to benchmark the database structure modifications with a real set of data.

Sorry, lots of private photos with suggestive names :)

**Comment by qligier** [comment]
Okay, no problem. I'll try to create not-so-stupid data with Faker.

**Comment by tribut** [comment]
> Also, the only way to get the filename of the photo is to ask the api, which should check the user permission before returning it. So knowing the ID is useless.

Oh, right. The files are all renamed to their checksum anyway. In that case having pseudo-random IDs seems entirely pointless to me. Can you explain @electerious?

**Comment by electerious** [comment]
> The IDs can be guessed, yes. But I wouldn't call hard-to-guess-IDs secure because it's also easy to bruteforce them. Furthermore it's known that actual IDs are microtime of upload so it's not that hard to find them. Also, the only way to get the filename of the photo is to ask the api, which should check the user permission before returning it. So knowing the ID is useless.

It's not secure and I never communicate it that way. But … guessing the microtime is still harder than simply increasing the ID by one. It's for people how are sharing photos as hidden. Access to the photo and direct URL is still only possible by a) guessing the direct link or b) when the photo is public.

**Comment by tribut** [comment]
> It's for people how are sharing photos as hidden

So why not use the checksum for the link? That could even be seen as somewhat secure and would only result in reduced complexity.

**Comment by electerious** [comment]
> So why not use the checksum for the link? That could even be seen as somewhat secure and would only result in reduced complexity.

Ugly URLs. But that's the only thing which speaks against checksums. It just hasn't been done this way. Lychee uses the timestamp for photos IDs since version one, where checksums weren't in use.

Just that I don't miss something: The mentioned performance boost is from adding indexes, not from changing the ID type, right? I agree that the ID type is a bit wired, but it works good as it is. I don't see a reason for changing it.

**Comment by qligier** [comment]
I'm testing some modifications and benchmarking them to see the performance boost we can get. We'll see which ones are effective.

**Comment by qligier** [comment]
These modifications have shown a good loading time decrease:
* Adding an index on `lychee_photos.albums` (incredibly effective);
* Adding an index on `lychee_photos.star`;
* Changing the type of `lychee_photos.[checksum,thumbUrl]`;
* Setting the integers columns to unsigned;
* Changing the type of `lychee_photos.album` to match `lychee_albums.id`;

Modifications that had no visible impact on loading time:
* Adding an index on `lychee_photos.public`;
* Changing the type of `lychee_photos.size`;
* Changing the type of `lychee_albums.password`;
* Changing the albums IDs to smallint auto-increment (I don't understand why, I would have expected a good improvement);

The queries of the four special albums are also quite slow with lot of photos (200k in my tests). It could be improved in that way:
* Instead of selecting all photos in each case, select only the three firsts thumbs (as done for others albums). Add another request to count the total number of photos in it.
* The recent photos query can be improved: 
```sql
WHERE id >> 13 >= unix_timestamp(DATE_SUB(NOW(), INTERVAL 1.2207 DAY)) LIMIT 3
# Instead of
WHERE LEFT(id, 10) >= unix_timestamp(DATE_SUB(NOW(), INTERVAL 1 DAY))
```

These changes allow the loading time of the main page to decrease from almost 10 min to ~1.5 sec with a database of 200k photos and 1k albums. In fact it's the albums that are slowing down Lychee, only a few of them can increase the loading time of a couple of seconds.

**Comment by electerious** [comment]
@qligier That sounds promising and I totally agree to those changes! :)

**Comment by electerious** [comment]
Add indexes: #531
Optimize SmartAlbum queries: #532
