### ISSUE TITLE
Importing KeyWords

### ISSUE THREAD

**Issue by barasher** [electerious/Lychee#514]
Hi,

I usually add some exif metadata to my pictures. This way, I'm able to retrieve all pictures on which someone appears or pictures taken during a specific event and so on. To do it, I use Lightroom inbuilt feature and it stores all the keywords in the **keyword** exif key.

I was very happy when I discovered Lychee and its "tag" attribute for each picture combined with a search field. Unfortunately, Lychee does not map this exif field to the picture's tag field in the database.

Would it be possible to do it automatically ?

Arnaud

**Comment by qligier** [comment]
Hey,
I've worked on the exif data import to extend it but it hasn't been pushed in a pull request yet. I'll do it, not sure when though.

**Comment by electerious** [comment]
The next version of Lychee imports tags. See https://github.com/electerious/Lychee/issues/309 for more details.
