### ISSUE TITLE
Suppressed fatal error exceptions are a hell for debugging

### ISSUE THREAD

**Issue by clarkwinkelmann** [electerious/Lychee#515]
### Detailed description of the problem

The suppressed exceptions in the database connection code (that have been introduced here: https://github.com/electerious/Lychee/commit/502f01ae6ce2923cd4c125a4d09e56ca6fc31fe9) does not only hide DB auth errors, it also hides the fatal `Class not found` exception thrown if the required php extension for `Mysqli` isn't installed on the system. This effectively removes all trace of the error in the system log and makes a hell of debugging that simple problem.

Additionally, the GUI gives absolutely no feedback to the user, as the fatal error prevents the request to return a textual error code to the front-end. Error is only visible from the console.
### Steps to reproduce the issue

I wanted to install latest Lychee version on a new server.
I booted a clean Ubuntu container, apt-get installed all the basics I usually need (apache2, mariadb-server, php5, php5-mysql). I then downloaded Lychee 3.1.0 (.tar.gz) directly on the server, extracted it and set folder permissions as asked in README. I typed the hostname of my container in Firefox and get prompted with the database configuration form. I created the user+database through MySQL Workbench and typed the values in the form. Clicking the next button did nothing at all.

I opened developer tools and saw an error in the console and in network tab. The `Config::create` endpoint was returning a 500 error with blank body. I looked in the apache/error.log and it was empty.

I then tried my best to decrypt how your routing works to find the `Config::create()` method. Placing dummy returns I saw that it was `Database::connect()` that was causing a problem. But putting it inside a `try{}catch(){}` block did not help. Still a blank response. Going further I found the actual `Database::connect()` code and saw the instruction `$connection = @new Mysqli($host, $user, $password);` [at line 84](https://github.com/electerious/Lychee/blob/v3.1.0/php/Modules/Database.php#L84). Removing the `@` allowed me to get the actual Exception: `PHP Fatal error:  Class 'Mysqli' not found in /var/www/photos/php/Modules/Database.php on line 84`.

So there was the problem. A [quick search on the web](http://stackoverflow.com/questions/666811/fatal-error-class-mysqli-not-found) gave me that the `php5-mysqlnd` Ubuntu package was required to get this class.

I saw that `mysqli` extension was required in INSTALL.md but until now everything I have ever installed on my server worked out of the box with the `php5-mysql` package. Maybe it is because they all used PDO and then the `Mysqli` object isn't required for these. Listing the debian/ubuntu packages required for Lychee somewhere could be a nice addition !
### Output of the diagnostics (Settings => Diagnostics)

I'm afraid all I get is the title:

```
Diagnostics
-----------
```

In Apache error.log I have `PHP Fatal error:  Call to undefined function Diagnostics\\gd_info() in /var/www/photos/plugins/Diagnostics/index.php on line 56`. I'm afraid I don't have time to debug that at the moment. Maybe it is another of these mysterious required php extensions that isn't installed on my system...
### Browser and system

Happened in a clean LXD container image of `Ubuntu trusty (14.04)`, `PHP 5.5.9`, `Lychee 3.1.0`. My browser is Firefox but it definitely is a server-side problem.

**Comment by electerious** [comment]
Thanks a lot for the detailed description of the problem!

I agree that suppressing a fatal error isn't a good idea. Throwing the error would be the better solution. However, I think there was a reason for adding the `@`. Not sure about this anymore :-/ Is there another situation where it might fail and getting the error via `$connection->connect_errno` isn't possible?

> In Apache error.log I have PHP Fatal error: Call to undefined function Diagnostics\\gd_info() in /var/www/photos/plugins/Diagnostics/index.php on line 56. I'm afraid I don't have time to debug that at the moment. Maybe it is another of these mysterious required php extensions that isn't installed on my system...

Found the problem: I'm checking if the `gd` extension is installed, but the script continues even when the extension is missing. That's why `gd_info()` fails.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
