### ISSUE TITLE
Browsing by dragging photo

### ISSUE THREAD

**Issue by Krzysiu** [electerious/Lychee#524]
[low prio] [enhancement] 

Another way of browsing photos. It's "smartphone'ish" way of browsing. It will be easier for me to explain by these points:

1. LMB (left mouse button) down
2. User moves mouse within some cage e.g.  more than 35% horizontally and less than 10% vertically move
3. LMB up
3. Check if cage conditions are met. If they are, prevent default action and change photo to next (left movement) or prev (right movement). If not, allow default browser action.

I have to admit I don't use smartphones and I don't know if that way is obvious, needed by users etc. I thought about that, because Lychee have very modern look and usage, so maybe users of Lychee are used to browsing photos like that on smartphones.

**Comment by electerious** [comment]
Thanks for the suggestion! Swiping in Lychee is possible on touch-screen devices, but it's not planned to support dragging via cursor.
