### ISSUE TITLE
install of 3.0.6

### ISSUE THREAD

**Issue by redtoadmedia** [electerious/Lychee#525]
### Detailed description of the problem

upload fails with a 500 error. we have php su so permissions are 755 but should work. admin user/pass is made. no errors in php logs (which is really weird)

we don't have exif activated is it required????????? is that my issue? I'm going to try to activate it but wanted to know if it was possible to run it without it. 

### Steps to reproduce the issue

try to upload a photo, upload failed check console

console says:

description: "Upload failed. Server returned the status code 500!"
params: XMLHttpRequest {onabort: null, onerror: null, onload: function, onloadend: null, onloadstart: null, …}
response: ""

error is on api.php when I go there it says 
Error: Called function not found!

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey
Warning: You may experience problems with the Dropbox- and URL-Import. Edit your php.ini and set allow_url_fopen to 1.
Error: PHP exif extension not activated

System Information
------------------
Lychee Version:  3.0.6
DB Version:      030003
System:          Linux
PHP Version:     5.4
MySQL Version:   50548
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         

### Browser and system

Apache version2.2.31
MySQL version5.5.48-cll

PHP version5.4.45

on safari 

there is fastcgi and I have modified the php.ini

**Comment by electerious** [comment]
Yes, the `exif` extension is required.

**Comment by redtoadmedia** [comment]
ok thank you.
