### ISSUE TITLE
Column datatype optimization

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#526]
- `lychee_albums.id`: bigint to unsigned smallint (limit of 65'535, high enough I think (: )
- `lychee_albums.password`: varchar(100) to char(60) (Blowfish always outputs a 60 chars hash)
- `lychee_albums.sysstamp`: int to datetime or timestamp (that what they store)
- `lychee_photos.id`: bigint to unsigned mediumint (limit of 16'777'215), see comment after
- `lychee_photos.album`: varchar(30) to unsigned smallint to match `lychee_albums.id`
- `lychee_photos.checksum`: varchar(100) to char(40) (sha1_file outputs 40 hexadecimal char hashes)
- `lychee_photos.takestamp`: int to datetime or timestamp
- `lychee_photos.size`: varchar(30) to char(10)
- `lychee_photos.thumbUrl`: varchar(50) to char(37) (all filenames will be 36 or 37 chars long)

by @qligier from #513 
- `lychee_settings.key`: varchar(50) to varchar(20)
- `lychee_settings.value`: varchar(200) to varchar(60)
- `lychee_log.id`: int to unsigned mediumint
- `lychee_log.time`: int to datetime or timestamp
- `lychee_log.type`: varchar(11) to char(6)
- `lychee_log.line`: int to unsigned smallint

by @qligier from #513

**Comment by electerious** [comment]
Agree to all of them. They could be updated using a [database-update-script](https://github.com/electerious/Lychee/tree/master/php/database). One question:

`lychee_albums.id` and `lychee_photos.id` store similar values since the last version of Lychee. Shouldn't they have the same  datatype?

**Comment by electerious** [comment]
`lychee_log` => Yes
`lychee_settings` => No. The fields are bigger because the content is dynamic. It might contain another setting (one day) which uses the full field length.

**Comment by qligier** [comment]
> `lychee_albums.id` and `lychee_photos.id` store similar values since the last version of Lychee. Shouldn't they have the same datatype?

Why should they? We expect to have much more photos than albums, the datatype must be chosen accordingly.

> `lychee_settings` => No.

Okay. That was more for the design, I don't expect any change of the performances for this; that's why I labelled them as non-important.

**Comment by electerious** [comment]
> Why should they? We expect to have much more photos than albums, the datatype must be chosen accordingly.

They are both using the micro-timestamp as the ID. The length doesn't depend on the amount of albums/photos.

**Comment by qligier** [comment]
True, I was watching the older version database. [My response](513#issuecomment-213997372) also applies to album IDs.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
