### ISSUE TITLE
Metadata in own table

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#527]
Metadata shoud also be in their own table, especially if we implement support for other formats. Table `lychee_photo_metadata`, with columns `photo_id` (unsigned mediumint, index), `metadata` (char 20 should be good) and `value` (varchar 50?).
If so, columns `width`, `height`, `iso`, `aperture`, `make`, `model`, `shutter` and `focal` from table `lychee_photos` should be dropped.

by @qligier from #513

**Comment by electerious** [comment]
Agree! :) Could also be done with a database-update-script to stay backward compatible.

**Comment by qligier** [comment]
Yes, backward compatibility is possible and should be preserved.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
