### ISSUE TITLE
Trigger the import from server function with a script

### ISSUE THREAD

**Issue by zobra00** [electerious/Lychee#528]
Is it possible to call the "import from server" function in some way from a script on the server to automate the import of photos into lychee?

My server automatically imports images from sd cards inserted, but I have to manage duplicates, file name conflicts etc. with a script. Basically everything gets processed twice while lychee could do it better the first time. 

I have been using lycheesync, but I would like to take advantage of the import and management system of lychee and be able to keep lychee up to date without worrying about breaking the plugins as lycheesync directly writes the database.

**Comment by electerious** [comment]
There's currently no way to trigger the import with a script, but it should be possible to use the existing code/files to add this feature.

**Comment by zobra00** [comment]
Thanks for the reply. I figured that was the case. When I have some free time again in a couple of weeks I will look into trying this out. I still have a whole lot to learn about PHP and web-related programming, my programming is mostly on tiny embedded systems.

I'm thinking about approaching it by creating an alternate index.php that can interpret command line arguments and call the right modules with those arguments.

Let me know if I'm on the right track. But yes, low low priority. You're doing a great job on Lychee.

**Comment by iamsebastian** [comment]
As long as your php session is valid, you can "execute" the import via cURL.

```sh
curl \
'http://lychee.example.com/php/index.php' \
-H 'Cookie: PHPSESSID=YourCookieSessionID' \
--data 'function=Import%3A%3Aserver&albumID=YourAlbumID&path=%2Fvar%2Fwww%2Flychee%2Fuploads%2Fimport%2F'
```

Take note about the url-encoded data-string. Calling cURL with `--data-urlencode` does not seems to be encoding the "Import::server" function-string correctly, so you are in need to urlencode the string manually or just take one of this approaches: http://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command

With this *curl-snippet*, you can configure a cronjob, or a *device-attached-event*.

**Comment by zobra00** [comment]
I didn't think of doing it that way, and didn't really know about cURL either. :) 
That looks like a simple option, all I have to do is set the `session.gc_maxlifetime` parameter to a few years and call the cURL snippet on localhost. 
I will try it out soon and report back, Thanks.

**Comment by sebastien4** [comment]
Any chance to add this feature?

**Comment by zobra00** [comment]
I have been using the curl solution by iamsebastian. It works perfectly apart from timeouts after many hours and 20.000+ pictures. 

Have a look at the discussion in issue #638 too, it's somewhat related.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
