### ISSUE TITLE
Add indexes to SQL fields

### ISSUE THREAD

**Issue by electerious** [electerious/Lychee#531]
You should really add indexes on field that are filtered or sorted in the queries:
- `lychee_photos.album` should definitively have one, as it's often used to select photos.
- `lychee_photos.public` and `lychee_photos.star` too if you want to filter on them with SQL. You could also get all photos and filter them with PHP, thus reducing the number of requests and their complexities (by example [here](https://github.com/electerious/Lychee/blob/e832ff0bf8f595bd541d92fdc0ebb75fb20ecebf/php/Modules/Album.php#L203)); not sure if it's worth it though.

Planned effective changes after some tests:

These modifications have shown a good loading time decrease:
* Adding an index on `lychee_photos.albums` (incredibly effective);
* Adding an index on `lychee_photos.star`;
* Changing the type of `lychee_photos.[checksum,thumbUrl]`;
* Setting the integers columns to unsigned;
* Changing the type of `lychee_photos.album` to match `lychee_albums.id`;

by @qligier from #513

**Comment by electerious** [comment]
@qligier We're done here, right?

**Comment by qligier** [comment]
We've done what was useful and could easily be done. So yes, we can close this.
