### ISSUE TITLE
Can't upload photos, diagnostics page is blank

### ISSUE THREAD

**Issue by vibbizz** [electerious/Lychee#536]
I can not upload new photos onto my Ubuntu Lychee installation. All attempts (from multiple browsers and clients) result in the error "server returned an unknown response. Please take a look at the console of your browser for further details". Resulting console error is:

http://<<server address redacted>>/lychee/php/index.php Failed to load resource: the server responded with a status of 500 (Internal Server Error):

main.js:5 Objectdescription: "Upload failed. Server returned an unkown error!"params: XMLHttpRequestonabort: nullonerror: nullonload: ()onloadend: nullonloadstart: nullonprogress: nullonreadystatechange: nullontimeout: nullreadyState: 4response: ""responseText: ""responseType: ""responseURL: "http://arnoldandfranklin.zapto.org/lychee/php/index.php"responseXML: nullstatus: 500statusText: "Internal Server Error"timeout: 0upload: XMLHttpRequestUploadwithCredentials: false__proto__: XMLHttpRequestresponse: ""__proto__: Objectlychee.error @ main.js:5

When I load the Diagnostics page, it is blank save for the header:

Diagnostics
-----------

Browser: Safari and Chrome, Mac OS X 10.11.4
Lychee install on Ubuntu 16.04 server, PHP 7.0.4-7

**Comment by electerious** [comment]
Please take a look at the PHP error log. It's properly because of a broken/incorrect server configuration.

**Comment by vibbizz** [comment]
Legend! Thank you, php-gd was not properly configured. Warning to anyone who thinks a basic Ubuntu server installation will just be properly configured out of the box...
