### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by icehawk-de** [electerious/Lychee#540]
Is it possible to update images? I have a lot of pictures imported with 800x600 pixels. I want to update these images (time after time) to a bigger size. 

Is this possible? How?

**Comment by electerious** [comment]
It's current not possible, but planned: https://github.com/electerious/Lychee/issues/268

Not recommended, but possible: If you really want to update photos you can do so by replacing the photos in `/uploads`. You might also adjust the photo size in the database.
