### ISSUE TITLE
Adding some Links?

### ISSUE THREAD

**Issue by WulfmanGer** [electerious/Lychee#541]
Hi

i've looked @ index.html and view.php but i don't find a solution how to add some links. 

I am a User from Germany and we have, in some cases, the problem that we need (by law) a legal notice and privacy policy. I have both on separate Websites - no custom-page in lychee needed - i need only an Link to this sites (and to some other projects ;) ) ... is this possible? (footer, header, menu ...)

Regards
Wulfman

**Comment by electerious** [comment]
There's no special place reserved for those links. You can add a footer (HTML) if you want, but you need to style it by yourself (CSS). I can't provide any help for customization.

**Comment by suntorytimed** [comment]
@WulfmanGer if you are still interested in a solution, I have put a simple <a href="Impressum URL" style="color:white">Impressum</a> into all header definitions in the index.html. Doesn't look very nice, but it gets the job done (photography.hibiki.eu).
