### ISSUE TITLE
Password asked multiple times

### ISSUE THREAD

**Issue by mlapaglia** [electerious/Lychee#542]
### Detailed description of the problem

Password prompt comes up when clicking on every image in an album.
### Steps to reproduce the issue

When navigating the root of the site and clicking on a password protected album, a prompt comes up for the password to be entered. In Chrome, after entering the album, every subsequent click on images brings up the same password prompt. I also observe that the image still loads in the background with the password lightbox above it. This issue also happens in incognito mode as a guest.

![image](https://cloud.githubusercontent.com/assets/4184746/15123967/250c7274-15f4-11e6-95c1-c10ab71dbce1.png)
## Diagnostics

Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!
## System Information

Lychee Version:  3.1.1
DB Version:      030100
System:          Linux
PHP Version:     5.6
MySQL Version:   50549
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1-dev
Plugins:         
### Browser and system

Windows 10, latest Chrome

**Comment by electerious** [comment]
Thanks for the report! I can confirm the issue. Seems to be a problem in Chrome only.

**Comment by electerious** [comment]
I took a look at it, but I'm still not sure what's causing the issue :-/

**Comment by givre** [comment]
Still have this issue :/

**Comment by mfalaize** [comment]
Still have the issue in 3.1.6 on Firefox 54.0 (64 bits) on ubuntu. It works on Epiphany browser and Chromium 59.0.3071.109 (also on ubuntu).

**Comment by ffasulo** [comment]
+1

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
