### ISSUE TITLE
Photo type not supported for any image.

### ISSUE THREAD

**Issue by Javiervgn** [electerious/Lychee#544]
No mater what image I try to upload it always gives me the same error.

2016-05-11 11:29:28 - error - Lychee\Modules\Photo::add (137) 	- Photo type not supported

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.1
DB Version:      030100
System:          WINNT
PHP Version:     5.6
MySQL Version:   50544
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by electerious** [comment]
Are there additional details in the PHP error log?

**Comment by Javiervgn** [comment]
Nothing on the PHP error log.

**Comment by electerious** [comment]
That makes it hard to debug :-/ Can you attach one of the images or send me the URL and login of your Lychee installation (via mail)?

Here's the line causing the output: https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L135 Feel free to take a closer look at it if you can.

**Comment by Javiervgn** [comment]
What is the validation for photo type to begin with? I mean, I understand photo format but I'm not sure what you want to verify with photo type.

**Comment by qligier** [comment]
On Windows server, [it seems](http://stackoverflow.com/a/20409917/4990350) that the _mbstring_ extension is needed by and should be loaded before GD in your php.ini file.

**Comment by electerious** [comment]
@Javiervgn Any updates for us?

**Comment by electerious** [comment]
Closing this issue as I'm not able to reproduce the problem. Please try the advise from @qligier and let us know when it's not working.
