### ISSUE TITLE
"Wrong"-URLs in view.php (http vs. https)

### ISSUE THREAD

**Issue by WulfmanGer** [electerious/Lychee#546]
Hi

view.php -> Meta-Tags for OGP etc.:

getGraphHeader.php
$parseUrl = parse_url('http://'  <- only http:// - what happend with https? My Pages uses only https ... ok 301-Redirect ... It would be nice if here automatically selects the correct protocol. I've changed this manualy - until next update ... ;)

Thx
Wulfman

**Comment by electerious** [comment]
Good point! PR welcome.

**Comment by mm2knet** [comment]
if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {
    // SSL connection
}
This should work. (Source: http://stackoverflow.com/questions/7304182/detecting-ssl-with-php )

**Comment by qligier** [comment]
Or you could just delete the scheme from the url (aka protocol-relative url):
```php
$url      = '//' . $parseUrl['host'] . $parseUrl['path'] . '?' . $parseUrl['query'];
$picture  = '//' . $parseUrl['host'] . $parseUrl['path'] . '/../uploads/' . $dir . '/' . $row->url;
```
https://github.com/electerious/Lychee/blob/master/php/helpers/getGraphHeader.php#L27-28

**Comment by electerious** [comment]
Good idea. Thanks for the tip! The next version of Lychee uses protocol-relative URLs.
