### ISSUE TITLE
Semi-Random Ordering Using Upload-Time

### ISSUE THREAD

**Issue by tillschaefer** [electerious/Lychee#548]
**Description**
The upload time sorting of images does not work as expected when uploading many files at once. When selecting multiple files during import one would expect, that the images are ordered the same way the files are ordered on file system, since the files gets uploaded in the same order. However, they are in a slightly random order. 

**Example:** 
Lets say the images are named 1.jpg to 10.jpg. Now i upload them, and i get the order 1,3,2,5,4,6,7,9,8,10.

**Analysis**
I guess the ordering is based on the upload time stamp from PHP. Since the files are uploaded in parallel, some files overtake their predecessors wrt their upload completion time (e.g. because they are smaller or just because some random network effects). 

**Diagnostics**
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

**System Information**
Lychee Version:  3.1.1
DB Version:      030100
System:          Gentoo Linux
PHP Version:     5.6
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:    

**Client**
Browser: Firefox 45.1 ESR
System: Gentoo Linux

**Comment by qligier** [comment]
One solution would be to send the timestamp in the AJAX request instead of using the processing timestamp, the order would be preserved in this case.

**Comment by electerious** [comment]
@qligier That won't work as the timestamp will be used for the id. We can't trust the client to send a correct timestamp. Is there a way to determine when the request has started (server-side)?

**Comment by qligier** [comment]
Not without a special configuration of the web server. Apache (or Nginx) knows when the request starts but PHP can't (its processing starts when the upload is complete).
The uploader receives the id at the end of the request, I don't see any good reason not to let him send it. You simply need to check that it's a 14-digits number not currently used and you're good to go. I can't see any security flaw with that.

**Comment by tillschaefer** [comment]
The client side time stamps may still result in weird sortings whenever the time is configured wrong on the client side (e.g. if someone is uploading from a machine which is one hour late and than switches to another machine with correct time), or am i wrong?

Is it possible to submit an ordering with an upload request? I.e. all files from a multi-file-upload get the same upload time, but additionally an ordering (such as consecutive numbers) is submitted from the client.

**Comment by electerious** [comment]
> The client side time stamps may still result in weird sortings whenever the time is configured wrong on the client side (e.g. if someone is uploading from a machine which is one hour late and than switches to another machine with correct time), or am i wrong?

Exactly.

> Is it possible to submit an ordering with an upload request? I.e. all files from a multi-file-upload get the same upload time, but additionally an ordering (such as consecutive numbers) is submitted from the client.

Not really. Each photo upload is a separated request. We can't correct the order on the server because they don't know anything about each other.

**Comment by tillschaefer** [comment]
maybe this is a bit bloated, but if the client generates an UUID for a parallel upload and submits this UUID together with an sequence id (ordering) the server should be able to reconstruct the correct order.

Nevertheless, i am not a web-developer and maybe there is a better "more standard" way to do this. We shouldn't be the first people having this problem.

**Comment by electerious** [comment]
It's definitely possible to find a solution, but I doubt that it's worth the effort. I would rather use the time to add [custom sorting](https://github.com/electerious/Lychee/issues/192).

However, I'm still open for ideas. Maybe there's an easy and reliable way to solve the issue.

**Comment by tillschaefer** [comment]
I do not want to be to pushy, but i think that the ordering the files have on the file system is maybe the most used/natural one. Ordering using the description of a picture is a workaround, but it involves fiddling with the meta data of an image, which is not trivial for regular users.

**Comment by jaywilliams** [comment]
This is something I've been experiencing as well. Perhaps the simplest fix would be to disable parallel uploading, and only upload one file at a time.

Having files ordered by filename is something I use quite often.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
