### ISSUE TITLE
Feature Request: Tool to find duplicates

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [electerious/Lychee#550]
It will be great if you add a tool to detect duplicate photos (files) and option to remove duplicates.

Would be very helpful to clean up the duplicate uploads caused by issue #433 .

**Comment by electerious** [comment]
It's not planned to build this functionality into Lychee, but you could find and delete the duplicates in the database using the checksum of the photos. Keeping one image per checksum should do the job as Lychee uses the same file for equal photos.
