### ISSUE TITLE
[Feature Request] Anonymous picture Upload

### ISSUE THREAD

**Issue by mm2knet** [electerious/Lychee#551]
The Idea is the following:

You are on a party or a wedding and the users are taking pictures with their smart phones. There is Wifi available and the users can upload their pictures to a Lychee Installation, where everyone can see the pictures the others took.
As the album has no Access control it shouldn't be listed and only available to those with the URL. But that shouldn't be a problem in times with whatsapp and group chats ;) 

The change that needs to done is allowing anonymous users upload pictures to an album specified by the admin.

Another useful feature would be a slide show that goes through an album and shows the pictures in it - with an auto update, so that newly uploaded pictures also show up.This would be perfect for showing the party pictures on a projector.

**Comment by ET-Bent** [comment]
How about just setting up an account with the username `public` and password `public` for example. You once tell the guests the login data together with the url and let them start uploading throughout the day / night.

After the event, you just change the password to something safe.

Another option would be combining the `Import from Server` option with a public ftp server + cronjob which runs the necessary script which I'd consider harder for the average user.

![auswahl_053](https://cloud.githubusercontent.com/assets/5788982/15763161/3cef8ee4-2922-11e6-8f0d-ffd29f240f0e.png)

**Comment by aplsms** [comment]
it would be great to have LR plugin and/or open API for import data.

**Comment by mm2knet** [comment]
The web interface of Lychee works very well with smartphones, so the ftp option is not really an option. but I will do a quick hack and remove the logon.. As the page will be hosted on a raspberry pi internal this shouldn't be a problem.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
