### ISSUE TITLE
[Feature request] Multi-user

### ISSUE THREAD

**Issue by russellhoff** [electerious/Lychee#552]
Thanks for your work, this application is awesome.

I would suggest a few things:

- It seems that this application is intended for single-user. It would be fantastic if it would be multi-user.

- When you add local photos, I have read in some readme over here that the files are deleted, why?

Thank you so much!

**Comment by electerious** [comment]
Hi @russellhoff 

> It seems that this application is intended for single-user. It would be fantastic if it would be multi-user.

https://github.com/electerious/Lychee/issues/132

> When you add local photos, I have read in some readme over here that the files are deleted, why?

Are you talking about the "Import from Server"? If so, yes, Lychee deletes the successfully imported photos when it has the rights to do so.

**Comment by russellhoff** [comment]
So photos are actually stored in the database?

**Comment by electerious** [comment]
@russellhoff Lychee stores photos in the `data/` folder.
