### ISSUE TITLE
Why does Lychee not recognize some pictures "captured" date?

### ISSUE THREAD

**Issue by omichalek** [electerious/Lychee#553]
Some pictures do not order correctly in my albums which are ordered by date taken.
It happened in the past already, but I would usually fix the issue by deleting the photo and reuploading it, that suddenly does not work.

- The photos in question might have been edited by Adobe Bridge (starred or rejected), unlike the rest of the photos, which are usually managed only in Shotwell (Photos in Elementary OS). I am not certain this is the common denominator, however.

##### Few observations:
- At least one photo has wrong "captured" date, possibly corresponding to the time it was tagged or starred (little hard to guess since Lychee shows only date, no time)
- When the date is wrong the Focal Length is as well (0 mm), but camera model, shutter speed, aperture and ISO seem to work.
- Few photos show no date captured at all (and are then sorted at the end of the album)
- The date taken of all above mentioned photos seems to be recognized in Shotwell (which is why I had no reason to panic so far)

### Questions
- Does the software I use corrupt metadata of my photos? Should I never touch them with Adobe Bridge again? Is Shotwell a safe choice for tagging/starring/rejecting?
- Can I make Lychee show the hour:minute:second when the image was taken, preferably after the date (preferably the whole string in ISO format for clarity)?

- (Could someone please point me to the "right" CL program to use to diagnose the metadata of my photos so that I can investigate further when I have time to do that?)

Thank you for any help!

##### Output of the diagnostics (Settings => Diagnostics)
Lychee Version:  3.1.1
DB Version:      030100
System:          Linux
PHP Version:     5.6
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1-dev
Plugins:

**Comment by electerious** [comment]
Thanks for the detailed report. Helps a lot! :)

> Does the software I use corrupt metadata of my photos? Should I never touch them with Adobe Bridge again? Is Shotwell a safe choice for tagging/starring/rejecting?

I guess that Shotwell/AdobeBridge stores some metadata in a different way/format and Lychee is just not able to parse it. Might be an issue of Shotwell, Adobe Bridge or Lychee. Lets see…

> Can I make Lychee show the hour:minute:second when the image was taken, preferably after the date (preferably the whole string in ISO format for clarity)?

Different topic. Could you open a separate issue for that?

> (Could someone please point me to the "right" CL program to use to diagnose the metadata of my photos so that I can investigate further when I have time to do that?)

There's a tool called [ExifTool](http://owl.phy.queensu.ca/~phil/exiftool/examples.html) which does exactly what we're looking for. Could you attach some of the photos that aren't working and one of the photos that does. If you want, you can also send me the photos via [mail](https://github.com/electerious) or just the output of ExifTool. Thanks!

**Comment by qligier** [comment]
Having the file would be the easiest way to understand what happens because two parts could fail: the extraction of the EXIF data and its processing. The first part is done by PHP and [it has a lot of bugs](https://bugs.php.net/search.php?cmd=display&search_for=exif&x=0&y=0); the second part is done by Lychee in a simple way.
The result of ExifTool would only be useful if the second part is the deficient one, as it has a more complete extraction method than PHP.

Some softwares store data in external files (as XMP files) to preserve original images (and Adobe Bridge does it), so be sure to include all data when you export the file. But both Shotwell and Adobe Bridge support EXIF headers so you should be fine using them.

**Comment by omichalek** [comment]
I'm sorry for the delay, attached is one photo that lacks the _captured_ field altogether
![493ae64d4ed59011cd13b7f8e1d3b2d5](https://cloud.githubusercontent.com/assets/5930013/16052973/07008c54-3267-11e6-9bc6-54493073c26c.JPG)

BTW, I just noticed that the file is larger than the photo I uploaded, why is that?

**Comment by omichalek** [comment]
and this one has wrong captured date (and "0 mm" focal length)
![ab231f020b75774d4099574b70495911](https://cloud.githubusercontent.com/assets/5930013/16053175/ef0f3fe0-3267-11e6-8c1d-600d9f15c57e.JPG)

**Comment by qligier** [comment]
It seems that github has modified your pictures, they have no exif data.

**Comment by electerious** [comment]
As @qligier said, the exif data is missing. Could you upload the photos somewhere else? Not sure if github removed the data or the data was already missing before.

**Comment by omichalek** [comment]
Is this better?
[wrong-date.zip](https://github.com/electerious/Lychee/files/333716/wrong-date.zip)
[no-date.zip](https://github.com/electerious/Lychee/files/333717/no-date.zip)

**Comment by electerious** [comment]
There're no EXIF or IPTC data in the photos. That's why Lychee can't show the information.

**Comment by omichalek** [comment]
Well it did have metadata before I uploaded these images.
I will find the pictures and readd them to my up-to-date lychee to see if it is works now
