### ISSUE TITLE
Erroneous display of portrait picture in a "narrow" window

### ISSUE THREAD

**Issue by nerbrume** [electerious/Lychee#555]
Hello,

Portrait images, when displayed in a "narrow" window, does not take all space available.

See screenshots for an hopefully better description:
"Narrow window" (the browser was resized to only take the right-half of my screen)
![erroneous-portrait](https://cloud.githubusercontent.com/assets/2480350/15774321/0d876fa0-297c-11e6-8ef7-95bb7c68319b.jpg)
(I would expect the picture to take the full height of the window)
The same picture, with my browser in full screen:
![correct-landscape](https://cloud.githubusercontent.com/assets/2480350/15774320/0d85fef4-297c-11e6-8c9f-46a5b4e445d1.jpg)

This was tested on Firefox and Chromium on desktop, where I don't think this is such a big issue (people usually have their browser in full-screen), and on Firefox on Android, for which it bothers me much more : I usually use my phone vertically :)

Feel free to ask if anything is unclear.

**Comment by qligier** [comment]
The problem is caused by the srcset attribute of the image: because the screen isn't so wide, it loads the resized version of the image (but smaller than the screen) and doesn't upscale it when shown.

The height and width of the thumbnails should be given by the server to correctly calculate the breakpoint.

**Comment by nerbrume** [comment]
The browser indeed load the resized "medium" image (its size is 717x1080, while the original is something like 4500x3000), but this is the case even for the "wide", second screenshot (look at the black on the bottom : the height of the image is less than my screen's height of 1200). There is no upscaling at play here, and I don't expect one (or should I ?)

**Comment by qligier** [comment]
Let me correct myself: when I talk about the screen, I mean the browser window. As you resize your window, the loaded image changes.

And you should of course not expect upscaling.

**Comment by electerious** [comment]
The browser loads the best photo for the current size, screen resolution and network. You see the photos centered in the middle as Lychee does not upscale them when they are too small. Reloading the browser or switching to the next image should auto-fix the problem as the browser now uses it's updated size.
