### ISSUE TITLE
Reducing medium-sized images

### ISSUE THREAD

**Issue by nerbrume** [electerious/Lychee#556]
Hello,

I'm using lychee on my self-hosted machine, at home, with a "typical" DSL upload of 1Mb/s (at least in France).
From an admittedly small subset of images, I get an average of more than 300kB for the medium images, meaning that my users need to wait something like 3s between images, which is a bit too much to my taste :)

I was able to reduce this by simply modifying Photo.php, adding the two following lines in the Imagick section, resulting in images around 100kB : 
`$medium->stripImage();
$medium->setImageCompressionQuality(70);`
Stripping the meta-data luckily doesn't break lychee "About" section, as the infos are fetched from the DB. The only thing we are losing is the ICC profile. The compression of 70 was quickly chosen, but on ~1920x1080 pictures, on a 24" display, I don't see the obvious compression differences without pixel-peeping (I don't have good eyes)

I have several questions / propositions :
- Would you consider a global "low-bandwidth" setting ? If so, I can volunteer to implement it more properly than my hack (hoping GD offers meta-data manipulation), and I guess that the quality and inclusion of the ICC profile would then be subject to discussion.
- Regardless of this, I think that _always_ stripping the meta-data is a good idea. It's often just a few kB saved, but it's better than nothing.

**Comment by qligier** [comment]
Stripping the metadata and reducing the quality is definitely a good idea. A quality of 70 or 75 is good enough for a thumbnail (see [this article on medium](https://medium.com/@duhroach/reducing-jpg-file-size-e5b27df3257c#.onf3pifmy) for an estimate of the quality used by some major companies).

> always stripping the meta-data is a good idea

Except in the case of the original image I think.

> The only thing we are losing is the ICC profile.

I think that losing the color profile isn't too bad, as a lot of screens today aren't calibrated and can have large delta E.

**Comment by electerious** [comment]
Totally agree!

> ->stripImage();

Should be implemented for thumbs and medium-photos.

> ->setImageCompressionQuality(70)

Should be implemented for medium-photos, but I would use 90. 

---

Someone in the PHP doc comments has a good point:

> Please note that striping off the exif information without handling the orientation information available in the exif will lead to wrong orientation of the image

We should check if this makes any trouble, but I don't think so as we are fixing the orientation in the `adjustFile()` function.

---

We could do a much better job adjusting the photo with Imagick: http://stackoverflow.com/a/31943940/207704
I'm going to implement this solution.

---

I realized Lychee creates a medium-sized photo no matter what format the photo has. This could turn huge animated GIFs into non-animated GIFs. As animated GIFs are usually small, this hasn't been a problem, yet.

**Comment by electerious** [comment]
I [implemented](https://github.com/recurser/exif-orientation-examples) the improved orientation handling. Could someone with Imagick installed take a look at it? My installation is currently not working correctly. Here're images to test: https://github.com/recurser/exif-orientation-examples

**Comment by nerbrume** [comment]
I had some time to test the orientation using the develop branch, every image from the examples you linked is displaying fine :). On the master branch, only the examples 1, 3 and 8 were correct.

> Except in the case of the original image.

> Should be implemented for thumbs and medium-photos.

Of course, stripping meta-data from the original image is nonsense. I however didn't though about the thumbnails, you're totally right.

> Should be implemented for medium-photos, but I would use 90. 

IMHO, 75 is good enough, both from my experience (I'm not a hardcore photographer, but I archive my processed RAWs in jpeg at this level), and from the article @qligier mentioned.
In any case, for my peculiar needs, I'll probably lower it to 60 or 65, but that's my problem.

Are you interested in a pull request (I didn't code anything yet), or are you faster doing it yourself ?

**Comment by electerious** [comment]
> IMHO, 75 is good enough

There's a comment on StackOverflow which perfectly reflects my experience with JPEGs.

> Use 90, or preferably 95. In my experience, the size gain when using anything under 90 is in most cases no longer beneficial in relation to perceivable quality loss[…]

It always depends on the image, but I will go with 90 as it might be the best for most images.

> Are you interested in a pull request (I didn't code anything yet), or are you faster doing it yourself ?

Highly welcome! :) Please use the `develop` branch for the PR.

**Comment by electerious** [comment]
Implemented! Please let me know if everything works.

**Comment by nerbrume** [comment]
I went to do that this morning, you beat me to it !
As for GD, there is no medium-size generation ?
Anyway, thanks !
(I see that I can close this, so I'll do it, apologies if it wasn't my job)

**Comment by electerious** [comment]
@nerbrume Yes, no medium-size generation with GD. It's too slow and PHP runs out of memory most of the time :-/

**Comment by oyvine** [comment]
Hi,
I have a slow uplink from my server and I am trying to reduce the resolution and/or compression of medium images to save some space. I have changed the resolution from 1920x1200 to 1024x768 in these two files:
Lychee/php/modules/Photo.php
Lychee/plugins/lychee-create-medium/index.php
In both files there is this comment:
# Size of the medium-photo
# When changing these values,
# also change the size detection in the front-end
Sorry but I am a newb an I have no idea what/where "the front-end" is. Could someone point me to the correct souce-file?

Thanks!
Øyvin Eikeland

**Comment by electerious** [comment]
@oyvine With front-end we mean the HTML, CSS and JS files. I recommend to take a look at the JS files, where the size has been defined, too.

**Comment by oyvine** [comment]
Thanks. After some experimentation I find that the best result comes from keeping the size at 1920x1080 and reducing the quality to 80% or 85%. This gives good results when I reduce the window size so that medium images are shown. The problem is when I enlarge the window to fullscreen and Lychee decides to go fetch the full size images and downscale them. Now, if I could only force Lychee to always use medium images for browsing and only use the full size images when I select "full photo". I gather that there must be an "if" function somewhere in the "front end" that selects between full and medium images. I am not able to find it. I would really appreciate some help on this. Thanks!

**Comment by electerious** [comment]
@oyvine It's not really an if. The browser chooses the best image by itself. We just tell him what sizes are available (`srcset`): https://github.com/electerious/Lychee/blob/master/src/scripts/build.js#L126
