### ISSUE TITLE
[Not an issue] What is the workflow of Lychee?  How are file stored behind the scene?

### ISSUE THREAD

**Issue by DeviantEng** [electerious/Lychee#557]
I really hate to open an issue like this, but I don't see any forums or any other method of communication.  I have not installed Lychee yet, and I want to better understand it first.

Basically, how are files stored behind the scenes?  Do images have to be uploaded from the webUI, or can Lychee be told to scan a specific directory for images, and can that scan be scheduled?

What I'm trying to accomplish is auto backups from multiple phones (mine and my wifes, for example), to a directory within our user directories (on my storage server).  So that means I have my own directory with my images from phones over the years, and she has the same in a different place.  I know Lychee doesn't have an app with auto-backup function or anything like that, but I'd love to use Lychee as a front-end and have it scan multiple directories for images.
With that in mind, is it possible to have an album in an album?  Like can I create a top-level album for each user, then have multiple albums within that album (one album for each phone I've had, which I've got about 5 directories full of images from different phones), if that makes sense?  Like have an album called "user1", and within "user1", have an album called "Galaxy S2" which pulls images from a certain path.  Another album called "HTC One", which pulls images from a different path.  Another album called "Xperia Z3", with images from yet another directory.  So on and so forth.

Is this something Lychee can support?  I completely understand if now, but I must say I'm very impressed with the little time I've spent in the demo!

**Comment by qligier** [comment]
> Basically, how are files stored behind the scenes?

The images are renamed and moved in the `Lychee/uploads/big/` directory. There is no sub-directory structure so it's maybe not that good for a backup.

> Do images have to be uploaded from the webUI, or can Lychee be told to scan a specific directory for images, and can that scan be scheduled?

The webUI has a server import button, which can be triggered automatically with a script, or you could use the [lycheesync](https://github.com/GustavePate/lycheesync) plugin.

> With that in mind, is it possible to have an album in an album?

Not yet; it has been often asked and it [will be done](https://github.com/electerious/Lychee/issues/254).

**Comment by DeviantEng** [comment]
Thank you @qligier for sharing some info.

Glad to hear sub-albums is a feature on the roadmap.  I now better understand Lychee, but I don't think it will be a drop-in solution for what I'm looking for to manage/share personal photos.
Though, it could be a good solution for my wife's photography business as a self hosted sharing platform.

lycheesync looks like a nice auto import solution, but not if it MOVES the files out of the source directory.  If it copies those out, to lychee, that would be fine except I'm now duplicating 30MB RAW images.
