### ISSUE TITLE
Back to album after tag research

### ISSUE THREAD

**Issue by valentin8709** [electerious/Lychee#562]
Just a question: when I make a tag research (like "landscape"), lychee show me every landscape pic, that's great. When I open one oh them, then click on the return button, lychee leave the search results and open the album where the picture is stored... Is it normal?

When I want to show every landscape pic to my friends, I just can't because I have to make the search between each file...

Thank you very much for your work by the way =)

**Comment by electerious** [comment]
That's the correct behavior. Lychee's architecture requires that the album is loaded behind the current photo. I agree that it's not optimal, but changing it would be too much work.

**Comment by valentin8709** [comment]
Ok no problem, I just wanted to know if it was a bug. I understand that could be a lot of work, and Lychee just does already a lot! Thank you for your answer =)
