### ISSUE TITLE
Is it possible to remove the Header (info, share, and More) from shared albums?

### ISSUE THREAD

**Issue by DrJeff** [electerious/Lychee#563]
Is it possible to remove the Header (info, share, and More) from shared albums?

I want to share a album with people but want the shared button, info, and more to be removed when not logged in. Is there any way of doing this? Is the page called differently when logged in and what to change??

**Comment by electerious** [comment]
I'm sure there's a way to do this, but I can't provide any help for customization.

Editing [this function](https://github.com/electerious/Lychee/blob/master/src/scripts/header.js#L111) could be a good starting point. Maybe that helps a bit.

**Comment by DrJeff** [comment]
Thanks 😃
