### ISSUE TITLE
Diagnostic page is "empty" if php5-gd is not installed

### ISSUE THREAD

**Issue by LudovicRousseau** [electerious/Lychee#565]
### Detailed description of the problem
I made a new installation of Lyche without installing the dependencies.

### Steps to reproduce the issue
Install lychee. But do not install the Debian package php5-gd.

### Output of the diagnostics (Settings => Diagnostics)
The page is mostly empty and contains only:
```
Diagnostics
-----------
```

I get an error in Apache error.log
```
PHP Fatal error:  Call to undefined function Diagnostics\\gd_info() in /home/rousseau/Documents/github/Lychee/plugins/Diagnostics/index.php on line 56, referer: https://images.xxx/Lychee/
```

The diagnostic should be smart enough to detect that php-gd is missing and display this information.
After installing php5-gd I have a filled Diagnostic page.

**Comment by electerious** [comment]
> The diagnostic should be smart enough to detect that php-gd is missing and display this information.

That's correct. PR welcome.
