### ISSUE TITLE
Green Images: Bug with Android? 

### ISSUE THREAD

**Issue by WulfmanGer** [electerious/Lychee#566]
Hey,

i use Lychee in Version 3.1.1
I hear repeated by Android users that they see only green images. From other Android User: no Problem. I use iOS: no Problems.

Workflow for alle Lychee-Pictures is the same:
DSLR / DSLM / iPhone ->  save as sRBG -> import to Lightroom -> Photoshop (switch from 16Bit to 8Bit) -> save es TIF/ZIP -> reimport Lightroom -> save as jpg. Upload to Lychee.

I use besides Lychee also Koken, Piwigo, Wordpress ... never heard from problems with pictures @ this Platform (same Workflow).

My Lychee-Album: https://album.fotobastler.de/

I can't confirm this ... no Android @ the Moment.

Is there an known Problem?

Thx
Patrick

**Comment by qligier** [comment]
I don't see any problem with Android 4.4.2 and 5.1.1

**Comment by WulfmanGer** [comment]
Example from Person 1; Smartphone: i don't know at this moment
![index](https://cloud.githubusercontent.com/assets/19263061/16406541/29dd935e-3d0f-11e6-8a6c-2eabba0ad13f.jpg)

Person 2 same ... Smartphone: Samsung galaxy s3 mini

I've check with Samsung Galaxy 4 7.0 LTE ... no problem.

More Infos come soon ... i hope ... Too many People don't know which Handy, Android-Version etc. they have ;) ... :(

**Comment by electerious** [comment]
Could they/you take a look at the images saved on the server (`uploads/big/`)? Are they green, too? Maybe it's just a front-end bug.

**Comment by electerious** [comment]
Closing this issue as it's not possible to reproduce the problem.
