### ISSUE TITLE
distributed data storage

### ISSUE THREAD

**Issue by Jonn3y** [electerious/Lychee#567]
Heyho, 

I tested Lychee yesterday and i think it's a nice tool do collect all my photos in one beautiful database.
But there are a few things I don't like:
1. the central datastorage.
2. filedelete after import from server (you should ask if the user agrees to that option)

1: For uploading files from a mobilephone or dropbox or any other external devices it's okay, but for local media it's not great.

It would be perfect just to 'link' to the local(on several HDDs or network-mounts) media and create a metadata file for each file. For example [Plex](https://plex.tv) does this point perfectly.
This would make it possible to use unlimited numbers of photos (and maybe videos too?) without using ZFS or RAID.

``` bash
├── Uploads: (in /var/www/html/Lychee/uploads/big)
│   ├── Sample Folder 
│   │   ├── File 1.png
...

/media
├── Disk 1 (local mount)
│   ├── Holiday 2014 -> /var/www/html/Lychee/php/database/<galleryid>
│   │   ├── File 1.png -> /var/www/html/Lychee/php/database/<galleryid>/<id>.metadata
│   │   ├── File 2.png -> /var/www/html/Lychee/php/database/<galleryid>/<id>.metadata
│   │   ├── ...
...
├── Disk 2 (network mount) 
│   ├──Cologne 2015 -> /var/www/html/Lychee/php/database/<galleryid>
│   │   ├── File 1.png -> /var/www/html/Lychee/php/database/<galleryid>/<id>.metadata
```

Something like that ? 

Edit1:
I found the plugin: https://github.com/GustavePate/lycheesync

```
Command line switches

You can choose between the following options to adjust the program behaviour:
[...]
-l link mode. Don't copy files from source folder to lychee directory structure, just create symbolic links (thumbnails will however be created in lychee's directory structure)
[...]
```

I think that is exactly what I mean, now it needs a WebGUi integration. 
Is there a way to integrate it? 

Best wishes:
Jonas

**Comment by DeviantEng** [comment]
I just want to share that I am looking for the exact same solution here.  I already have several organized directories (and sub-directories) of images, and a good chunk of those are auto-synced from my phone via WebDav.  I don't want Lychee to move/edit/update/delete the actual image file, but I would love for Lychee to be able to view, tag, generate metadata to store in a Lychee DB.  

Using lycheesync in link mode may be a start?

**Comment by qligier** [comment]
A solution could be to create symlinks from your already existing library to the lychee directory. The `-l` flag of lycheesync does that. My only worry with lycheesync is that it doesn't process the photos metadata the same way as lychee.
You could also modify lychee to create a symlink/copy the file:
https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L182-186
```php
// Move file (original)
if (!@copy($tmp_name, $path)) {
	Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
	if ($returnOnError===true) return false;
	Response::error('Could not copy photo to uploads!');
} else @unlink($tmp_name);
// OR
// Copy file
if (!@copy($tmp_name, $path)) {
	Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
	if ($returnOnError===true) return false;
	Response::error('Could not copy photo to uploads!');
}
// OR
// Create symlink
if (!@symlink($tmp_name, $path)) {
	Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
	if ($returnOnError===true) return false;
	Response::error('Could not copy photo to uploads!');
}
```

**Comment by DeviantEng** [comment]
@qligier Interesting.

So I've got Lychee installed on a CentOS 7 instance (php5.6, mariadb, nginx) and working.  I've updated Photo.php to remove those lines you highlighted, and added the symlink section as you mentioned.  Here is that section of my `Photo.php`:

````
                if ($exists===false) {

                        // Import if not uploaded via web
                        if (!is_uploaded_file($tmp_name)) {
                        #       if (!@copy($tmp_name, $path)) {
                        #               Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
                        #               if ($returnOnError===true) return false;
                        #               Response::error('Could not copy photo to uploads!');
                        #       } else @unlink($tmp_name);

                       // Create symlink
                               if (!@symlink($tmp_name, $path)) {
                                        Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
                                        if ($returnOnError===true) return false;
                                        Response::error('Could not copy photo to uploads!');
                        } else {
                                if (!@move_uploaded_file($tmp_name, $path)) {
                                        Log::error(Database::get(), __METHOD__, __LINE__, 'Could not move photo to uploads');
                                        if ($returnOnError===true) return false;
                                        Response::error('Could not move photo to uploads!');
                                }
                        }

                } else {

                        // Photo already exists
                        // Check if the user wants to skip duplicates
                        if (Settings::get()['skipDuplicates']==='1') {
                                Log::notice(Database::get(), __METHOD__, __LINE__, 'Skipped upload of existing photo because skipDuplicates is activated');
                                if ($returnOnError===true) return false;
                                Response::warning('This photo has been skipped because it\'s already in your library.');
                        }

                }
````

Does that look correct, as you suggested?  

I have a local directory (for testing), `/tmp/images` containing 5 png's.  I then go into Lychee (after setting up the DB connection and creating a user) and click the `Import from Server` option.  I specify `/tmp/images` (nginx:nginx owns `/tmp/images`, which is the same user:group that owns Lychee, with 770 perms on `/tmp/images`) and the `Importing from Server` box appears where it just says the path and "importing", but nothing appears to be happening.

I am seeing this in my nginx error log:
````
2016/07/07 20:34:48 [error] 30716#0: *11 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'private' (T_PRIVATE) in /var/www/Lychee/php/Modules/Photo.php on line 266" while reading response header from upstream, client: 172.16.1.10, server: localhost, request: "POST /php/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php56-php-fpm.sock:", host: "lemp.local.domain.com:8084", referrer: "http://lemp.local.domain.com:8084/"
````
(172.16.1.10 is my macbook pro that I am accessing the webUI from)

Here is my Lychee diagnostics:
````
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.2
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50547
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.2.1
Plugins:         
````

Nothing in Lychee logs.  Suggestions?

**Comment by bb-Ricardo** [comment]
have you considered SELinux?
try <code>setenforce 0</code> and try again

**Comment by DeviantEng** [comment]
Selinux is already disabled. 

Like I said, if I leave `Photo.php` as normal, that app works. Changing that piece to create symlinks is when it no longer uploaded anything.

**Comment by qligier** [comment]
You forgot a closing curly bracket:
```php
if ($exists===false) {

        // Import if not uploaded via web
        if (!is_uploaded_file($tmp_name)) {
        #       if (!@copy($tmp_name, $path)) {
        #               Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
        #               if ($returnOnError===true) return false;
        #               Response::error('Could not copy photo to uploads!');
        #       } else @unlink($tmp_name);

         // Create symlink
                if (!@symlink($tmp_name, $path)) {
                        Log::error(Database::get(), __METHOD__, __LINE__, 'Could not copy photo to uploads');
                        if ($returnOnError===true) return false;
                        Response::error('Could not copy photo to uploads!');
                } // Close me
        } else {
                if (!@move_uploaded_file($tmp_name, $path)) {
                        Log::error(Database::get(), __METHOD__, __LINE__, 'Could not move photo to uploads');
                        if ($returnOnError===true) return false;
                        Response::error('Could not move photo to uploads!');
                }
        }

 } else {

        // Photo already exists
        // Check if the user wants to skip duplicates
        if (Settings::get()['skipDuplicates']==='1') {
                Log::notice(Database::get(), __METHOD__, __LINE__, 'Skipped upload of existing photo because skipDuplicates is activated');
                if ($returnOnError===true) return false;
                Response::warning('This photo has been skipped because it\'s already in your library.');
        }

 }
```

And of course, please try the script on some dummy files before running it on your library :wink:

**Comment by DeviantEng** [comment]
@qligier That missing curly bracket was the problem.  I was able to import photos and it created symlinks instead of moving, and it created albums like I expected.  

Now the next question, and possibly the final question, can I run Import from Server via cron?

**Comment by edobry** [comment]
just want to mention i'm looking for a solution to exactly this problem. i'm thinking of building a tool to manage importing to lychee, wrapping lycheesync.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
