### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by matunixe** [electerious/Lychee#568]
### Detailed description of the problem
I can't upload photos.

### Steps to reproduce the issue
1. Install properly Lychee as explained here: https://github.com/electerious/Lychee/blob/master/docs/Installation.md
2. Open the Safari web-browser, navigate to your website.
3. Try to upload something.

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.2
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      bundled (2.1.0 compatible)
Plugins:     
```

### Browser and system
Lychee: Debian 8 Jessie, PHP 7.0, Nginx 1.10, MariaDB 10, ImageMagick
Me: MacOS and the last Safari

### PHP logs
```
2016/07/01 12:18:33 [error] 5214#5214: *92 client intended to send too large body: 2429725 bytes, client: 81.64.130.1, server: photo.matuni.xyz, request: "POST /php/index.php HTTP/2.0", host: "photo.matuni.xyz", referrer: "https://photo.matuni.xyz/"
```

### PHP config (php.ini)
Exactly like the FAQ.
```
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 20M
memory_limit = 256M
```

I don't have forgotten to restart PHP service, that's very strange.
Thanks in advance for helping.

**Comment by thehawkes** [comment]
Please try to in crease the client_max_body_size for nginx too

>http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by matunixe** [comment]
Many thanks dear Sir, it works.

But now I'm stuck on the #522 error. 👎

**Comment by electerious** [comment]
@matunixe Please add some details to #522, so we can take a closer look at it.
