### ISSUE TITLE
Importing large numner of images from server

### ISSUE THREAD

**Issue by toby11** [electerious/Lychee#569]
Hi, 

I am trying to upload a large number of photos  (800) they are all very large (5MB each) photos

When I used import from server it always stops after anout 12-18 photos.

I have read the FAQ and adjusted the max_execution_time and other settings in my php user ini. I have confirmed these have taken effect by looking at php info. Are there any other settings that would affect it?
## Diagnostics

Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!
## System Information

Lychee Version:  3.1.1
DB Version:      030100
System:          Linux
PHP Version:     5.6
MySQL Version:   50548
Imagick:         1
Imagick Active:  1
Imagick Version: 1684
GD Version:      bundled (2.1.0 compatible)
Plugins:         

WIndows 7 - Firefox and Chrome

Many Thanks
Toby

**Comment by toby11** [comment]
Updated to 3.1.2 and it still does it.

On another note it would be nice to have some progress indication whilst importing from the server.

thanks

**Comment by electerious** [comment]
Could you please attach the recent lines of your PHP error log? It should contain additional details.

**Comment by toby11** [comment]
Hi,

The last log line is :

[Wed Jul 06 12:11:01 2016] [error] [client xxxxxxxxx] php: time limit exceeded `Operation canceled' @ fatal/cache.c/GetImagePixelCache/1560, referer: http://xxxxx

However I have the .user.ini set as this :

max_execution_time = 10000
post_max_size = 1200M
upload_max_size = 1200M
upload_max_filesize = 120M
max_file_uploads = 1200

The images are quite large (approx. 4-5mb each) it stops each time after about 15 images.

Thanks
Toby

**Comment by toby11** [comment]
Did you have any ideas what this might be?

Many Thanks

**Comment by qligier** [comment]
This is an [issue of ImageMagick](https://github.com/gographics/imagick/issues/71). I don't think there's something we can do for it. You should try to update your ImageMagick installation as it [has been patched](https://github.com/ImageMagick/ImageMagick/commit/c09e485e5e3cad09c117a3657bbca98f6a8050fe).

**Comment by maggick** [comment]
Hi, I just import 284 file from the server. ~3MB each. All pictures seems to be there but the importing window didn't close itself.

**Comment by electerious** [comment]
@maggick That usually happens when an error has occurred. Can you give us some additional information (PHP error log messages or browser console output)?

**Comment by maggick** [comment]
@electerious Okay next time it happen I will get the log for you.

**Comment by westframe** [comment]
Same error here. I'm on Dreamhost. Installed Lychee is good (amazing software thnx!). But I can't seem to import more then 5 or 9 images from Server, and also the Import-window does not close. Main reason for me to install this software is I'm about to upload 10 GB of image-archive... Please any tips are welcome.

**Comment by karstil** [comment]
Same problem here. In my case it seems to be a timeout in php
Fatal error:  Maximum execution time of 30 seconds exceeded in /www/htdocs/photo/php/Modules/Photo.php on line 324

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
