### ISSUE TITLE
[Security] GET request passing the password in parameter

### ISSUE THREAD

**Issue by BenoitGEORGELIN** [electerious/Lychee#571]
### Detailed description of the problem

The download of a picture/album do a GET request passing the password in parameter. 
### Steps to reproduce the issue

Download a picture or an album
### Browser and system

All

I would be nice to find another way to allow picture or album downloads from users using a password without passing the password in parameter (GET) 
The password could be hidden or hashed and use of POST method would be the best, maybe using an ajax call ?

At least the password album used by the admin to protect it will not been visible. 
The best would be that direct link using hashed password don't work so user have to login first and then be able to download the album/picture

As an exemple, if you are using a public computer , you know the password of the album. 
You connect , you download it. 
The link (including the password , hash or not) stays in the download history. 
Then another guy come, click to the link , and can enjoy all your pictures albums . If the password is also in clear text, and you setup the same password to others album, he can download everything

Thanks

**Comment by dd23** [comment]
That should definitely be fixed by using a POST request.
Hashing does hide the password, but still allows to download.

**Comment by electerious** [comment]
We can't get away from transferring the password, but we should definitely switch to a POST request. PR welcome.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
