### ISSUE TITLE
Preload medium instead of big picture

### ISSUE THREAD

**Issue by givre** [electerious/Lychee#572]
### Detailed description of the problem
I had a quick look on the picture size from my web browser. 
It look like Lychee pre-charge the next picture, but it use the "big" format witch is the original size.  Why the medium format is not used for that ? The "big" format should only be used when this format is asked by the user.

Maybe it's this call that generate the "medium" size of the big one called in advance ? But it looks do do the same each time I consult the picture , do you know why ?

For better performance on low bandwidth connexion that would be a nice thing to have a background generation of picture "thumbnails, medium and big" so there is no need to "pre-charge" the big format of the picture.  Specially when it's the original size picture sent. 

### Steps to reproduce the issue
Open the browser debugger from chrome or FF 
Check the link of the pictures loaded every time you change from one picture to another one

### Browser and system
Linux , Chromium

**Comment by electerious** [comment]
Good point. It should preload the medium photo instead.

**Comment by electerious** [comment]
Implemented and part of Lychee 3.1.3 https://github.com/electerious/Lychee/commit/c527534ee58e5f1bb0c33a3c03c88c6972ea4115 https://github.com/electerious/Lychee/commit/1b8dd24fe1b52cef4f0a18d2ade786fbba348a09
