### ISSUE TITLE
[NewFeature] Statistics Integration 

### ISSUE THREAD

**Issue by givre** [electerious/Lychee#573]
### Request of a new feature
That would be a great new features to have statistics about visitors on the gallery simple and clean one like your other projet ACKEE or an easy integration with Piwik for exemple. 

If a statistic system fully integrated is too much work, we can just provide a configuration option where people can add the specific tag of google analytics , Piwik  or ACKEE

Thanks

**Comment by electerious** [comment]
It's currently not planned to integrate a statistics service or a configuration for such a service. Custom scripts can be added to the `index.html` directly.
