### ISSUE TITLE
Dockerfile not present? 

### ISSUE THREAD

**Issue by sjs7007** [electerious/Lychee#575]
### Detailed description of the problem
It seems the script for Dockerfile has been removed from the repository. It was present earlier in the commit(https://github.com/electerious/Lychee/commit/e12f53d91d82208dcf51c6a497dfc69721400a38) in which README for Docker was added.

### Steps to reproduce the issue
```
git clone https://github.com/electerious/Lychee.git
cd Lychee
docker build -t lychee .
```

### Potential Solution
If the [docker file](https://github.com/electerious/Lychee/blob/e12f53d91d82208dcf51c6a497dfc69721400a38/Dockerfile) present in previous commit is still valid, we can use that.

**Comment by electerious** [comment]
Please take a look at the [readme](https://github.com/electerious/Lychee#docker). We recommend to use the following Dockerfile: https://hub.docker.com/r/kdelfour/lychee-docker/

**Comment by sjs7007** [comment]
Ah my bad. I followed the instructions from [here](https://github.com/electerious/Lychee/blob/c0c924fc13c3b675de06167a95fcbd803b0e4148/docs/Docker.md) after searching for Docker. Didn't see the homepage README.
