### ISSUE TITLE
Make & Camera Model not shown, content Description bleeds into those fields

### ISSUE THREAD

**Issue by dpkz** [electerious/Lychee#577]
Hi,

I just started using Lychee and uploaded a first bunch of photos. Exported from Adobe Lightroom with all metadata except location.

### Detailed description of the problem
Lychee doesn't show content for "Make" and "Camera Model", and if there is a Description, parts of the content of that field are shown in Make and Camera Model.

Example with Description can be viewed here:
http://www.holger-pontius.de/lychee/#14686757680526/14686758015961

There are 9 photos in that album, all of them show the same issue.

exiftool shows this (before uploading):
```
$ exiftool IMG_5006.jpg | egrep "(Make|Camera Model|winde)"
Image Description               : Purpur-Prunkwinde
Make                            : Canon
Camera Model Name               : Canon EOS 70D
Description                     : Purpur-Prunkwinde
Caption-Abstract                : Purpur-Prunkwinde
```

Since exiftool shows everything fine, I think the files should be fine.

Best regards
Holger

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.2
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50549
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1
Plugins:         
```

### Browser and system
OS X 10.11.5 / Safari 9.1.1, Chrome 51.0.2704.103 (64-bit)

**Comment by dpkz** [comment]
Updated link: http://www.holger-pontius.de/lychee/#14686757680526/14688774048192

**Comment by electerious** [comment]
Can confirm the issue. It looks like `exif_read_data` returns an invalid value for `Make` and `Model`. Not sure if we can do something about it. Let me know when you find more about it.

Here's where the parsing happens in Lychee: https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L844

**Comment by dpkz** [comment]
After reading the comments below here: http://php.net/manual/en/function.exif-read-data.php
and search a bit for 'Make' and 'Model' here: http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

... I came up with the suspicion, that the culprit might be the `'EXIF'` as `$sections` parameter here: https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L827

Not tested yet, but it seems to me that IFD0 data isn't read if only `'EXIF'` is given as `$sections` parameter. And Make an Model are part of IFD0.

I will test it eventually, but that will take quite some time.

**Comment by dpkz** [comment]
Okay, now that I had time to check it, this is merely a duplicate of #481. Sorry for the confusion.
