### ISSUE TITLE
Firefox password prompt info not stored

### ISSUE THREAD

**Issue by dd23** [electerious/Lychee#578]
### Detailed description of the problem
When signing in into the admin interface, Firefox does not offer to store username and password.
It works fine in Chrome, though. 

Maybe there is some meta data missing that would let Firefox know that this form contains username and password, so that the browser can store this data in its password manager.

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.2
DB Version:      030102
System:          Linux
PHP Version:     5.5
MySQL Version:   50630
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      bundled (2.1.0 compatible)
Plugins:         
```
### Browser and system
Firefox 47.0.1 on Win 10 x64 on the client side that visits the website.

**Comment by electerious** [comment]
Thanks for the report. [The issue has been discussed](https://github.com/electerious/Lychee/issues/456) already, but we are still not sure what's causing it. Let us know in issue #456 when you find more details.
