### ISSUE TITLE
php-session

### ISSUE THREAD

**Issue by elnicko** [electerious/Lychee#579]
The installation doc contains the following plugins marked as mandatory:
exif, gd, json, mbstring, mysqli, zip

However, on minimalistic systems also "session" may not be installed, which is used excessively. Could You please add this to the docs?

Cheers.

**Comment by electerious** [comment]
Added it! Thanks for letting me know.

**Comment by Tectu** [comment]
May I suggest cherry-picking that commit into the current master branch as well?

**Comment by electerious** [comment]
It will be part of the next release/version. I don't think it's critical.
