### ISSUE TITLE
Server Error or API not found and Diagnostics returning error 500

### ISSUE THREAD

**Issue by josefrvaldes** [electerious/Lychee#582]
Hi guys! I'm trying to install this amazing tool in a brand new FreeBSD distro inside a FreeNAS Jail. The thing is that I just installed apache, php and mysql and everything seems to be working. I installed too the php extensions needed to work (exif, gd, json, mbstring, mysqli and zip) and in my phpinfo they are all enabled.
I gave 777 permissions to the folders mentioned in the installation doc.

But it still doesn't work. When I try to go to the main page it says `Server Error or API not found`, and when I try to run Diagnostics, it returns server error 500 too.

I even try to see the real error in the server using 

     ini_set('display_errors', 1);
     ini_set('display_startup_errors', 1);
     error_reporting(E_ALL);

but anything is shown.

This is running in a HP Proliant microserver gen8 inside a Jail running in FreeNAS.

Thanks a lot for your help and congratulations for this amazing tool!

**Comment by josefrvaldes** [comment]
I will close this issue because I'm pretty sure it's a problem with my server and not with the library itsef. If somebody thinks it may be a real bug, then reopen it again.

**Comment by isntall** [comment]
Last time I ran Lychee inside a FreeBSD jail, it had problems with the php session not being set.

**Comment by josefrvaldes** [comment]
and how did you solve it? do you still remember?

**Comment by isntall** [comment]
Is php session support enabled in the jail. 
Searching with pkg got me this.
` # pkg search php-session `
` p5-PHP-Session-0.27_1          Read / write PHP session file`

I ended going back to a docker container, my FreeNAS is under powered.

**Comment by josefrvaldes** [comment]
It is definitely the same problem that you had. I finally managed to get the error and the problem is that session_start() is not found.
Thanks a lot!

**Comment by josefrvaldes** [comment]
Finally managed to solve it.
The problem was that in php.ini the extensions_dir was pointing to `./php/extensions.ini` when it should be pointing to `/usr/local/lib/php/20131226`. That's why really there was no extension working correctly. But now everything looks fine!
