### ISSUE TITLE
Dates translations

### ISSUE THREAD

**Issue by zikamatej** [electerious/Lychee#586]
Hi, I saw one of the latest updates included an improvement for dates translations.  
How is that possible then?  
I need to translate dates, the rest is not a problem for me, i could rewrite the hardcoded text, but that's with every update again...  

Thanks

Running 3.1.2

**Comment by electerious** [comment]
Please see https://github.com/electerious/Lychee/issues/461#issuecomment-197009370 Can't provide any additional information as I haven't tried it, yet.
