### ISSUE TITLE
Edit main header title

### ISSUE THREAD

**Issue by Rurik19** [electerious/Lychee#587]
Is it possible to change main page header title from just "Albums" to my custom title? 
May be it should be some settings?

**Comment by electerious** [comment]
Please see [here](https://github.com/electerious/Lychee/issues/455).

**Comment by electerious** [comment]
Ah sorry, I missed your point. Changing "Albums" in the header is only possible by changing a string in the JS file. A setting for this isn't planned.

**Comment by Rurik19** [comment]
Do you consider internationalisation ? There are not so many strings in app, may be useful to have separate file like JSON to manage them.

**Comment by electerious** [comment]
Internationalisation is [planned](https://github.com/electerious/Lychee/issues/207).
