### ISSUE TITLE
[FEATURE] Allow to set a page name in the top bar on the left

### ISSUE THREAD

**Issue by gladiac** [electerious/Lychee#592]
### Detailed description of the problem
It would be great to set a page name maybe with a link in the top bar one the left. Some people might like to put their name in there and a link to their website. The title of the site might be set to the same name ...

**Comment by electerious** [comment]
You could modify the HTML and CSS directly. Lychee is a management web-app, it's not planned to add such features. Thanks for the idea anyway.
