### ISSUE TITLE
Lychee will allow you to upload duplicates

### ISSUE THREAD

**Issue by megah3rtz** [electerious/Lychee#596]
If I upload a duplicate photo with the same name, EXIF data and the like, it still shows up as a new photo.

Please can we check for a duplicate of the data in the database already, or have a clean-up function or the like?

**Comment by electerious** [comment]
Lychee allows you to upload or duplicate the same image, but only stores one copy of the photo on the server. It won't use any storage and it's not planned to prevent the user from doing so. You could use a MySQL query which shows or deletes duplicates from the database.

**Comment by electerious** [comment]
Totally forgot that there's an option to skip duplicates on upload: https://github.com/electerious/Lychee/blob/master/docs/Settings.md#skip-duplicates-on-upload

**Comment by megah3rtz** [comment]
Is there any advantage to showing duplicate photos, that I haven't thought
of?
