### ISSUE TITLE
Internal server error when uploading larger files

### ISSUE THREAD

**Issue by fred2fish** [electerious/Lychee#599]
Hi, 

I'm trying out Lychee on MAMP and I'm facing an internal server error when uploading larger images (>8mb). 

I did apply the recommended settings in the PHP.INI file before installing Lychee. 

What I find odd is that the files do find their way to the upload folder. 

Any clues? 
<img width="1259" alt="capture d ecran 2016-08-20 a 12 01 56" src="https://cloud.githubusercontent.com/assets/21139914/17830522/39bb355e-66ce-11e6-8920-dd3e031a8b73.png">

**Comment by qligier** [comment]
Anything in the PHP or Lychee logs?

**Comment by fred2fish** [comment]
In the Lychee logs I find this : "2016-08-20 11:29:20 - notice - Lychee\Modules\Photo::add (219) 	- Skipped adjustment of photo (IMG_2160)"

**Comment by qligier** [comment]
That should not be meaningful here. Nothing in the PHP logs?

**Comment by fred2fish** [comment]
I can't find anything in the PHP logs.

However, for the OSX logs I get this for each failed upload : iconservicesagent:-[ISGenerateImageOp generateImageWithCompletion:] Failed to composit image for descriptor <ISBindingImageDescriptor: 0x7fe31a42f240>.

**Comment by fred2fish** [comment]
I re-tried to upload larger files and I got this in the PHP log: 
[20-Aug-2016 13:30:21 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1601 bytes) in /Applications/MAMP/htdocs/lychee-master/php/helpers/fastImageCopyResampled.php on line 24

**Comment by qligier** [comment]
That's the one. You have to increase php memory limit in the _php.ini_ file, with the [memory_limit](http://php.net/manual/en/ini.core.php#ini.memory-limit) directive.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
