### ISSUE TITLE
Link to live demo in README.md

### ISSUE THREAD

**Issue by krestenjacobsen** [electerious/Lychee#602]
### Detailed description of the problem
The link to the live demo in README.md should probably point to "http://ld.electerious.com" instead of "http://electerious.com/lychee_demo/" as it does now.

### Steps to reproduce the issue
Click link -> get 404

### Output of the diagnostics (Settings => Diagnostics)
N/A 

### Browser and system
I bet that doesn't matter. ;-)

**Comment by electerious** [comment]
Thanks for letting me know :) Fixed it!
