### ISSUE TITLE
Creating/installing a plugin

### ISSUE THREAD

**Issue by Hu51** [electerious/Lychee#604]
### Detailed description of the problem

After following your howto to create a plugin I got "server error or API not found"

update `lychee_settings` set `value`='ExamplePlugin\ExamplePlugin' WHERE `key`='plugins'

I have the same issue with your watermark plugin.

version : 030102
### Steps to reproduce the issue

Simply follow your guide..
## Diagnostics

Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!
## System Information

Lychee Version:  3.1.3
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50630
Imagick:         1
Imagick Active:  1
Imagick Version: 1680
GD Version:      bundled (2.1.0 compatible)
Plugins:         ExamplePlugin\ExamplePlugin
### Browser and system

PHP 5.6, Firefox 48 .

**Comment by electerious** [comment]
The watermark plugin is outdated. It won't work with the newest version.

Is there an ExamplePlugin directly in `lychee/plugins/`?

**Comment by Hu51** [comment]
I tried again, the example plugin works.
Is there any documentation to how to debug this app?

On "var_Dump($subject);" I have the same error message in the example plugin.

**Comment by qligier** [comment]
You get the "server error or API not found" error message when php encounters an error in your plugin. You have to debug it with php logs, as you would do for any other script.

**Comment by mullacha** [comment]
I also have a Problem using one of the finished plugins called "redirect"
Lychee is running perfectly via Web Hosting without problems

Diag:
> Diagnostics
> -----------
> Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
> Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
> No critical problems found. Lychee should work without problems!
> 
> 
> System Information
> ------------------
> Lychee Version:  3.1.4
> DB Version:      030102
> System:          SunOS
> PHP Version:     7
> MySQL Version:   50631
> Imagick:         -
> Imagick Active:  1
> Imagick Version: -
> GD Version:      bundled (2.1.0 compatible)
> Plugins:         

I copied 'redirect' into the "plugins"-folder, when I try to open /plugins/redirect/?name=test all I get is a white page. Do I have to change the value 'plugins' @ lychee_settings?

**Comment by qligier** [comment]
What's the content of both Lychee and PHP logs?

**Comment by electerious** [comment]
@mullacha The plugin is deprecated and might not work anymore. v2.5 was the last supported version. Double check if the `config.ini` exists in the folder like instructed in the readme. That might be the only chance to get it working.

**Comment by mullacha** [comment]
The config.ini exists and redirects to the root of Lychee.
Both Lychee and PHP-Error-Logs have no changes after trying the redirect-link
 
It seems, that the plugin isn't working anymore..

**Comment by Hu51** [comment]
Can you add a "Working example" to the plugins?

**Comment by electerious** [comment]
The [ExamplePlugin code](https://github.com/electerious/Lychee/blob/master/docs/Plugins.md) should work. Please let us know the content of your PHP log. It should tell why it isn't working.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
