### ISSUE TITLE
Server error or API not found when using search function

### ISSUE THREAD

**Issue by ticoombs** [electerious/Lychee#605]
### Detailed description of the problem
When doing a POST to index.php with the search function, (or just using the searchbar ) I get an "Server error or API not found". 
This is because I have the php.ini value `display_errors = On` An error is returned instead of just the json object. 

- Issue with the following code, [php/Modules/Photo.php](https://github.com/electerious/Lychee/blame/master/php/Modules/Photo.php#L655)

```

                if ($data['medium']==='1') $photo['medium'] = LYCHEE_URL_UPLOADS_MEDIUM . $data['url'];
                else                       $photo['medium'] = '';
```

Data Returned in browser is not JSON:
```
<br />
<b>Notice</b>:  Undefined index: medium in <b>/var/www/lychee.local/wordpress/php/Modules/Photo.php</b> on line <b>655</b><br />
<br />
<b>Notice</b>:  Undefined index: medium in <b>/var/www/lychee.local/wordpress/php/Modules/Photo.php</b> on line <b>655</b><br />
{"photos":{"14719904900691":{"id":"14719904900691","title":"Dinner","tags":"Service,Meal","public":"0","star":"0","album":"14719905303501","medium":"","thumbUrl":"uploads\/thumb\/ce4366dbb71f109c4120cbd511ab4465.jpeg","url":"uploads\/big\/ce4366dbb71f109c4120cbd511ab4465.jpg","cameraDate":"1","sysdate":"30 January 2016"},"albums":null,"hash":"183a3899289fc93518b6869aace4be15"}
```

### Steps to reproduce the issue
- git pull from master (Latest commit, was https://github.com/electerious/Lychee/commit/18f2397830af8d2235b0a0d373d93d053bab0688) 
- set `display_errors = On` in your php.ini file.
- Restart php
- Go through setup 
- upload image
- Try to search for that image
- Get an error

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.3
DB Version:      030102
System:          Linux
PHP Version:     5.5
MySQL Version:   50631
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      2.1.1-dev
Plugins:         
```
### Browser and system
Firefox 48, Ubuntu 14.04 LTS

**Comment by electerious** [comment]
You're right, thanks for letting me know!

**Comment by howdytom** [comment]
Yes, I am able to reproduce it. It's working as expected in `display_errors = off``

**Comment by electerious** [comment]
Could someone try the develop branch and confirm that the issue has been fixed? https://github.com/electerious/Lychee/tree/develop

**Comment by hrniels** [comment]
Yes, is fixed now.

**Comment by electerious** [comment]
A new version has been released. Thanks for the help!
