### ISSUE TITLE
[Feature Request] Albums within Album

### ISSUE THREAD

**Issue by Mukrosz** [electerious/Lychee#607]
Good day,

Is it possible to have Albums inside Albums to better organization and security/convenience?
Currently, all of my albums are password protected. This means a viewer has to enter a password for each album they want to see (and re-enter that password each time they re-enter the album).

It would be much easier if a viewer could enter a password protected folder and navigate through all sub-albums inside.

is this making sense?

Thank you!

**Comment by hrniels** [comment]
Yes, we are working on a subalbum feature. See the branch feature/subalbums. It's not completely finished yet and you also need to rebuild dist/* first (see docs/Build.md), but you can already give it a try, if you like.

**Comment by electerious** [comment]
See https://github.com/electerious/Lychee/issues/254 for more information.

**Comment by Mukrosz** [comment]
Thank you.
