### ISSUE TITLE
[Feature request] Tag database

### ISSUE THREAD

**Issue by tvdmitrii** [electerious/Lychee#608]
I have a huge archive of photos and I want to tag them. Is it possible to create a tag database? So it will assist you while you are trying to tag a photo and will show some already existing tags. This will also make possible to create a tag cloud to help a new user search

**Comment by electerious** [comment]
Yes, there're several improvements planned for tags: https://github.com/electerious/Lychee/issues/505 https://github.com/electerious/Lychee/issues/409 https://github.com/electerious/Lychee/issues/397
