### ISSUE TITLE
[Feature Request] Bulk actions - delete or move

### ISSUE THREAD

**Issue by n1md4** [electerious/Lychee#612]
The ability to mark many images for removal or to move to an album.

**Comment by electerious** [comment]
Just click and hold between the photo thumbs and move your mouse. The next minor version also allows the selection of multiple individual items.

**Comment by n1md4** [comment]
Ah, it is the multiple individual items delete/move that I meant, so that is good news!  I have over 10,000 unsorted pictures to sort through :)  Thanks.
