### ISSUE TITLE
Submit on Database setup throws a json parse error

### ISSUE THREAD

**Issue by donpdonp** [electerious/Lychee#613]
### Detailed description of the problem

Pressing submit at the very first page to install/setup database, the client js throws a json parse error. the network inspector shows no http traffic from the submit, it looks like it errors before it gets the chance to send.
### Output of the diagnostics (Settings => Diagnostics)

column number: 12393
https://example.org/lychee/dist/main.js
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

(more data, hard to copy/paste)
Object { description: "Server error or API not found.", params: Object, response: SyntaxError }main.js:5:23481
lychee.error()main.js:5
api.post/i()main.js:4
pe.Callbacks/c()main.js:2
pe.Callbacks/u.fireWith()main.js:2
o()main.js:3
.send/n/<()
### Browser and system

Firefox 49 and Lychee 3.1.4

**Comment by electerious** [comment]
It sounds like the response contains errors / invalid JSON. Could you attach the response text of the network request? The JS error doesn't provide any helpful information. Taking a look at the PHP error log is also an option.

**Comment by donpdonp** [comment]
Okay I've looked at the firefox network inspector again and there is a request being made. The reponse body is empty. The same request, duplicated with curl, is below.

```
$ curl 'http://torx.local/lychee/php/index.php' --data 'function=Config%3A%3Acreate&dbName=lychee&dbUser=root&dbPassword=pass&dbHost=localhost&dbTablePrefix='
$
```
I've looked for php_errors.log but it appears php is not encountering an error. Also, the http post is succeeding according to nginx

`192.168.0.14 - - [03/Sep/2016:06:56:08 -0700] "POST /lychee/php/index.php HTTP/1.1" 200`

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
