### ISSUE TITLE
Optimizing SQL queries of Albums::get()

### ISSUE THREAD

**Issue by qligier** [electerious/Lychee#615]
Hey,

So I wanted to optimize the SQL queries of Albums::get() because N+1 queries for N albums doesn't seem quite good.
I wrote a few queries that I benchmarked to see if it was possible to do better.
## The queries

The original one:

``` sql
SELECT SQL_NO_CACHE id, title FROM lychee_albums ORDER BY id ASC;
-- for album in albums
SELECT SQL_NO_CACHE thumbUrl FROM lychee_photos WHERE album = :album_id ORDER BY id DESC;
```

The nice one:

``` sql
SELECT SQL_NO_CACHE a.id, a.title, SUBSTRING_INDEX(GROUP_CONCAT(p.thumbUrl SEPARATOR ','), ',', 3) AS thumbs
FROM lychee_albums AS a
LEFT OUTER JOIN lychee_photos AS p ON a.id = p.album
GROUP BY a.id ORDER BY a.id ASC, p.id DESC;
```

The dumb one:

``` sql
SELECT SQL_NO_CACHE a.id, a.title,
(SELECT thumbUrl FROM lychee_photos AS p1 WHERE p1.album=a.id ORDER BY p1.id DESC LIMIT 0,1) AS thumbUrl1,
(SELECT thumbUrl FROM lychee_photos AS p2 WHERE p2.album=a.id ORDER BY p2.id DESC LIMIT 1,1) AS thumbUrl2,
(SELECT thumbUrl FROM lychee_photos AS p3 WHERE p3.album=a.id ORDER BY p3.id DESC LIMIT 2,1) AS thumbUrl3
FROM lychee_albums AS a
ORDER BY a.id;
```

The not working one (sadly `IN` doesn't use comma-separated values):

``` sql
SELECT SQL_NO_CACHE p.thumbUrl, a.id, a.title from lychee_photos AS p
LEFT OUTER JOIN lychee_albums AS a ON a.id = p.album
WHERE p.id IN (SELECT r.id FROM
(SELECT SUBSTRING_INDEX(GROUP_CONCAT(p2.id SEPARATOR ','), ',', 3) AS id, p2.album FROM lychee_photos AS p2 GROUP BY p2.album) AS r
WHERE r.album = p.album);
```
## The results

Testing the three firsts gave the following results (times are per round):

```
The old one:   1.54s
The nice one:  1.01s
The dumb one: >180s
Photos: 100000
Albums: 1000
Iterations: 50

---
The old one:  0.00785s
The nice one: 0.00481s
The dumb one: 0.0196s
Photos: 515
Albums: 11
Iterations: 1000
```

As expected, the dumb one is impossible to run because of the three subqueries. The nice one is a little bit faster than the old one but it surely could be better.
## The surprise

Interestingly, if we sort only on `lychee_albums.id/lychee_photos.album` and not on `lychee_photos.id`, the results are following:

```
The old one:  0.525s
The nice one: 0.306s
The dumb one: 0.0122s
Photos: 100000
Albums: 1000
Iterations: 50

---
The old one:  0.00621s
The nice one: 0.00407s
The dumb one: 0.00420s
Photos: 515
Albums: 11
Iterations: 1000
```

This time, the dumb one is blazing fast for large dataset. The downside is that the thumbnails aren't the three last photos.
Creating an index that takes both `lychee_photos.id` and `lychee_photos.album` has decreased the execution time to 5s for the sorted query (an incredible optimization with only one index btw) but it's still not enough. I currently don't have any idea to improve that again.
## The conclusion

So what do you think? Is it necessary to retrieve the three last photos, even if it's much slower (at least 1s vs 0.01s for the large dataset)?
## Edit 1

The nice one also return unsorted results on both cases, that's weird.
## Edit 2

The current selection retrieves in fact the three first photos of the album based on sorting settings.

**Comment by electerious** [comment]
Thanks a lot for doing some benchmarks! :)

> So what do you think? Is it necessary to retrieve the three last photos, even if it's much slower

Yes, as long as there's no way to set an cover photos. The current implementation also prefers starred photos. Lot of people are asking for a way to choose the cover thumb. We could drop the "retrieve three last photos based on photo-sorting AND prefer starred and shared photos"-sorting when this feature has been implemented. The way of implementation might also depend on what's better for Albums::get().

https://github.com/electerious/Lychee/issues/193

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
