### ISSUE TITLE
Customization through CSS

### ISSUE THREAD

**Issue by LiliwoL** [electerious/Lychee#616]
Hi, i'd like to customize lychee by modifying styles.
As it's a scss  (Sass?), i don't really know how it's compilated. 

Is it planned to allo users to add their own css file (through a simple @import user.css) ?

Thanks for your job.
N.

**Comment by qligier** [comment]
You can add your `@import` rule at the beginning of _dist/main.css_, it's the file containing the compiled SCSS.

**Comment by hrniels** [comment]
> Hi, i'd like to customize lychee by modifying styles.
As it's a scss (Sass?), i don't really know how it's compilated.

Please take a look at docs/Build.md.
