### ISSUE TITLE
Panel with destination albums while moving images in full screen view

### ISSUE THREAD

**Issue by hDoubleU71** [electerious/Lychee#618]
Would be nice to have a panel on the right side of the screen while moving images instead of the pop up window with the albums. So you can page through your images and click on the right side to move the displayed window directly into the other album.

So there should be a button on the upper right side to toggle a "Move to album" panel and then you can directly select the album where the display image is sorted to.

**Comment by electerious** [comment]
We already implemented an improved multi-select, which let's you select and modify individual photos. This feature should ship with one of the next major versions. Does this solve your problem? https://github.com/electerious/Lychee/issues/339#issuecomment-242972947

**Comment by hDoubleU71** [comment]
Sorry - but no. My meaning was of a panel shown with all albums while browsing through the images. No need of multi select, more a nice move option while showing the images in full screen.

**Comment by electerious** [comment]
An albums sidebar isn't planned. Maybe something that helps: You can click the album title in the header to switch between albums/photos. It's also planned to improving navigation between images (#365).
