### ISSUE TITLE
Only previeus button available when 'Photo Info' is opened.

### ISSUE THREAD

**Issue by sjorge** [electerious/Lychee#624]
Only the button to navigate to the previous image is available when the 'Photo Info' sidebar is opened.

![screenshot](http://i.imgur.com/Rh6sZ2v.jpg)

**Comment by ophian** [comment]
Well, this is the way I do it:

I added to view.js
```javascript
rightnavslider=function(){$('#imageview .arrow_wrapper--next').css('right','');$('#imageview .arrow_wrapper a#next').css('right','');if($('.sidebar.active')[0]!= null){$('#imageview .arrow_wrapper--next').css('right','350px');$('#imageview .arrow_wrapper a#next').css('right','350px');}},
```
right before:
```javascript
sidebar.toggle=function(){return!(!visible.sidebar()&&!visible.sidebarbutton())&&(header.dom(".button--info").toggleClass("active"),lychee.content.toggleClass("content--sidebar"),sidebar.dom().toggleClass("active"),rightnavslider(),!0)}
```
and called `rightnavslider` inside as shown.

This new function should be called in `photo.next = function(e) {` and `photo.previous = function(e) {` too.

Works good for me in all cases so far.
@electerious Maybe that helps to include this to the next lychee version.

And what about the prev/next navigation below 640px. Is there something touchable available on mobiles which I can't test with my desktop browser, or is it disabled for all?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
