### ISSUE TITLE
Improve auto-fullscreen delay

### ISSUE THREAD

**Issue by mhellwig** [electerious/Lychee#625]
In PR #583, a new behaviour was introduced that would cause the picture to switch to fullscreen if the viewer didn't move his mouse for >=1 second.

In my case, I need people (elderly relatives) to _always_ see the top bar with the title. I have for now achieved that for myself by commenting out the relevant part from that PR in view.js, but it would be nicer if there was a config switch in the DB to turn the auto-fullscreen off. Notably I wouldn't have to redo this after every update and rebuild lychee.

**Comment by jullit31** [comment]
+1 for that, also being able to adjust that 1 second delay would be nice.

**Comment by electerious** [comment]
A setting isn't planned, but we could increase the delay. I agree that 1 second might be too fast for some users.

**Comment by electerious** [comment]
The next version will use a 2.5s delay. 1 second was too aggressive.
