### ISSUE TITLE
Smart Albums based on Tags

### ISSUE THREAD

**Issue by guzzisti** [electerious/Lychee#628]
Hi,

as the tag handling seems to be revamped in 3.1.5, i´d like to see smart albums based on tags in a future version.
I could do the backend stuff (database and php), but as i´m not that familiar with js/css/andsoon, someone else would need to do the frontend...

Is there any interest in having smart albums based on tags?

kind regards

**Comment by Rurik19** [comment]
Yes, that would be great feature!

**Comment by omichalek** [comment]
yes, please!

**Comment by electerious** [comment]
Could be part of the proposed (Custom Smart Albums)[https://github.com/electerious/Lychee/issues/197] feature.
