### ISSUE TITLE
Albums Archive Zip

### ISSUE THREAD

**Issue by BenoitGEORGELIN** [electerious/Lychee#630]
### Detailed description of the problem

Is the albums archive deleted all the time ?
I can see for a big album, the zip archive is generated in data folder 
Looks like it is not delete.

What is the idea around downloading archives ? Is it suppose to generate an archive of the album, storing it to data folder, let the client download it and then delete the zip file
Or is it suppose to create the archive file once and reuse it for others downloads ?
- There is some concern here :  
  To Keep the ZIP archive file should be a good option to avoid multiple-creation of zip file (performance/io/disk) 
  - First guest downloading the archive will force the archive to be created
  - Others, will have the archive already ready to download 

If that's the case, there is important things to manage : 
- The album archive **name should not have the same name as the album name** 
  The zip archive should have a random name to avoid  data/album_name.zip access as this folder is not protected event for protected albums with password. 

Also, this folder data, should have by default an .htaccess file do avoid listing .

Thanks

**Comment by qligier** [comment]
Please take a look at #538,

**Comment by electerious** [comment]
> The zip archive should have a random name to avoid data/album_name.zip access as this folder is not protected event for protected albums with password.

Good point! Hardly depends on #538 and its solution. I'm not sure what's the best way.

**Comment by givre** [comment]
I would love to help more on the development side , but I'm not a php dev and It will take me too much time to understand the structure of the application , maybe I will give it a try for something simple.

About the Album Archive, here are some though that could help 

**1- Compress or not**
Lychee could have a quick look about the filename extension . 
If majority is JPG/JPEG  => no compression 
else => compression

So if PHP7 Is the only one (up to date) library , let's enable the possibility to create zip archive without compression if php version < 7 , using PhpZip library might be the only one option 

**2- Compression Method** 
Keep standard library compression with PHP is the more easy and portable solution 

**3- Privacy** 
I think the Zip archive should have a random name not based on the album title to avoid unwanted people to guess the name of the archive and use the data/ folder to download .
_( I spend some time to look about Lychee installation and I was able to find some users , with a bad apache configuration / no .htaccess allowing to browse the data folder with..  zip of some albums inside)  My Lychee instance never delete the zip file generated for my big album (1.2Gb)_ 

I also think that a protected folder should be generate a protected Zip archive with the same password as the album.  I case of direct access to the zip archive or zip archive folder, there a small security 

**4- Keep the zip or not** 
I would generate a zip archive with a random name (see previous point) and keep it in a folder like data/archives 
The archive will only be kept if the folder have more than configurable number (10 pictures for example) 
So the archive will only be generated by the first guest asking to download the album
If the album is modified , Lychee should delete the archive 

As an option, generating ZIP archive on demand  (by the admin) could be a nice option to have .
If I have 10 albums, big album and I wanna generate the archives before the first guest, so nobody will have to wait to generate it 
It's also great if I want to send the direct archive link to my friends/family and they will only need to know the password to unzip it. 
As an option, deleting ZIP archive on demand  (by the admin) could be a nice option to have .

**5- UI** 
When a guest wants to download an album,  an ajax message/ui should tell the user what's happening , specially for big albums 
It would be nice to get a message like "Generating Zip Archive, please wait....." and some real/fake progression  so the user knows that something is happening in background 

**6- New feature **
Select multiple pictures and download them as a zip file. 
If I want to download 20 pictures out of 100, this should be a nice option to Lychee

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
