### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by skyway22** [electerious/Lychee#631]
[Here](http://s6.postimg.org/6qtmrwhfl/screenshot_2016_10_08_at_01_19_44.jpg) i'm stuck. Creating data/config.php crashes my Lychee and goes to Server error or API not found.

**Comment by qligier** [comment]
Have you anything in PHP logs?

**Comment by skyway22** [comment]
some privileges to databse was wrong, now it's fixed, but i'm struggling to import. I'm trying to import from local folder but it only imports 135 photos... why?

**Comment by electerious** [comment]
We need more information before we can tell what's going wrong. Can you show us your PHP error log?
