### ISSUE TITLE
More filter options for starred images

### ISSUE THREAD

**Issue by wenzul** [electerious/Lychee#634]
I search for a webbased image gallery where I'm able to sort/select/rate images within an album. 

Following use case is imaginable: There are images from an event - some are pretty nice some aren't. I want be able to star (maybe more than a binary star system) my images. I want to show all 5/5 starred images to a friend.

Would this be feasible? Fits this requirement to this project?

**Comment by electerious** [comment]
Hey @wenzul, thanks for the idea. This issue sounds similar: https://github.com/electerious/Lychee/issues/310 Please feel free to add your use-case to the issue.

**Comment by electerious** [comment]
Also related to your problem: https://github.com/electerious/Lychee/issues/401
