### ISSUE TITLE
Request about the tags

### ISSUE THREAD

**Issue by valentin8709** [electerious/Lychee#635]
Hi everyone,
Would it be possible, after doing a tag search, to download the picture with a right-click? I can only download it when the pitcture is opened, but when I come back I am inside the folder picture and not inside my tag search so it's a bit annoying.

I don't know if I am very clear sorry =/

**Comment by electerious** [comment]
Yes, that's a good idea. Keep an eye on this issue. It's about the same feature: https://github.com/electerious/Lychee/issues/492
