### ISSUE TITLE
Display photos from Dropbox without importing/copying them

### ISSUE THREAD

**Issue by ldanicel** [electerious/Lychee#636]
Hi!

I was thinking for some time now... is it possible to just display the photos stored in a dropbox account without actually fetching them ?
I'm talking about querying the dropbox api for each picture, get an ID , store the ID locally and display the items matching them by that ID.
Thumbnails - I think dropbox has already generated thumbnails for each item - so this would make things easier for lychee overall as it doesn't have to generate its own thumbnails...
Of course it would be necesary to cache the thumbnails for example but that's not a stopper.

Anything I'm missing here?

**Comment by electerious** [comment]
Should be possible in some way, but it's nothing that would work with the current architecture. Lychee requires all photos locally and in a predefined structure. A medium-sized photo is also not possible without saving and I'm not sure if you can get the thumbnails via the API in the correct size/format.
