### ISSUE TITLE
Error when loading individual photo page directly

### ISSUE THREAD

**Issue by iangreenleaf** [electerious/Lychee#641]
### Detailed description of the problem

When loading an individual photo page without first visiting an album, a JS error occurs on page init, leaving a blank page. The errors look a little different in each browser console, so I'll paste them both here.

Chrome devtools:

```
main.js:6 Uncaught TypeError: Cannot read property '14775229774119' of undefined
(anonymous function) @ main.js:6
t @ main.js:6
init @ main.js:6
(anonymous function) @ main.js:5
o @ main.js:4
c @ main.js:2
fireWith @ main.js:2
o @ main.js:3
(anonymous function) @ main.js:3
```

Firefox console:

```
TypeError: album.json.content is undefined  main.js:6:30226
view.photo.photo<   http://lychee.iangreenleaf.com/dist/main.js:6:30226
t    http://lychee.iangreenleaf.com/dist/main.js:6:29736
view.photo.init    http://lychee.iangreenleaf.com/dist/main.js:6:28328
photo.load/<    http://lychee.iangreenleaf.com/dist/main.js:5:27801
api.post/o    http://lychee.iangreenleaf.com/dist/main.js:4:29617
ae.Callbacks/c    http://lychee.iangreenleaf.com/dist/main.js:2:6666
ae.Callbacks/u.fireWith    http://lychee.iangreenleaf.com/dist/main.js:2:7439
o    http://lychee.iangreenleaf.com/dist/main.js:3:10378
.send/n/<    http://lychee.iangreenleaf.com/dist/main.js:3:16233
```

As far as I can tell, it looks like the backtrace points to the minified version of [these lines](https://github.com/electerious/Lychee/blob/3eaaed72715b30bf10ce66a5f75268467bcb728d/src/scripts/view.js#L423).
### Steps to reproduce the issue

I can reproduce pretty consistently by clearing the browser cache and then loading an individual photo page as the very first page you load, for ex: http://lychee.iangreenleaf.com/#20/14492120069372

It seems to happen very frequently in v3.1.0+, and much less frequently in v3.0.9 (the above link is currently running v3.0.9 so you may not see the behavior there).
### Output of the diagnostics (Settings => Diagnostics)

403 forbidden, but that's not related to this, just a server permission I need to fix 😇 
### Browser and system

Firefox 49.0.2
Chrome 53.0.2785.89 (64-bit)

Server: Ubuntu Server 12.04

**Comment by electerious** [comment]
I'm sure it's a callback error. Something executes too early and required data is missing. I'm just not able to reproduce it.

**Comment by gdureuil** [comment]
Hello.

Digging up this old bug. I get it too, and pretty often when sharing single photos.

Sharing is at album level (public sharing).

Here is an example link : 

https://screenshots.baka-gamer.net/#14942520125249/15078392250445

How can i help to solve this bug ?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
