### ISSUE TITLE
Scaling of photos in portrait orientation

### ISSUE THREAD

**Issue by larzon83** [electerious/Lychee#642]
I encountered a view-problem when looking at photos taken in portrait orientation. If the browser itself is in portrait-orientation (viewport-width is smaller than height), the photo is kind of centered in the middle of the screen, not using all available height. Especially on a mobile phone the photo than looks tiny.

My photos are taken with a Canon EOS 5d mk III (2:3 aspect ratio). The sweet spot seems to a height of 2879px. Scaled down to this height, the image gets displayed correctly. If the image is scaled down to 2880px in height, it isn't displayed at full browser height.

I then tried to crop the "faulty" 2880 (2880 x 1920px) version in width. The resulting image (2880 x 1919px) works correctly.

It must be some calculation error.

Here are two screenshots showing the problem:
[lychee1.png](http://www.dominicschwarz.de/share/lychee1.png)
[lychee2.png](http://www.dominicschwarz.de/share/lychee2.png)

Here is a sample gallery:
[testalbum](https://fotos.dominicschwarz.de/#14780860484700)
Shrink your browser so that it is in portrait orientation.
1919x2879.jpg and 1919x2880.jpg are working.
1920x2880.jpg is showing the bug.

Also, I see this message in the log for each photo I upload:
`2016-11-02 12:49:32 - notice - Lychee\Modules\Photo::add (219) - Skipped adjustment of photo (1919x2880)`
What does this mean?

**Comment by qligier** [comment]
This has been discussed in #555
The _Skipped adjustment of photo_ message is thrown when the photo doesn't need to be rotated or the script has failed to rotate it.

**Comment by larzon83** [comment]
Anyone?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
