### ISSUE TITLE
Downloading a SmartAlbum results in crash

### ISSUE THREAD

**Issue by nebulade** [electerious/Lychee#652]
### Detailed description of the problem
When clicking on the Download Album button in a SmartAlbum (like Public), the request dies with:
```Undefined variable: album in /app/code/php/Modules/Album.php on line 258``` on the server.

### Steps to reproduce the issue
1. Add picture to the Public album
2. Click Download Album

### Output of the diagnostics (Settings => Diagnostics)
Serverlogs:
```
Undefined variable: album in /app/code/php/Modules/Album.php on line 258
```
Browser:
```
Error: Function not found! Please check the spelling of the called function.
```
### Browser and system
Firefox and Chrome
Lychee version 3.1.5 installed on Ubuntu 16.04

**Comment by electerious** [comment]
Fixed! Thanks for letting me know.

**Comment by nebulade** [comment]
Thanks for the quick fix. I can confirm that it works now.

Just to let you know, it was found during porting Lychee to https://cloudron.io/
