### ISSUE TITLE
htaccess IfModule mod_php

### ISSUE THREAD

**Issue by chainsawbeaver** [electerious/Lychee#653]
### Detailed description of the problem
.htaccess in base directory:
<IfModule mod_php5.c> will not work on servers running php7.
### Steps to reproduce the issue
Use server with php7.
### Error Message
php.ini error, upload_max_filesize
### Possible Fix?
Add section:
```
<IfModule mod_php7.c>
	php_value max_execution_time 200
	php_value post_max_size 200M
	php_value upload_max_size 200M
	php_value upload_max_filesize 20M
	php_value max_file_uploads 100
</IfModule>
```

**Comment by electerious** [comment]
Added it to the htaccess. Thanks for the tip!
