### ISSUE TITLE
 Error: No API function specified! on Upload

### ISSUE THREAD

**Issue by Silent-Party** [electerious/Lychee#657]
### Detailed description of the problem
When I attempt to upload a photo, I get an error after the upload has gone from 0-> 100% that states: “No API Function Specified” (you can see the error in the attached picture). However I am able to upload pictures through URL Upload. 

### Steps to reproduce the issue
1.	Click “+” in top right
2.	Select “Upload Photo”
3.	Select Photo to upload
4.	Upload proceeds normally from 0% -> 100%
5.	Error messeage appiers on screen, see attached screenshot.
![image](https://cloud.githubusercontent.com/assets/16393396/20773783/9534390a-b721-11e6-8944-a419e6cc8e56.png)

Console: 
![image](https://cloud.githubusercontent.com/assets/16393396/20773827/b2102854-b721-11e6-9b42-5ff3d5fd502f.png)

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1
Plugins:         

### Browser and system
Browser: Google Chrome 54.0.2840.99 m (64-bit)
System: Ubuntu 16.04 LTS
	Apache 2
	php7.0
	MariaDB

**Comment by Silent-Party** [comment]
Solved it by editing the correct php.ini file at /etc/php/7.0/apache2/php.ini , interestingly it did not show that the PHP filesize limit was the issue on files that where grossly over the limit, but on files that where just slightly over the limit it would error and advise increasing the limit in php.ini .

**Comment by electerious** [comment]
Glad you solved the issue and thanks for letting us know! Not sure why the error is missing when the file size is grossly over the limit.
