### ISSUE TITLE
Link Issue

### ISSUE THREAD

**Issue by thecodestudio** [electerious/Lychee#658]
I put a home button (Pic attached) to my lychee header which has to redirect the lychee page to my website home page, but when i give an anchor tag for example www.google.com to it , it always goes through the root folder and then the anchor link

For eg: 

`<li><a href="www.google.com">Home</a></li>`

but the link always takes me through the hosted server for eg : [www.example.com/lychee/www.google.com
i just want it to be www.google.com](url)

does this happen to be a Js issue where some defaults have been set to all the anchor links?

![1](https://cloud.githubusercontent.com/assets/24267659/20858563/4eb41678-b96d-11e6-803d-1c01e217904c.JPG)

**Comment by qligier** [comment]
You've to prepend `http://`, `https://` or `//` to your URL. That isn't a JS/browser/whatever issue, it's how it's designed to work (you can search for relative and absolute URIs).

**Comment by thecodestudio** [comment]
Well, that's pretty embarrassing.
Worked like a charm! , just added http:// in the beginning followed by the address.
Thank you so much @qligier
