### ISSUE TITLE
How can i use ImageMagick on 1and1 Server

### ISSUE THREAD

**Issue by mfgsc** [electerious/Lychee#665]
I would like to use Lychee on a 1and1 (1&1) web hosting server.
Except for the function of the medium picture size everything works very well.
What do I have to do that Imagemagick on a 1&1 webserver get to run.
In the help files of 1&1 I have found the following:
[http://hilfe-center.1und1.de/hosting/1und1-hosting-c10085285/skript--und-programmiersprachen-c10082634/php-c10082686/bedienung-c10082739/imagemagick-nutzen-a10791778.html](url)

This is my diagnostic output:

> Diagnostics
> -----------
> Warning: Dropbox import not working. No property for dropboxKey.
> Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
> No critical problems found. Lychee should work without problems!
> 
> System Information
> ------------------
> Lychee Version:  3.1.5
> DB Version:      030102
> System:          Linux
> PHP Version:     5.6
> MySQL Version:   50552
> Imagick:         -
> Imagick Active:  1
> Imagick Version: -
> GD Version:      bundled (2.1.0 compatible)
> Plugins:   

Many thanks for your help.
Christian

**Comment by benjaminpick** [comment]
The help that you link says: "Die PECL-Extension imagick ist bei 1&1 WebHosting-Paketen und Managed-Servern nicht installiert ."
So you would need to upgrade to "1&1 WebHosting Linux-Pakete, 1&1 Performance Hosting und Dedicated Server Managed" (which are a lot more expensive ...)

**Comment by benjaminpick** [comment]
(The commandline-Version of Image Magick (`convert`) would work, though ...)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
