### ISSUE TITLE
Photo import dialogs result in a console error

### ISSUE THREAD

**Issue by Klikini** [electerious/Lychee#667]
### Detailed description of the problem

Photo import dialogs do not open on Lychee 3.1.5.

The following console error appears:
```
main.js:1 Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover
    at Function.t.error (main.js:1)
    at PSEUDO (main.js:1)
    at y (main.js:1)
    at t.compile (main.js:2)
    at t.select (main.js:2)
    at Function.t [as find] (main.js:1)
    at fe.fn.init.find (main.js:2)
    at fe.fn.init (main.js:2)
    at fe (main.js:1)
    at Object.multiselect.show (main.js:3)
```

### Steps to reproduce the issue

Click on any of the import buttons in the menu.

![image](https://cloud.githubusercontent.com/assets/1693960/21463590/07352516-c931-11e6-9d9a-c397d7c71b3f.png)

### Output of the diagnostics (Settings => Diagnostics)

```
Diagnostics
-----------
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50631
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.1.1
Plugins:         
```

### Browser and system

**Client:** Google Chrome 55.0.2883.87 on Linux Mint 17.3 Cinnamon 64-bit
**Server:** nginx 1.9.3 on Ubuntu 15.10 64-bit

**User Agent**
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
