### ISSUE TITLE
Can't create new album using subfolders branch

### ISSUE THREAD

**Issue by KevinMitchell** [electerious/Lychee#672]
### Detailed description of the problem
I decided to try the subfolders branch as that feature would be very useful.  So I took my existing Lychee directory and removed everything except the data and uploads directories, and then substituted the latest sources from the subfolders branch.  Lychee seems to start up fine.  But when I try to create a new album it fails.  The error in the log is

error - Lychee\Modules\Album::add (39) 	- Incorrect integer value: 'false' for column 'parent' at row 1

Is this a known problem?  Is there something I'm supposed to reset when "upgrading" versions that I didn't do?

Thanks,

Kevin

### Steps to reproduce the issue
See above.

### Output of the diagnostics (Settings => Diagnostics)
iagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.2.0
DB Version:      030102
System:          Darwin
PHP Version:     5.6
MySQL Version:   50717
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         

### Browser and system
Problem with both Chrome and Safari under OSX

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
