### ISSUE TITLE
Problem : Server returned an unknown response.  Please take a look at the console of your browser for further details

### ISSUE THREAD

**Issue by krisken** [electerious/Lychee#676]
I just installed Lychee on my server, and I want to give it a try.  But when i want to upload one or multiple pictures, i get the error "Server returned an unknown response.  Please take a look at the console of your browser for further details".  It doesn't mather how I upload them : using the + mark above or drag/drop them.  Photos are norman JPEG photos.  Nothings special on them.

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
Error: PHP exif extension not activated

System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50629
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         

http://krisa.gallery/lychee/#

Browser is FireFox 50.1.0 on a Windows10 system.

**Comment by qligier** [comment]
You need to install/activate PHP's exif extension (as written in the diagnostics part).

**Comment by krisken** [comment]
When i visit the LOG page, I get these errors : 

2017-01-26 20:31:25 - error - Lychee\Modules\Database::createTables (180) 	- Table 'u0066_lychee.lychee_settings' doesn't exist
2017-01-26 20:31:25 - error - Lychee\Modules\Database::createTables (225) 	- Table 'u0066_lychee.lychee_albums' doesn't exist
2017-01-26 20:31:25 - error - Lychee\Modules\Database::createTables (248) 	- Table 'u0066_lychee.lychee_photos' doesn't exist

Question is ... why aren't these created?

**Comment by krisken** [comment]
I did install the exif extension (https://help.directadmin.com/item.php?id=252) but still it doesn't work?

**Comment by wildgus** [comment]
Have you checked uploads/ and uploads/import filesystem permissions?

**Comment by sabrinal79** [comment]
I'm having this same problem. The permissions of uploads/ and uploads/import are 777

**Comment by sabrinal79** [comment]
nevermind! I figured out that it was that I needed to download Godaddy's php5 . ini file and edit that. I was trying to bypass with a custom ini file and it wasn't working. Fixed now.

**Comment by hegemon2** [comment]
If you are using nginx, you MUST insert the following code within the http{} block of nginx.conf:
client_max_body_size 0; #max size disabled

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
