### ISSUE TITLE
Allowing all members to upload to Lychee gallery on forum

### ISSUE THREAD

**Issue by gitsex2** [electerious/Lychee#678]
Detailed description of the problem: I want to install Lychee on my forum and allow all members to upload photos to the forum Gallery using Lychee. Should be more elegant than users simply uploading attachments to individual posts... but I don't understand how to enable all users to use Lychee instead of just one user (me, forum Admin). Please advise. The forum software is MyBB.

Browser and system: Windows 10, some possibly Windows 8, Windows 8.1, whatever recent Mac OS

**Comment by SungMatt** [comment]
This issue has been discussed here. Please close and add your opinion in issue #132.
