### ISSUE TITLE
How to integrate Lychee with a forum?

### ISSUE THREAD

**Issue by gitsex2** [electerious/Lychee#679]
Detailed description of the problem: How do I install Lychee as a public Gallery on my forum? Forum software is MyBB.

Browser and system: Windows 10, some possibly Windows 8, Windows 8.1, whatever recent Mac OS

**Comment by SungMatt** [comment]
I don't think you would be able to directly link forum comments into Lychee. Your best bet is to just install lychee in a separate subdirectory, and directly link from there. Also, uploads are only enabled from the single user account, so you would have to share the admin password for uploads (eek!)

Your question could be more clear though. What were you expecting when you want to "install Lychee as a public Gallery"? Add as a plugin? Use as a direct linking method?
