### ISSUE TITLE
Server returned an unknown response.

### ISSUE THREAD

**Issue by kriskropd** [electerious/Lychee#680]
### Detailed description of the problem
Can't seem to get lychee to upload photos on an old Ubuntu server running php 5.6 (intentionally old php version). Didn't run into any issues getting the dependencies installed and Diagnostics doesn't alert me of any critical issues. I have uncommented all of the lines in provided .htaccess for "large files" according to the  FAQ https://github.com/electerious/Lychee/blob/master/docs/FAQ.md

### Steps to reproduce the issue
After selecting an image to upload photo from top-right menu. Seems to occur whether I grab image from disk or from a URL.

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50633
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      2.2.3
Plugins:         
```

### Browser and system
client: Chrome Version 56.0.2924.87 (64-bit)  on Macintosh 10.10.5
server: Ubuntu 14.04.4 LTS using php 5.6 acquired through http://ppa.launchpad.net/ondrej/php/ubuntu (downgrade for testing other php software)

```
==> /var/log/apache2/error.log <==
[Fri Feb 10 15:51:02.503597 2017] [:error] [pid 28585] [client 172.16.1.123:65427] PHP Fatal error:  Uncaught exception 'ImagickException' with message 'no decode delegate for this image format `/home/testserver/web/dev/kk-17/lytest/uploads/big/59d16398bc1005f6f94498814a5eeda0.jpg' @ error/constitute.c/ReadImage/544' in /home/testserver/web/dev/kk-17/lytest/php/Modules/Photo.php:313\nStack trace:\n#0 /home/testserver/web/dev/kk-17/lytest/php/Modules/Photo.php(313):
Imagick->readimage('/home/testserver...')\n#1 /home/testserver/web/dev/kk-17/lytest/php/Modules/Photo.php(226): Lychee\\Modules\\Photo->createThumb('/home/testserver...', '59d16398bc1005f...', 'image/jpeg', 1920, 1080)\n#2 /home/testserver/web/dev/kk-17/lytest/php/Access/Admin.php(234): Lychee\\Modules\\Photo->add(Array, '0')\n#3 /home/testserver/web/dev/kk-17/lytest/php/Access/Admin.php(44): Lychee\\Access\\Admin::uploadAction()\n#4
/home/testserver/web/dev/kk-17/lytest/php/index.php(71): Lychee\\Access\\Admin::init('Photo::add')\n#5 {main}\n  thrown in /home/testserver/web/dev/kk-17/lytest/php/Modules/Photo.php on line 313, referer: http://172.16.1.237/dev/kk-17/lytest/
```

Chrome console - not sure it's very helpful
http://i.imgur.com/NjzFb3f.png

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
