### ISSUE TITLE
Request - How to shorten the URLS?

### ISSUE THREAD

**Issue by WreckRox** [electerious/Lychee#682]
The urls are soo big, is there any way to shorten them automatically ?
PS: On ubuntu 16.04 and apache

**Comment by LudovicRousseau** [comment]
Do you have an example of a "long" URL?
In my case I have URL like: https://site/Lychee/#8/14318903069976
What would be a shorter URL?

**Comment by WreckRox** [comment]
@LudovicRousseau https://i.wreckroxd.gq/i/i/big/7c22700a1de6ede2e4a721bc2af8b6e8.png 

Like this for example, its huge, I want something short like an imgur link http://i.imgur.com/i5zaQ5D.png

**Comment by WreckRox** [comment]
Bump

**Comment by ekianjo** [comment]
Just curious @WreckRox but why do you need this? Are there cases where you need to type the address?

**Comment by ramonakira** [comment]
I agree it would be nice to have prettier urls, so instead of http://site/#14982936537540/14990607674016 something like http://site/<slugified-album-title>/<slugified-photo-title>

**Comment by peterberbec** [comment]
Maybe [YOURLS](https://yourls.org/) integration? I run a private YOURLS server in addition to Lychee.

pix.berb.ec/#15022661159797/15022669376570 turns into berb.ec/smiley

The share photo button already has Twitter Facebook ... Direct Link. Might not be too hard to add Direct Short Link

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
