### ISSUE TITLE
why is it so cryptic to create a new album ?

### ISSUE THREAD

**Issue by phil123456** [electerious/Lychee#688]
### Detailed description of the problem

I been digging the menu but I cant find any way to create a new album

also, most infos supposed to show as I click on an image, dont show up
there is only a top menu to rename the image

why all of these are not default ? why is it so cryptic ? 

### Browser and system

**Comment by matunixe** [comment]
Hahaha, GTFO troll. 👍

**Comment by electerious** [comment]
¯\_(ツ)_/¯

**Comment by phil123456** [comment]
there are way better options than this lychee crap 
sorry
