### ISSUE TITLE
Clicks on navigation buttons don't properly register in IE

### ISSUE THREAD

**Issue by tackturn** [electerious/Lychee#690]
Hello,
I have found what I think is a bug in Lychee.  In Internet Explorer I noticed that if you use the navigation buttons and you click exactly on the triangle that appears, it does not register the click.  If you click just outside of the symbol but still within the box it will advance.  I've tested this behavior in Firefox and Chrome and it looks like it works ok in those browsers.  I've just found the issue with IE.  Also with IE, after clicking around for a while it appears that Javascript stops responding to mouse clicks and the features like the picture stack fanning when mouseover or the navigation buttons appearing on mouse move stop working.  I can still advance forward and back with the keyboard but no mouse. Once this happens a refresh of the browser window returns the functionality until it happens again.  No errors appear in the debugging console in IE either.  I have tested this with Windows 7 and 10 on my site as well as your demo site.

Other than that, I love Lychee.  It's simple and ticks most of the boxes.  Best of all, it doesn't remind me of 1990's Geocities like some other notable galleries. :)

If I may also suggest a feature.  It would be nice to be able to pin the EXIF data and still have access to the navigation buttons.
Thanks
Shawn

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
