### ISSUE TITLE
Original file extension case should not be respected 

### ISSUE THREAD

**Issue by yuukieve** [electerious/Lychee#699]
### Detailed description of the problem
When uploading an image to Lychee, the case of the file extension will be kept despite the rest of the image name being switched to lowercase. So if you upload, for example, "imAGe.PNG", it will become "hash.PNG" and "hash.png" will 404. It would be more standard to convert the file extension to lowercase automatically like most image hosts. This is because renaming the images to lowercase names manually is not an option on some clients like iOS, whose Photos app images will always be in the format "IMG_0000.EXT". 
### Steps to reproduce the issue
Upload any image with an uppercase file extension, grab the direct link, note the incorrect case. 
### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.2.0
DB Version:      030102
System:          Linux
PHP Version:     7.1
MySQL Version:   50554
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      2.2.3
Plugins:
```
### Browser and system
All, tested on desktop Chrome, Edge, iOS Safari, etc.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
