### ISSUE TITLE
Insecure by default

### ISSUE THREAD

**Issue by quixoticgeek** [electerious/Lychee#700]
### Detailed description of the problem

The instructions for installing lychee say:

"Change the permissions of uploads/, data/ and all their subfolders. Sufficient read/write privileges are required.

chmod -R 777 uploads/ data/"

Permissions 777 is collossally bad on any multi user system. The fact that it is advised in the install by default is even worse. 
### Steps to reproduce the issue

Open web browser, goto:

https://github.com/electerious/Lychee/blob/master/docs/Installation.md

**Comment by electerious** [comment]
The problem is that most users don't know how to choose permissions correctly. The readme uses 777 to prevent people from opening issues because of incorrect permissions. I guess the text should be updated to inform that 777 isn't a good choice. PR welcome.

**Comment by Hikari-chin** [comment]
@electerious Could you add a "recommended permissions" portion, maybe? Read/write access should be given to the user Lychee is running under, right? This would usually be www-data or nginx on some systems.

**Comment by philwig** [comment]
It depends what you think you're trying to defend against.

In a shared host (say Rackspace) you absolutely *do not* have a shared file system in the way the OP appears to suggest. The only access to the file system is from the web server, which is restricted to the one user they automatically create for you, and any ftp users you create. 

In this case 777 does the job and is simple. If you can break in here with some random user then you can easily tweak a few file permissions. I've never used hosting where the file system was "shared" in that sense. 

I'd leave it the way it is.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
