### ISSUE TITLE
Importing images trows JS-Error after 1-2 minutes => stops import

### ISSUE THREAD

**Issue by LordSimal** [electerious/Lychee#705]
### Problem
After copying all my images to the import folder (<lychee-app>/uploads/import/) i can import a few images, but after some time a JS-Console Error shows up, thus stopping the importer and showing folowing error in the JS-Console:

```
Object {description: "Server error or API not found.", params: Object, response: SyntaxError: Unexpected token < in JSON at position 0 at parse (<anonymous>) at Z (https://f…}
description : "Server error or API not found."
params : 
  albumID : 0
  function : "Import::server"
  path : "/www/htdocs/<some-path>/<some-path>/<some-path>/uploads/import/"
response : 
  SyntaxError: Unexpected token < in JSON at position 0 at parse (<anonymous>) at Z (https://<some-domain>/dist/main.js:1:12499) at o (https://<some-domain>/dist/main.js:3:12161) at XMLHttpRequest.<anonymous> (https://<some-domain>/dist/main.js:3:17338)
  message : "Unexpected token < in JSON at position 0"
  stack : "SyntaxError: Unexpected token < in JSON at position 0↵    at parse (<anonymous>)↵    at Z (https://<some-domain>/dist/main.js:1:12499)↵    at o (https://<some-domain>/dist/main.js:3:12161)↵    at XMLHttpRequest.<anonymous> (https://<some-domain>/dist/main.js:3:17338)"
```

Unfortunately, the importer stopped obviously, because i checked in a different window if some thing happens.
And the importer window doesnt change in the initial tab (not showing the user, that something is wrong). 

My images folder contains several subfolders with >1000 images (dont know the exact count)

### Steps to reproduce the issue:

1. Copy all files, which should be imported to the <lychee-root>/uploads/import Folder
2. Log in to lychee
3. Go to "Add" on the top right corner
4. Go to "Import form Server"
5. Click "Import" and wait 1-2 minutes. Then check your JS-Console in the browser

### Diagnostics:

```
System Information
------------------
Lychee Version:  3.1.5
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50633
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      bundled (2.1.0 compatible)
Plugins:         
```

### Browser and system:
Windows 10 Pro x64
Chrome: 58.0.3029.110
PHP: 7.1.1(Apache)

**Comment by LordSimal** [comment]
I recognised that im not running the newest version.
I updated to 3.1.6 but still the same problem.

**Comment by donutmonger** [comment]
Is there anything of note in the logs? accessible at Lychee/plugins/Log

**Comment by LordSimal** [comment]
`
2017-05-25 23:31:26 - error - Lychee\Modules\Import::server (162) 	- Could not create album in Lychee ()`
`
2017-05-25 23:31:26 - error - Lychee\Modules\Album::add (39) 	- Duplicate entry '14957478869800' for key 'PRIMARY'
`

**Comment by JackKuo-tw** [comment]
same problem in my Raspberry Pi 3 with Debian 9.4
But my PC Ubuntu 18.04 works fine
Both of them run PHP7.2, and I try PHP7.0 in Pi still got the problem

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
