### ISSUE TITLE
One Computer Blocked? 

### ISSUE THREAD

**Issue by TriBeard** [electerious/Lychee#718]
### Detailed description of the problem

I tried to upload several folders at once from my desktop at home at once and the upload didn't complete successfully. I closed out of the session and didn't think much of it. Now however, I cannot upload anything from that computer. Other computers on the same network work fine, and externally I can upload anything from another computer, but from that one lychee just gives me an error as below: 

![image](https://user-images.githubusercontent.com/13950156/28168253-7993b45a-67ac-11e7-8a14-dd0d9923bee3.png)

This problem occurs in IE, Firefox and Chrome. 

### Steps to reproduce the issue

Occurs whenever I try to upload a file from that one particular computer

### Output of the diagnostics (Settings => Diagnostics)

![image](https://user-images.githubusercontent.com/13950156/28168199-528f1ed0-67ac-11e7-83f4-810f54d249e9.png)

### Browser and system

Windows 10
Firefox, IE and Chrome all show issue

**Comment by apsarapea** [comment]
Same thing happened with me on Safari and Chrome. My error message reads:

"No API function specified! Please take a look at the console of your browser for further details."

This script looked promising and I was looking forward to integrating it with my website. Hope someone can help and point us in the right direction. 

Best,

apsarapea

**Comment by apsarapea** [comment]
I had the same problem and realised later that there is a php limit on uploads set by my hosting. I managed to change the limits in cpanel. Just navigate to the “Software/Services” section in cpanel & select “Select PHP version” and set to current then update the file upload limit, save and it should work.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
