### ISSUE TITLE
No update available message on 3.1.5. UpdatePath file outdated.

### ISSUE THREAD

**Issue by woderkant** [electerious/Lychee#719]
### Detailed description of the problem
Sing In dialog doesn't show the `Update available!` message on Lychee 3.1.5.
### Steps to reproduce the issue
On Lychee version 3.1.5, when not logged in, click on the top left icon to open the Sign In/Login dialog.
### Solution
Update the file http://update.electerious.com/index.json (updatePath) to `"version": 30106`.

**Comment by electerious** [comment]
Fixed! Thanks for letting me know.
