### ISSUE TITLE
some images from Samsung S7 cause false error and do not appear in web client

### ISSUE THREAD

**Issue by CptCap** [electerious/Lychee#723]
### Detailed description of the problem
It looks as though some images taken through my samsung S7's camera give a false positive error and will not allow the imaged to be displayed on the web client.
I can upload screenshots from this phone just fine, and even got a 40MB panoramic uploaded without error, but 'standard photos' (being 12 megapixel in 4:3, setting on auto) I get an error in the browser even though I can navigate to the Big folder and see the image has uploaded just fine.

the message given to my S7 is "Could not save photo in database! Please take a look at the console of your browser for further details."

when I take the same image and upload it through my PC and look in console I get an error from main.js:5 
description
:
"Upload failed. Server returned an error!"
readyState
:
4
response
:
""Error: Could not save photo in database!""
responseText
:
""Error: Could not save photo in database!""
responseType
:
""
responseURL
:
"http://192.168.1.205/lychee/php/index.php"
responseXML
:
null
status
:
200
statusText
:
"OK"
timeout
:
0
lychee.error @ main.js:5
l.onload @ main.js:6

I have looked through the FAQ and have adjusted all recommended parameters in php.ini, the only one that I couldn't find is upload_max_size, which I added. I did find all the others and even boosted parameters a bit higher. nevertheless it's strange I got that 40MB panoramic to upload, which was taken from the same camera. could be something to do with Metadata?? i'm afraid i'm new to web development and have only scratched the surface on how image files store data. I will mention I actually have getagging and some other metadata settings simply turned off on the phone.

I plan to use Lychee for my wedding guests to upload their files to my PC directly over localnet. likely users will be uploading groups of 20 or more files from their phones at any given time, which is why my php.ini params are boosted around the 200M range

### Steps to reproduce the issue
snap an image or upload one from my Samsung Galaxy S7

### Output of the diagnostics (Settings => Diagnostics)
here's the error in Lychee's log.
error - Lychee\Modules\Photo::add (243) 	- Incorrect integer value: '' for column 'width' at row 1

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: PHP zip extension not activated

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50719
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1
Plugins:
### Browser and system
any browser or OS, this is image-specific. attempted Ubuntu 16.04 with Firefox (Lychee host system on VM) Windows 10 using Vivaldi (chromium based) (VM host system) and Android 7.0 chrome

I'm afraid I'm pretty new to apache and PHP, I'm hoping it's a simple oversight on my part. any help would be appreciated.

**Comment by sdc011** [comment]
Bump. Does anyone else have this issue, I just started getting this error.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
