### ISSUE TITLE
List of deleted photos?

### ISSUE THREAD

**Issue by peterberbec** [electerious/Lychee#726]
### Detailed description of the problem

When Lychee deletes a photo, does it scrub it completely from the database, or is it possible to get a list of deleted pictures?

### Steps to reproduce the issue

Delete a photo.

### Output of the diagnostics (Settings => Diagnostics)

n/a

### Browser and system

Chrome browsing to a Ubuntu 16.04 server.

### Rational

I have enabled an S3 system, sorta :). 

I have two additional upload directories - `uploads.local` and `uploads.s3`. Local is stored on the ec2's hard drive. S3 is a read-only rclone fuse mount of an S3 bucket. I then use unionfs to mount `uploads.s3`+`uploads.local` onto `uploads`. 

When a file gets uploaded, unionfs stores it on the local file system, since the s3 directory is read-only. A cron job runs every minute and moves all files in the `uploads.local` directory into the s3 bucket.

The problem is, you can't delete a file from the s3 bucket this way. I want to keep the s3 bucket read-only. If there was a way to extract deleted photos from the database somehow, or from a log file, I could clean them up manually. I don't mind if I have to grep a log file somewhere, I just need a list of deleted pictures.

Is this possible?

Sidebar: I needed to do the unionfs mount because rclone's S3 fuse file system doesn't support opening files as read/write. If Lychee didn't do this, I could just mount the S3 bucket directly. Is read/write needed for resizing the images?

Thanks for an amazing product. It's amazingly well-put together.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
