### ISSUE TITLE
Images not being rescaled

### ISSUE THREAD

**Issue by rogboyce** [electerious/Lychee#728]
Hi, 

When I upload fairly large photos (4032 x 3024) they don't appear to be rescaled by Lychee. In a previous post I read: "Lychee scales big photos down so they fit into 1920x1080 (when ImageMagick is installed).". But my photos are obviously the same size after upload because they are slowish to load in the gallery and when I right-click and save one it saves it as the same dimensions as the original image. Photos are also not being rotated.

As far as I know ImageMagick is installed. Here is the information in the Diagnostics section of Lychee:

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50717
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by hadret** [comment]
uhm, the way I see it, imagemagick is not installed and not picked up by Lychee. here's an example output from the working config: 

 ``` 
System Information ------------------ Lychee Version: 3.1.6 DB Version: 030102 System: SunOS PHP Version: 7 MySQL Version: 50505 Imagick: 1 Imagick Active: 1 Imagick Version: 1795 GD Version: 2.2.4
```

**Comment by rogboyce** [comment]
Thanks for that, I'm waiting now to hear back from my host as to whether they can ensure it is installed

**Comment by rogboyce** [comment]
Just to update you on my progress with that: I asked my host to install ImageMagick which they did but it still didn't show in the Lychee diagnostics that it was active. So I got back to them and suggested I might need both Imagick and ImageMagick installed. They then got back to me and said that they had managed to successfully do that by adding a custom php.ini file with the following line: 
extension=imagick.so 

Apparently it was not working correctly on php 7.0 so they changed it to 5.6 and then it showed imagick as installed. 

So it all works great now part from the fact that if you upload a photo that's the wrong way up it won't rotate it to the right way. 

Should Lychee automatically detect when a photo is not the right way up and change it or is that something planned for the future?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
