### ISSUE TITLE
EXIF orientation

### ISSUE THREAD

**Issue by lljoerne** [electerious/Lychee#731]
### Detailed description of the problem
When uploading photos via browser, EXIF orientation of photo is respected. All is fine.
When uploading phots via _lycheeupload_ or importing with _Import from Server_ option, the orientation of photo is not respected. All photos appear in landscape orientation.

### Steps to reproduce the issue
lycheeupload, Import from Server

### Output of the diagnostics (Settings => Diagnostics)
python lycheeupload.py -v -d /external_disk/data31/data26/xxxxx/xxxxxx-neu/yyyyy-Wolken-RV xyz@192.168.x.zz:/external_disk/data32/fotos-server/

`xyz@jw03:~/lycheeupload $ python lycheeupload.py -v -d /external_disk/data31/data26/xxxxx/xxxxx-neu/yyyyy-Wolken-RV xyz@192.168.x.zzz:/external_disk/data32/fotos-server/
           
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
Password: 
Connected to 192.168.x.zz
INFO: Connected to database localhost
Uploading photos...
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpiq55EW
DEBUG: Uploaded file tmpDnGjJS
DEBUG: Uploaded file tmpyXfEmt
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7869.JPG
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpxIqJod
DEBUG: Uploaded file tmpeT0ROP
DEBUG: Uploaded file tmpiHY8kK
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7873.JPG
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpMOVDzD
DEBUG: Uploaded file tmpnnWC2c
DEBUG: Uploaded file tmpK9zjXe
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7868.JPG
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpcOq3tu
DEBUG: Uploaded file tmp7KpY0B
DEBUG: Uploaded file tmprXmYCY
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7879.JPG
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpMcFbz8
DEBUG: Uploaded file tmpvZf0O7
DEBUG: Uploaded file tmpMDRup7
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7870.JPG
DEBUG: Original size: 5184x3456; New size: 1920x1280
DEBUG: Uploaded file tmpnwvZqv
DEBUG: Uploaded file tmpXyhW3i
DEBUG: Uploaded file tmppTj29O
INFO: Uploaded file 2017-07-Jul-01-Wolken-RV/IMG_7866.JPG
6 out of 6 photos imported`

### Browser and system
Firefox ESR, 52.3.0 (32-Bit)

see also:
#725

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
