### ISSUE TITLE
How to allow public to use tag search function?

### ISSUE THREAD

**Issue by whfletcher** [electerious/Lychee#738]
### Issue 
I have tagged various photos with descriptive labels.  I'd like public users to be able to search on tags and / or photo titles to find relevant images as other gallery systems allow.  Unless the user is logged in the search box is invisible. I tried copying it to different header sections but that did not work.

Any workarounds?  I'd be glad to edit index.html or customize css or js files if I knew I wasn't messing anything up.

### To replicate
Log out and the "Search" box disappears from the "Albums" page.  Log in again and it's back. 

### Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems with the Dropbox- and URL-Import. Edit your php.ini and set allow_url_fopen to 1.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1-dev
Plugins:         

### Browser and system

Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Same story wit MS Edge browser.

**Comment by whfletcher** [comment]
###More info on issue

Editing index.html, if I copy the search box HTML 

>`<input class="header__search" type="text" name="search" placeholder="Search â€¦" >`
>`<a class="header__clear">&times;</a>`
>`<a class="header__divider"></a>`

from the admin toolbar DIV

>`<div class="header__toolbar header__toolbar--albums">`

to the corresponding public DIV

>`<div class="header__toolbar header__toolbar--public">`

the search box appears whether I am logged (admin) in or not (public).  However, when I enter text in the search box in admin mode, each character disappears after I enter it and nothing else happens.  In public mode it raises the following error:
>*Error: Function not found!  Please check the spelling of the called function.*

There should be a way to assign the appropriate function to the search box in public mode and to make it behave correctly in admin mode.  Any suggestions?

**Comment by rcastillogarcia** [comment]
You need add "search" function to "Guest.php" file. You can see the code in "Admin.php" and copy it to "Guest.php".

**Comment by tribut** [comment]
Would be great if an option for that existed!

**Comment by rcastillogarcia** [comment]
I have implemented it. It's very simple. Simply copy "search" function from "Admin.php" to "Guest.php". I upload the code as soon as I can.

**Comment by whfletcher** [comment]
¡Mil gracias, rcastillogarcia!

For those who are waiting for the code, this is what I did:
In file `php/access/Guest.php` I copied the two blocks of code from `php/access/Admin.php`  (see my comments after `//COPIED `)

```php
	public static function init($fn) {

		switch ($fn) {

			// Albums functions
			case 'Albums::get':       self::getAlbumsAction(); break;

			// Album functions
			case 'Album::get':        self::getAlbumAction(); break;
			case 'Album::getPublic':  self::checkAlbumAccessAction(); break;

			// Photo functions
			case 'Photo::get':        self::getPhotoAction(); break;

			// Session functions
			case 'Session::init':     self::initAction(); break;
			case 'Session::login':    self::loginAction(); break;
			case 'Session::logout':   self::logoutAction(); break;

			// $_GET functions
			case 'Album::getArchive': self::getAlbumArchiveAction(); break;
			case 'Photo::getArchive': self::getPhotoArchiveAction(); break;

                        // COPIED Search function  from Admin.php 26 Oct 17 per rcastillogarcia_
			case 'search':                  self::searchAction(); break;
                      // END COPY
		}
		self::fnNotFound();
	}

	// COPIED Search functions from Admin.php 26 Oct 17 per rcastillogarcia
	private static function searchAction() {
		Validator::required(isset($_POST['term']), __METHOD__);
		Response::json(search($_POST['term']));
	}
       // END COPY
```

**Comment by shaneashford** [comment]
This works great for me @rcastillogarcia and @whfletcher. Thanks for the code! I'm also wondering how to add the search functionality to the album pages and how to search within albums. Do you know if this is possible?

**Comment by fly-man-** [comment]
@whfletcher Can you stil replicate this with the current version of Lychee ??

**Comment by mmelon** [comment]
I am also looking for a working public search pls

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
