### ISSUE TITLE
Downloading Albums >500 MB

### ISSUE THREAD

**Issue by gargatsh** [electerious/Lychee#759]
The issue I'm addressing here is that album downloads (zipped) of a size above roughly 500 MB fail.
The zip archive is not created. In lychee's data folder I see broken zip archives for every attempt to download a specific album of sizes ranging from 400-550 MB. Lychee produces a time-out after 40-50 seconds with script error 500. I read about similar issues here but haven't discovered a solution yet. I have set the settings in PHP.ini to the values suggested in lychee's installation.md, namely:
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 20M
memory_limit = 256M
I have also tried to further increase these values which didn't produce different results. The diagnostics output doesn't show any issues in this regard.

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:    3.1.6
DB Version:          030102
System:                Linux
PHP Version:        5.6
MySQL Version:   50619
Imagick:               1
Imagick Active:    1
Imagick Version:  1794
GD Version:          bundled (2.1.0 compatible)
Plugins:

The issue is consistent across different browsers. I have tried current versions of Opera, Edge and Firefox.

Thanks for any advice. Michael

**Comment by GjjvdBurg** [comment]
I had a similar issue (but error 504), increasing the ``default_socket_timeout`` value in the php.ini file solved my problem. Maybe that helps?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
