### ISSUE TITLE
Multiple file upload not working correctly for old android and chrome browser versions

### ISSUE THREAD

**Issue by chrobs** [electerious/Lychee#760]
### Detailed description of the problem
When using Lychee's 'Upload Photo' functionality on an older smartphone with chrome, it is not possible to upload multiple photos at once - even if multiple photos could be selected.

Using the Samsung Samsung S4 Mini with Android 4.4.2 (Chrome browser 62.0.3202.84) and S5 Mini with Android 6.0.1 (Chrome browser 62.0.3202.84), the shown android dialog after selecting 'Upload Photos' only shows the default gallery and the camera. Using the gallery, it is not possible to select more than one picture at once (I know that this is the app's behavior and not Lychee's fault).

Using the Nexus 5 with android 6.0.1 and Chrome browser 62.0.3202.84, I'm able to select multiple files within the default gallery app, but only the latest one is uploaded. Looking at the server side, I only see one HTTP POST request to index.php which indicates that it may be again a problem of the android app.

In all three cases a user is not able to upload multiple files at once from the respective mobile phone which results in a very annoying amount of work ;)

Looking at the code, it turns out that the following HTML code in [_index.html_](https://github.com/electerious/Lychee/blob/8b2c07861d0d09b30b18b6ec196959da58ddba89/index.html#L137) is responsible for the upload dialog and gives Android an indication which apps the user is able to choose from:
`<input id="upload_files" type="file" name="fileElem[]" multiple accept="image/*">`
And this correctly addresses all image media files according to HTML5. But it seams to be the case, that the referenced android versions (and respective versions of the used chrome browser) does not handle the _accept="image/*"_ correctly.

The value of the _accept_ is specified as follows:
> The value must be a comma-separated list of unique content type specifiers

Therefore, it is a workaround for me to use the following value of the accept attribute:
`accept=".jpg,.jpeg,image/*"`
Resulting in the following input element:
`<input id="upload_files" type="file" name="fileElem[]" multiple accept=".jpg,.jpeg,image/*">`
This results on the Samsung S4 and S5 mini phone in showing "Documents" or "My Pictures" in the presented android dialog after selecting 'Upload Photos". Using the Nexus 5, the android dialog is still the same, but the multiple upload works now correctly.

### Steps to reproduce the issue
Using one of the following mobile phones and try to upload multiple files at once using the "Upload Photo" button:

* Samsung Samsung S4 Mini with Android 4.4.2 and Chrome browser 62.0.3202.84
* S5 Mini with Android 6.0.1 and Chrome browser 62.0.3202.84
* Nexus 5 with android 6.0.1 and Chrome browser 62.0.3202.84

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics:
Warning: Dropbox import not working. No property for dropboxKey.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information:
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50505
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      2.2.4
Plugins:         

### Browser and system

Multiple mobile phones with different android versions, see above

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
