### ISSUE TITLE
[feature request] Zooming of photos

### ISSUE THREAD

**Issue by tekk** [electerious/Lychee#762]
Hi, first of all, thank you for your hard work on this amazing project. 👍 🥇 
Just a question - I looked at the docs and haven't found any keyboard shortuct to zoom image in/out.
If this is not implemented yet, would it be possible to add this feature?
I have datasheets as images and they're very hard to read in fullscreen mode.
I would need to zoom it in.
Thank you. 👍

**Comment by fly-man-** [comment]
@tekk Would it be that you want a zoom-able image when you click on it or that it opens as a separate window in which you can use the normal zoom function that comes with a browser (Ctrl-Mouse scroll wheel)

**Comment by tekk** [comment]
@fly-man- It doesn't work - at least on Chrome. Try yourself.

**Comment by fly-man-** [comment]
@tekk I know it doesn't work. I was asking what would be your choice in having the zoom work.

**Comment by tekk** [comment]
@fly-man- It looks like here: https://1drv.ms/u/s!Asev3XxUh8b_n5NC9I-CJnZxddgYQw

**Comment by fly-man-** [comment]
@tekk I will have a look what I can come up with as zoomable

**Comment by tekk** [comment]
@fly-man- I apologize, I didn't understood your question. I'm not a native speaker and my english is poor.
In my opinion, simple shortcuts like A/Z to zoom in/out and cursor keys + mouse to pan. It would be awesome. Anyways, I figured out a workaround - when you open direct link to image in separate tab, you can zoom in and scroll.

**Comment by ilias-sp** [comment]
Just to add one more "vote" for the need of a zoom feature (any implementation i guess). It would be very convenient!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
