### ISSUE TITLE
Can't use IFRAME html in sites

### ISSUE THREAD

**Issue by matanmn33** [electerious/Lychee#767]
Hi everyone,
I'm designning right now a new WordPress Theme for my self website and i'm tring to embed my Lychee site.
I'm using iFrame to do it and JS to take the height of the iframe. its all work but the content show up above all of my elements in the site.

Using Google Chrome and its all up on my locahost right now using WAMP.

Here the Code Preview:

`			<script>
			function setHeight() {
			parent.document.getElementById('iframemanga').style.height = document['body'].offsetHeight + 'px';
			}
			</script>
			
			<style>
			iframe {
			width:100%;
			}
			</style>
		
		<iframe id="iframemanga" frameborder="0" scrolling="no" onload="setHeight('#iframemanga')" src="http://localhost/m/"> </iframe>
		`

![v_ozerhwtkeg5xhkolvlla](https://user-images.githubusercontent.com/36113282/35770758-f0986342-0929-11e8-8c33-87728109f9a3.png)

**Comment by alainstudio** [comment]
I would recommend, NOT to use iframe, but create a sub-domain gallery.yourdomain for Lychee and link your MENU with website ... it will work a lot faster and less bugs... that what i did for my church website

**Comment by matanmn33** [comment]
I would like to do but i think its not very usefull cuz i wanna use my site template and style, if i will try to style Lychee itslef it will bugged for RTL Direction and self-style, i already tried it.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
