### ISSUE TITLE
Backup/Restore albums

### ISSUE THREAD

**Issue by davidsbatista** [electerious/Lychee#768]
Say that I want to change hosting, and move everything into a new machine, what are the best practices/step-by-step instructions to move all the albums to the new host? 

Is it enough to:
* copy /var/www/html/Lychee into new host
* dump MySQL Lychee database into a file and then restored it in a new host?

Or is there a more systematic/bullet-proof process of doing this ?

Thanks,
David

**Comment by ilias-sp** [comment]
i would:

- dump mySQL and import to new server. 
- copy the uploads folder from old to new server. (or the whole Lychee installation)

dont see any reason to be more complicated than that.

**Comment by davidsbatista** [comment]
fair enough! thanks for the reply :)
