### ISSUE TITLE
Can't connect to database?

### ISSUE THREAD

**Issue by Sir-Teabag** [electerious/Lychee#769]
### Detailed description of the problem

I've followed a video exactly how they do it and it works for them and not myself. After following a different tutorial I'm still getting the exact same error.

### Steps to reproduce the issue

I've created a new database with different credentials, looked through the different settings that came int he files of the git and looked up for people having the same issue.

### Output of the diagnostics (Settings => Diagnostics)

Sorry but I'm not 100% sure what this is exactly or how to access it. Could you elaborate? Here is a screenshot of my error https://gyazo.com/16bba202fda8917ec6bc5994c910f658 

### Browser and system

My laptop: Windows 10 with Opera browser.
My VPS: 

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by Sir-Teabag** [comment]
Error log displays 
2018-02-18T12:46:42.104308Z 8 [Note] Access denied for user 'gallery'@'localhost' (using password: YES)

**Comment by ilias-sp** [comment]
hi Sir-Teabag,

connect to mysql as root and run:

GRANT ALL PRIVILEGES ON <the db name you created>.* TO 'gallery'@'localhost';

thanks

**Comment by Sir-Teabag** [comment]
Thank you for getting back to me :)

I tried what you said above and got this error


mysql> GRANT ALL PRIVILEGES ON .* TO 'gallery'@'localhost';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* TO 'gallery'@'localhost'' at line 1
mysql>

**Comment by ilias-sp** [comment]
hi!

it looks like you didnt provide the DB name in that command, please see an example. Assuming  the DB name is LYCHEE_DB, the command to use is:

GRANT ALL PRIVILEGES ON LYCHEE_DB.* TO 'gallery'@'localhost';

GRANT ALL PRIVILEGES ON "the db name you created".* TO 'gallery'@'localhost';

**Comment by Sir-Teabag** [comment]
Hmm I'm getting another error now. I'm going to recreate the databse because everything I did above was at like 2am


mysql> GRANT ALL PRIVILEGES ON imghost.* TO 'gallery'@'localhost';
ERROR 1133 (42000): Can't find any matching row in the user table
mysql> GRANT ALL PRIVILEGES ON imghoster.* TO 'gallery'@'localhost';
ERROR 1133 (42000): Can't find any matching row in the user table

**Comment by Sir-Teabag** [comment]
Still getting this error with the new database


mysql> GRANT ALL PRIVILEGES ON root.* TO 'gallery2'@'localhost';
ERROR 1133 (42000): Can't find any matching row in the user table
mysql>

**Comment by ilias-sp** [comment]
you are not doing it correctly. what is the name of the DB you created, and the user you want to connect with?

by the way, these are stored in data/config.php of Lychee.

**Comment by Sir-Teabag** [comment]
Aha sorry I'm still really new to this stuff.

database name: root
databse username: gallery2
database pass: normalpass (for example)

Also am I supposed to create that file? Or could you provide me with it as it's not in my files for some reason. https://gyazo.com/5db5026e5a472ec9ece9378f8165b92d

**Comment by Sir-Teabag** [comment]
Oh it worked! Followed instructions above and it seems to have finally created the form aha. 

Thank you so much! Appreciate it :) 👍

**Comment by ilias-sp** [comment]
Nice, glad to hear that :)

Do you have privileges to close the issue or only project admins can do it? Not so familiar with Github.

**Comment by Sir-Teabag** [comment]
Haha i'm as familiar with it as you are. I'll see waht I can do otherwise it's up to admin
