### ISSUE TITLE
Proposal: Name of the Organisation

### ISSUE THREAD

**Issue by fly-man-** [electerious/Lychee#772]
Please leave your suggestion for the Organisation in which Lychee can be put so multiple users can benefit from commiting and also be able to keep everything Lychee related (upload scripts, Docker files, etc) in 1 location.

**Comment by LudovicRousseau** [comment]
- Lychee-org (for organisation)
- Lychee-ng (for Next Generation)

**Comment by fantawttw** [comment]
Litchi as that is the genus of the Lychee (https://en.wikipedia.org/wiki/Lychee)

**Comment by tobru** [comment]
I propose either `Lychee-org` or `getlychee` (like the Twitter handle). I would be in favour to somehow keep the name `Lychee` in the name so it doesn't get confusing.

**Comment by daveballan** [comment]
Keep it simple and easily pronounceable. Too many free software projects suffer from name fail. Lychee-org would get my vote.

**Comment by illyaking** [comment]
I vote for Get Lychee, although Lychee Org makes more sense.

**Comment by petter-** [comment]
Playing with both verb and noun as well as invite users to pick this software.

PicLychee
PikLychee
PickLychee

**Comment by LudovicRousseau** [comment]
Keep in mind that we discuss the name of the github **organization** for the Lychee project.
We do not discuss the names of the repositories inside the organization.

We can still have a GetLychee project inside the Lyche-org organization. The URL would be https://github.com/Lyche-org/GetLychee
The most obvious would be to have https://github.com/Lyche-org/Lychee to host the main source code.

I think it will be confusing to have an organization name containing an action verb. The organization may also host projects that are related to Lychee (like extensions, addons, etc) so the organization name should be neutral.

**Comment by cryptomilk** [comment]
Then go with Lychee-org

**Comment by CodingFrieda** [comment]
Would switching to a Lychee organisation make trouble for [Softaculous](https://www.softaculous.com/) installations?

By the way, I would prefer @lychee as organisation name (e.g. https://github.com/lychee/app) or alternatively Lychee-org like @cryptomilk, @LudovicRousseau & @tobru.

**Comment by fly-man-** [comment]
I am glad to announce that the Lychee Organisation has been created

It lives at https://github.com/LycheeOrg
