### ISSUE TITLE
Fix "Server error or api not found" on Centos7

### ISSUE THREAD

**Issue by Evilmass** [electerious/Lychee#773]
Run `php plugins/Diagnostics/index.php`, show:

![error](https://ws1.sinaimg.cn/large/006CZ9Gwgy1fp6u5t5oppj30wq028wog.jpg)

## Centos7:
    rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

## Centos6:
    rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm

## Install PHP7:

    yum install php70w php70w-cli php70w-common php70w-mbstring php70w-gd php70w-fpm

> option: php70w-mcrypt php70w-mysql php70w-mysqli

## Enable php-fpm

    systemctl status php-fpm
    systemctl enable php-fpm
    systemctl start php-fpm
    systemctl status php-fpm

![restart_fpm](https://ws1.sinaimg.cn/large/006CZ9Gwgy1fp6u6njkjhj30yq0gmu0y.jpg)

## Configure Nginx

![nginx_conf](https://ws1.sinaimg.cn/large/006CZ9Gwgy1fp6u67xetfj30lj0aa4qp.jpg)

`vim /etc/nginx/nginx.conf`

    server {
        server_name your_server_name;
        listen 80;
        listen [::]:80;
        root /path/to/Lychee/;
        index index.html index.htm index.nginx-debian.html index.php ;
        location ~ \.php$ {
                include fastcgi.conf;
                fastcgi_index index.php;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_param PHP_VALUE "max_execution_time=1800
                                        post_max_size=1500M
                                        upload_max_filesize=32M
                                        max_input_time=1800
                                        max_file_uploads=300";
        }
    }

## Reload Nginx

    nginx -t && systemctl restart nginx

## Done

![done](https://ws1.sinaimg.cn/large/006CZ9Gwgy1fp6u80ft1mj318p0mo1l1.jpg)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
