### ISSUE TITLE
- error - Lychee\Modules\Photo::add (243) 	- Field 'position' doesn't have a default value

### ISSUE THREAD

**Issue by samnyan** [electerious/Lychee#779]
### Detailed description of the problem
When I upload a photo, it shows a error. And the log shows 
`- error - Lychee\Modules\Photo::add (243) 	- Field 'position' doesn't have a default value`
When I add the default value of position to 0 in mysql, it work fine.
but it won't return an error when I test Lychee in my local machine no matter setting the default value of position, it stay at 0 without doing anything.
### Steps to reproduce the issue
Install normally , and upload a photo. 
### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50722
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1
Plugins:         
```
### Browser and system
Ubuntu 16.04
Nginx 1.10.3
Mysql 5.7.22
php 7.0

**Comment by samnyan** [comment]
[https://github.com/LycheeOrg/Lychee/issues/2](https://github.com/LycheeOrg/Lychee/issues/2)

**Comment by williamdes** [comment]
Introduced by commit https://github.com/electerious/Lychee/commit/20a1ff2d6102e5a5f1dd2c2ffb4ca06697ea738f#diff-146441a33cbdc780f4f93217924080be
Please re open this issue.

**Comment by djolker** [comment]
> had to manually alter table to set the default value.

I'm attempting to setup a Lychee server and appear to be hitting the same issue.  Would you mind explaining how you altered the table to resolve this issue?

Thanks

**Comment by williamdes** [comment]
@djolker Added a default value for the column `position` :)

**Comment by fly-man-** [comment]
Seems I missed that. When you pull the most recent version the default value should now be set to 0. Thanks for bringing it to the attention.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
