### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by IceBoosteR** [electerious/Lychee#780]
### Detailed description of the problem
Hi,
I tried it various times on debian nad ubuntu, but I am not able to install the php dependencies which are required for lychee to operate. Someo f them cannot be found in the official repos, and also not if I use external repositories.
Some of the PHP extension are included in other packages, some are renamed. Please solve the confusion so I can make use of lychee.
### Steps to help with the issue
Create a detailled manual how to install lychee and dependencies
Update the same documentation to make use of PHP7.X (latest)

**Comment by AkselMeola** [comment]
I'm not sure what is the minimum for Lychee, but I would think that something similar from your disto's 
selection would apply. 

On top of the head i can say that required should be: mysqli, mcrypt, session, zip, exif, imagick, gd, json. 


here's the full list for my php docker containr(Alpine 3.6):

```
    apk --update add \
        bash \
        php7 \
        php7-bcmath \
        php7-dom \
        php7-ctype \
        php7-curl \
        php7-fpm \
        php7-gd \
        php7-iconv \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-mcrypt \
        php7-mysqlnd \
        php7-mysqli \
        php7-opcache \
        php7-openssl \
        php7-pdo \
        php7-pdo_mysql \
        php7-pdo_pgsql \
        php7-pdo_sqlite \
        php7-phar \
        php7-posix \
        php7-session \
        php7-soap \
        php7-xml \
        php7-zip \
        php7-imap \
        php7-exif \
        php7-imagick \
        imagemagick \
        imagemagick-dev \

```

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
