### ISSUE TITLE
Do I need a big size hard drive for Lychee

### ISSUE THREAD

**Issue by helsan74** [electerious/Lychee#787]
Was trying to find the minimum requirements foir Lychee.
Do I need a big size hard drive? Most of my photo collection is on a NAS.
But not sure if I need to have all locally or not.

Thanks for the details in advance.

Helder

**Comment by ildyria** [comment]
Lychee by itself is pretty small. What takes the biggest space are the pictures (and your OS to run Apache, Php and MySQL). So it mainly depends on how many pictures you have (and the OS).
