### ISSUE TITLE
Missing parameters.  setPositionAction

### ISSUE THREAD

**Issue by huntson** [electerious/Lychee#790]
On any page, inside an album, views of albums, if I try to drag any content around I get the following error:

Error: Missing parameters.  Can not execute function Lychee\Access\Admin::setPositionAction

The item gets dragged to the proper location however this error is produced.

I am using OS X and I have had this happen on Safari and Firefox

**Comment by ildyria** [comment]
This repo is inactive. Project moved here: https://github.com/LycheeOrg/Lychee
Try again with the moved repo and keep up updated if the issue persist.
