### ISSUE TITLE
How to rotate images in Lychee?

### ISSUE THREAD

**Issue by bigfoot50** [electerious/Lychee#792]
Hi,

how can I rotate an image in Lychee? I didn´t find the option.

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7.1
MySQL Version:   50560
Imagick:         1
Imagick Active:  1
Imagick Version: 1656
GD Version:      bundled (2.1.0 compatible)
Plugins:        

Regards

**Comment by ildyria** [comment]
1. you can't.
2. this repo is inactive. Project moved here: https://github.com/LycheeOrg/Lychee
